--------------------------------------------------------
--  파일이 생성됨 - 월요일-5월-30-2022   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table MY_CART
--------------------------------------------------------

  CREATE TABLE "NA"."MY_CART" 
   (	"CART_NO" NUMBER, 
	"CART_AMOUNT" NUMBER, 
	"CART_STATUS" VARCHAR2(10 BYTE) DEFAULT 'Y', 
	"MEM_NO" NUMBER, 
	"PRO_NO" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
REM INSERTING into NA.MY_CART
SET DEFINE OFF;
Insert into NA.MY_CART (CART_NO,CART_AMOUNT,CART_STATUS,MEM_NO,PRO_NO) values (2,2,'P',105,11);
Insert into NA.MY_CART (CART_NO,CART_AMOUNT,CART_STATUS,MEM_NO,PRO_NO) values (3,1,'P',154,8);
Insert into NA.MY_CART (CART_NO,CART_AMOUNT,CART_STATUS,MEM_NO,PRO_NO) values (4,3,'P',154,10);
Insert into NA.MY_CART (CART_NO,CART_AMOUNT,CART_STATUS,MEM_NO,PRO_NO) values (5,3,'P',154,2);
Insert into NA.MY_CART (CART_NO,CART_AMOUNT,CART_STATUS,MEM_NO,PRO_NO) values (6,1,'P',210,11);
Insert into NA.MY_CART (CART_NO,CART_AMOUNT,CART_STATUS,MEM_NO,PRO_NO) values (7,1,'R',210,12);
Insert into NA.MY_CART (CART_NO,CART_AMOUNT,CART_STATUS,MEM_NO,PRO_NO) values (8,1,'Y',0,12);
Insert into NA.MY_CART (CART_NO,CART_AMOUNT,CART_STATUS,MEM_NO,PRO_NO) values (9,1,'P',105,12);
Insert into NA.MY_CART (CART_NO,CART_AMOUNT,CART_STATUS,MEM_NO,PRO_NO) values (10,2,'P',154,11);
Insert into NA.MY_CART (CART_NO,CART_AMOUNT,CART_STATUS,MEM_NO,PRO_NO) values (11,2,'R',154,12);
Insert into NA.MY_CART (CART_NO,CART_AMOUNT,CART_STATUS,MEM_NO,PRO_NO) values (1,2,'R',105,12);
Insert into NA.MY_CART (CART_NO,CART_AMOUNT,CART_STATUS,MEM_NO,PRO_NO) values (12,1,'P',210,12);
Insert into NA.MY_CART (CART_NO,CART_AMOUNT,CART_STATUS,MEM_NO,PRO_NO) values (13,1,'R',210,11);
Insert into NA.MY_CART (CART_NO,CART_AMOUNT,CART_STATUS,MEM_NO,PRO_NO) values (14,1,'R',104,12);
Insert into NA.MY_CART (CART_NO,CART_AMOUNT,CART_STATUS,MEM_NO,PRO_NO) values (15,1,'R',216,6013);
Insert into NA.MY_CART (CART_NO,CART_AMOUNT,CART_STATUS,MEM_NO,PRO_NO) values (16,1,'P',214,12);
Insert into NA.MY_CART (CART_NO,CART_AMOUNT,CART_STATUS,MEM_NO,PRO_NO) values (17,1,'R',216,6007);
Insert into NA.MY_CART (CART_NO,CART_AMOUNT,CART_STATUS,MEM_NO,PRO_NO) values (18,4,'P',217,6060);
Insert into NA.MY_CART (CART_NO,CART_AMOUNT,CART_STATUS,MEM_NO,PRO_NO) values (19,1,'R',217,10);
Insert into NA.MY_CART (CART_NO,CART_AMOUNT,CART_STATUS,MEM_NO,PRO_NO) values (24,1,'P',219,11);
Insert into NA.MY_CART (CART_NO,CART_AMOUNT,CART_STATUS,MEM_NO,PRO_NO) values (22,1,'R',218,6049);
Insert into NA.MY_CART (CART_NO,CART_AMOUNT,CART_STATUS,MEM_NO,PRO_NO) values (23,1,'Y',220,10);
Insert into NA.MY_CART (CART_NO,CART_AMOUNT,CART_STATUS,MEM_NO,PRO_NO) values (27,1,'P',214,11);
Insert into NA.MY_CART (CART_NO,CART_AMOUNT,CART_STATUS,MEM_NO,PRO_NO) values (26,1,'R',213,8);
Insert into NA.MY_CART (CART_NO,CART_AMOUNT,CART_STATUS,MEM_NO,PRO_NO) values (28,1,'P',219,11);
--------------------------------------------------------
--  DDL for Index SYS_C007745
--------------------------------------------------------

  CREATE UNIQUE INDEX "NA"."SYS_C007745" ON "NA"."MY_CART" ("CART_NO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  Constraints for Table MY_CART
--------------------------------------------------------

  ALTER TABLE "NA"."MY_CART" ADD PRIMARY KEY ("CART_NO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "NA"."MY_CART" MODIFY ("CART_AMOUNT" NOT NULL ENABLE);
--------------------------------------------------------
--  Ref Constraints for Table MY_CART
--------------------------------------------------------

  ALTER TABLE "NA"."MY_CART" ADD FOREIGN KEY ("MEM_NO")
	  REFERENCES "NA"."MEMBER" ("MEM_NO") ENABLE;
  ALTER TABLE "NA"."MY_CART" ADD FOREIGN KEY ("PRO_NO")
	  REFERENCES "NA"."PRODUCT" ("PRO_NO") ENABLE;
