--------------------------------------------------------
--  파일이 생성됨 - 월요일-5월-30-2022   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table PRODUCT
--------------------------------------------------------

  CREATE TABLE "NA"."PRODUCT" 
   (	"PRO_NO" NUMBER, 
	"PRO_NAME" VARCHAR2(120 BYTE), 
	"PRO_PRICE" NUMBER, 
	"PRO_STOCK" NUMBER, 
	"PRO_EFFICACY" VARCHAR2(300 BYTE), 
	"PRO_DESCRIPTION" VARCHAR2(3000 BYTE), 
	"PRO_IMG_PATH" VARCHAR2(150 BYTE), 
	"PRO_ENROLL_DATE" DATE DEFAULT SYSDATE, 
	"PRO_STATUS" VARCHAR2(1 BYTE) DEFAULT 'Y'       -- 제품 등록상태

   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;

   COMMENT ON COLUMN "NA"."PRODUCT"."PRO_NO" IS '제품번호';
   COMMENT ON COLUMN "NA"."PRODUCT"."PRO_NAME" IS '제품명';
   COMMENT ON COLUMN "NA"."PRODUCT"."PRO_PRICE" IS '제품가격';
   COMMENT ON COLUMN "NA"."PRODUCT"."PRO_STOCK" IS '제품재고';
   COMMENT ON COLUMN "NA"."PRODUCT"."PRO_EFFICACY" IS '제품효능';
   COMMENT ON COLUMN "NA"."PRODUCT"."PRO_DESCRIPTION" IS '제품설명';
   COMMENT ON COLUMN "NA"."PRODUCT"."PRO_IMG_PATH" IS '제품사진경로';
   COMMENT ON COLUMN "NA"."PRODUCT"."PRO_ENROLL_DATE" IS '제품등록날짜';
   COMMENT ON COLUMN "NA"."PRODUCT"."PRO_STATUS" IS '제품진열상태';
REM INSERTING into NA.PRODUCT
SET DEFINE OFF;
Insert into NA.PRODUCT (PRO_NO,PRO_NAME,PRO_PRICE,PRO_STOCK,PRO_EFFICACY,PRO_DESCRIPTION,PRO_IMG_PATH,PRO_ENROLL_DATE,PRO_STATUS) values (3,'비타민 E',34000,200,'시력개선','에너지 이용에 필요하고
신경과 근육 기능 유지에 필요
뼈와 치아의 구성요소인 마그네슘은 세포막을 안정시키고 신경의 자극을 전달하며 지방, 단백질, 핵산의 합성에 관여합니다.

뼈를 형성하는 칼슘은 신경과 근육 기능 유지와 정상적인 혈액 응고에 필요하며 골다공증 발생 위험 감소에 도움을 줍니다.','/na/resources/upfiles/2022052923463873635.png',to_date('22/05/29','RR/MM/DD'),'Y');
Insert into NA.PRODUCT (PRO_NO,PRO_NAME,PRO_PRICE,PRO_STOCK,PRO_EFFICACY,PRO_DESCRIPTION,PRO_IMG_PATH,PRO_ENROLL_DATE,PRO_STATUS) values (4,'루테인',42000,300,'면역력증진','황반색소 밀도를 유지하여 눈 건강에 도움을 줄 수 있음
노화로 인해 망막의 황반색소 밀도가 줄어들지 않도록 루테인이 눈 건강에 도움을 줄 수 있습니다.

인체 내에서 합성되지 않아요.
루테인은 인체내에서 합성되지 않기 때문에 채소나 보충용 제품을 통해 보충하여야 합니다.

권장섭취량
10~20 mg
하루 권장 섭취량은 10~20 mg이나 식사량만으로 충족하기 어려우므로 루테인 보충용 건강기능식품을 통해 섭취하는 것이 도움이 됩니다','/na/resources/upfiles/2022052923472354166.png',to_date('22/05/29','RR/MM/DD'),'Y');
Insert into NA.PRODUCT (PRO_NO,PRO_NAME,PRO_PRICE,PRO_STOCK,PRO_EFFICACY,PRO_DESCRIPTION,PRO_IMG_PATH,PRO_ENROLL_DATE,PRO_STATUS) values (5,'마그네슘',54000,240,'에너지충전','뼈를 형성하는 칼슘은 신경과 근육 기능 유지와 정상적인 혈액 응고에 필요하며 골다공증 발생 위험 감소에 도움을 줍니다.

에너지 이용에 필요하고
신경과 근육 기능 유지에 필요
뼈와 치아의 구성요소인 마그네슘은 세포막을 안정시키고 신경의 자극을 전달하며 지방, 단백질, 핵산의 합성에 관여합니다.

칼슘을 도와
뼈의 형성과 유지에 필요
몸안의 칼슘농도를 안정적으로 유지시키는 비타민D는 골다공증 발생 위험 감소에 도움을 주는 것으로 알려져 있습니다.','/na/resources/upfiles/2022052923481025901.png',to_date('22/05/29','RR/MM/DD'),'Y');
Insert into NA.PRODUCT (PRO_NO,PRO_NAME,PRO_PRICE,PRO_STOCK,PRO_EFFICACY,PRO_DESCRIPTION,PRO_IMG_PATH,PRO_ENROLL_DATE,PRO_STATUS) values (6,'밀크씨슬',63000,100,'간기능개선','밀크시슬은 엉겅퀴라고 하는 억센 식물로 실리마린 성분을 가지고 있습니다. 실리마린 성분이 간세포를 보호하는 항산화 작용으로 간 건강에 도움을 줄 수 있습니다.

간은 침묵의 장기라 불리고 있어 생활 습관과 몸을 관찰하여 미리미리 지켜야 합니다.

유럽이 원산지라고 알려지는 밀크씨슬의 원료를 폴란드에서 가져왔습니다. 플라보노이드 복합체인 실리마린 성분이 청정한 유럽의 환경에서 재배 후 추출되어 필리 밀크씨슬에 사용되었습니다.
- 어린이, 임산부 및 수유부는 섭취를 피하십시오.
- 알레르기 반응이 나타나는 경우에는 섭취를 중단하십시오.
- 설사, 위통, 복부팽만 등의 위장관계 장애가 나타나는 경우에는 섭취에 주의하십시오.
- 이상사례 발생 시 섭취를 중단하고 전문가와 상담하십시오.
- 강력방습제(실리카겔)는 섭취하지 마십시오.
- 자세한 정보는 제품설명서를 참고하세요.','/na/resources/upfiles/2022052923491291683.png',to_date('22/05/29','RR/MM/DD'),'Y');
Insert into NA.PRODUCT (PRO_NO,PRO_NAME,PRO_PRICE,PRO_STOCK,PRO_EFFICACY,PRO_DESCRIPTION,PRO_IMG_PATH,PRO_ENROLL_DATE,PRO_STATUS) values (7,'비타민 C',74000,150,'배변활동','유해산소로부터 세포를 보호하는데 필요
비타민 C는 세포 대사과정에서 생성되는 유리라디칼을 제거함으로써 산화적 손상을 방지합니다.
결합조직 형성과 기능 유지에 필요
결합조직인 피부, 골격, 연골 등을 구성하는 콜라겐 합성에 관여하는 비타민C는 철의 흡수에도 필요합니다.','/na/resources/upfiles/2022052923495955697.png',to_date('22/05/29','RR/MM/DD'),'Y');
Insert into NA.PRODUCT (PRO_NO,PRO_NAME,PRO_PRICE,PRO_STOCK,PRO_EFFICACY,PRO_DESCRIPTION,PRO_IMG_PATH,PRO_ENROLL_DATE,PRO_STATUS) values (8,'오메가',78000,150,'피부건강','EPA 및 DHA를
함유한 rTG 오메가3
EPA 및 DHA 함유유지는 인체 내 생성이 충분하지 않아 보충해주는 것이 건강에 도움이 됩니다.
혈행개선에
도움을 줄 수 있음
EPA 및 DHA 함유유지는 간에서 중성지방의 합성을 방해하여 혈액의 흐름에 도움을 줄 수 있습니다.
 건조한 눈을 개선하여
눈건강에 도움을 줄 수 있음
뻑뻑하고 이물감이 있는 건조한 눈에 도움을 줄 수 있습니다.','/na/resources/upfiles/2022052923504183807.png',to_date('22/05/29','RR/MM/DD'),'Y');
Insert into NA.PRODUCT (PRO_NO,PRO_NAME,PRO_PRICE,PRO_STOCK,PRO_EFFICACY,PRO_DESCRIPTION,PRO_IMG_PATH,PRO_ENROLL_DATE,PRO_STATUS) values (9,'옥티코사놀',83000,200,'면역력증진','면역력 증진·피로개선·기억력개선에 도움을 줄 수 있음
홍삼에는 사포닌의 일종인 진세노사이드가 함유되어 있어 면역력 증진 및 피로개선 그리고 기억력 개선에 도움을 줄 수 있습니다.

','/na/resources/upfiles/2022052923511777809.png',to_date('22/05/29','RR/MM/DD'),'Y');
Insert into NA.PRODUCT (PRO_NO,PRO_NAME,PRO_PRICE,PRO_STOCK,PRO_EFFICACY,PRO_DESCRIPTION,PRO_IMG_PATH,PRO_ENROLL_DATE,PRO_STATUS) values (10,'프로바이오틱스',91000,200,'에너지충전','유산균 증식 및 유해균을 억제하여 장 건강에 도움을 줄 수 있음
유해한 균이 만드는 유독물질은 장에서 흡수되고, 우리 건강에 위험요인으로 작용합니다. 유산균은 유해균의 증식을 억제하여 장 건강에 도움을 줄 수 있습니다.

배변활동 원활에
도움을 줄 수 있음
유익균이 증가되고 유해균수가 억제되어 장운동 및 배변활동이 개선될 수 있습니다.
','/na/resources/upfiles/2022052923520468949.png',to_date('22/05/29','RR/MM/DD'),'Y');
Insert into NA.PRODUCT (PRO_NO,PRO_NAME,PRO_PRICE,PRO_STOCK,PRO_EFFICACY,PRO_DESCRIPTION,PRO_IMG_PATH,PRO_ENROLL_DATE,PRO_STATUS) values (12,'히알루론산 스피루리나',12000,200,'에너지충전','피부 보습에
도움을 줄 수 있음
피부 속 진피층에서 체내 수분을 저장하는 히알루론산의 보충으로 피부 보습에 도움을 줄 수 있습니다.
 피부건강·항산화에
도움을 줄 수 있음
스피루리나의 항산화물질은 활성산소로 인한 세포 내 산화스트레스 감소에 도움을 줄 수 있습니다.','/na/resources/upfiles/2022052923541758533.png',to_date('22/05/29','RR/MM/DD'),'Y');
Insert into NA.PRODUCT (PRO_NO,PRO_NAME,PRO_PRICE,PRO_STOCK,PRO_EFFICACY,PRO_DESCRIPTION,PRO_IMG_PATH,PRO_ENROLL_DATE,PRO_STATUS) values (1,'리턴업 발효효소 베이직',15000,200,'면역력증진','효소는 소화과정에 있어 섭취하는 음식물을 분해하고, 영양소 흡수를 돕는 중요한 역할을 합니다.
체내 소화에 필요한 특정효소는 나이가 들수록 감소하여, 타액 아밀라아제의 경우 노인집단의 효소량은 젊은 집단의 효소량보다 약 30배 적습니다
6가지 곡물(퀴노아/현미/밀/귀리/렌틸콩/찰보리)에 특허균주(누룩 유익균)*를 접종해 최적의 환경에서 발효시켰습니다.
','/na/resources/upfiles/2022052923444297363.png',to_date('22/05/29','RR/MM/DD'),'Y');
Insert into NA.PRODUCT (PRO_NO,PRO_NAME,PRO_PRICE,PRO_STOCK,PRO_EFFICACY,PRO_DESCRIPTION,PRO_IMG_PATH,PRO_ENROLL_DATE,PRO_STATUS) values (2,'비타민 B',25000,200,'혈액개선','활성산소로부터 인체를 보호하고높은 혈압 감소에 도움을 줄 수 있는필리 코엔자임Q10 국제표준인증(GMP, ISO_900, ISO_22000)을 받은 인도산 코엔자임Q10 원료를 식약처 1일 섭취량 (100 mg)만큼 충분히 담았습니다. 아사이베리추출분말 등 부원료 함유아사이베리추출분말, 빌베리 추출물, 포도씨앗유 등 부원료 함유비타민B1, 판토텐산, 비오틴은 탄수화물, 단백질 또는 지방의 대사에 필요하며 에너지 생성에 필요합니다.비타민B2, 나이아신은 체내 에너지 생성에 필요합니다. 활력이 없는 현대인에게 필요한 영양성분입니다.비타민B6의 섭취량은 혈중 호모시스테인 수준을 유지하는데 필요합니다.뼈를 형성하는 칼슘은 신경과 근육 기능 유지와 정상적인 혈액 응고에 필요하며 골다공증 발생 위험 감소에 도움을 줍니다.에너지 이용에 필요하고신경과 근육 기능 유지에 필요뼈와 치아의 구성요소인 마그네슘은 세포막을 안정시키고 신경의 자극을 전달하며 지방, 단백질, 핵산의 합성에 관여합니다.칼슘을 도와뼈의 형성과 유지에 필요몸안의 칼슘농도를 안정적으로 유지시키는 비타민D는 골다공증 발생 위험 감소에 도움을 주는 것으로 알려져 있습니다.','/na/resources/upfiles/2022052923454526304.png',to_date('22/05/29','RR/MM/DD'),'Y');
Insert into NA.PRODUCT (PRO_NO,PRO_NAME,PRO_PRICE,PRO_STOCK,PRO_EFFICACY,PRO_DESCRIPTION,PRO_IMG_PATH,PRO_ENROLL_DATE,PRO_STATUS) values (6002,'루테인Q',42000,300,'면역력증진','"면역력 증진·피로개선·기억력개선에 도움을 줄 수 있음','/na/resources/upfiles/2022052923472354166.png',to_date('22/05/02','RR/MM/DD'),'Y');
Insert into NA.PRODUCT (PRO_NO,PRO_NAME,PRO_PRICE,PRO_STOCK,PRO_EFFICACY,PRO_DESCRIPTION,PRO_IMG_PATH,PRO_ENROLL_DATE,PRO_STATUS) values (6003,'마그네슘W',54000,240,'에너지충전','홍삼에는 사포닌의 일종인 진세노사이드가 함유되어 있어 면역력 증진 및 피로개선 그리고 기억력 개선에 도움을 줄 수 있습니다.','/na/resources/upfiles/2022052923481025901.png',to_date('22/05/01','RR/MM/DD'),'Y');
Insert into NA.PRODUCT (PRO_NO,PRO_NAME,PRO_PRICE,PRO_STOCK,PRO_EFFICACY,PRO_DESCRIPTION,PRO_IMG_PATH,PRO_ENROLL_DATE,PRO_STATUS) values (6005,'비타민 CR',74000,150,'배변활동','홍삼에는 사포닌의 일종인 진세노사이드가 함유되어 있어 면역력 증진 및 피로개선 그리고 기억력 개선에 도움을 줄 수 있습니다.','/na/resources/upfiles/2022052923495955697.png',to_date('22/05/23','RR/MM/DD'),'Y');
Insert into NA.PRODUCT (PRO_NO,PRO_NAME,PRO_PRICE,PRO_STOCK,PRO_EFFICACY,PRO_DESCRIPTION,PRO_IMG_PATH,PRO_ENROLL_DATE,PRO_STATUS) values (6007,'옥티코사놀Y',83000,200,'면역력증진','홍삼에는 사포닌의 일종인 진세노사이드가 함유되어 있어 면역력 증진 및 피로개선 그리고 기억력 개선에 도움을 줄 수 있습니다.','/na/resources/upfiles/2022052923511777809.png',to_date('22/05/29','RR/MM/DD'),'Y');
Insert into NA.PRODUCT (PRO_NO,PRO_NAME,PRO_PRICE,PRO_STOCK,PRO_EFFICACY,PRO_DESCRIPTION,PRO_IMG_PATH,PRO_ENROLL_DATE,PRO_STATUS) values (6009,'코엔자임 Q10I',100000,300,'피부건강','홍삼에는 사포닌의 일종인 진세노사이드가 함유되어 있어 면역력 증진 및 피로개선 그리고 기억력 개선에 도움을 줄 수 있습니다.','/na/resources/upfiles/2022052923525277862.png',to_date('22/05/04','RR/MM/DD'),'Y');
Insert into NA.PRODUCT (PRO_NO,PRO_NAME,PRO_PRICE,PRO_STOCK,PRO_EFFICACY,PRO_DESCRIPTION,PRO_IMG_PATH,PRO_ENROLL_DATE,PRO_STATUS) values (6011,'리턴업 발효효소 베이직K',15000,200,'면역력증진','홍삼에는 사포닌의 일종인 진세노사이드가 함유되어 있어 면역력 증진 및 피로개선 그리고 기억력 개선에 도움을 줄 수 있습니다.','/na/resources/upfiles/2022052923444297363.png',to_date('22/05/14','RR/MM/DD'),'Y');
Insert into NA.PRODUCT (PRO_NO,PRO_NAME,PRO_PRICE,PRO_STOCK,PRO_EFFICACY,PRO_DESCRIPTION,PRO_IMG_PATH,PRO_ENROLL_DATE,PRO_STATUS) values (6013,'비타민 EH',63000,200,'에너지충전','홍삼에는 사포닌의 일종인 진세노사이드가 함유되어 있어 면역력 증진 및 피로개선 그리고 기억력 개선에 도움을 줄 수 있습니다.','/na/resources/upfiles/2022052923463873635.png',to_date('22/05/29','RR/MM/DD'),'Y');
Insert into NA.PRODUCT (PRO_NO,PRO_NAME,PRO_PRICE,PRO_STOCK,PRO_EFFICACY,PRO_DESCRIPTION,PRO_IMG_PATH,PRO_ENROLL_DATE,PRO_STATUS) values (6015,'마그네슘F',78000,240,'배변활동','높은 혈압 감소에 도움을 줄 수 있는','/na/resources/upfiles/2022052923481025901.png',to_date('22/05/24','RR/MM/DD'),'Y');
Insert into NA.PRODUCT (PRO_NO,PRO_NAME,PRO_PRICE,PRO_STOCK,PRO_EFFICACY,PRO_DESCRIPTION,PRO_IMG_PATH,PRO_ENROLL_DATE,PRO_STATUS) values (6017,'비타민 CS',91000,150,'면역력증진',' 국제표준인증(GMP, ISO_900, ISO_22000)을 받은 인도산 코엔자임Q10 원료를 식약처 1일 섭취량 (100 mg)만큼 충분히 담았습니다.','/na/resources/upfiles/2022052923495955697.png',to_date('22/05/01','RR/MM/DD'),'Y');
Insert into NA.PRODUCT (PRO_NO,PRO_NAME,PRO_PRICE,PRO_STOCK,PRO_EFFICACY,PRO_DESCRIPTION,PRO_IMG_PATH,PRO_ENROLL_DATE,PRO_STATUS) values (6018,'비타민 EAW',100000,150,'에너지충전','"활성산소로부터 인체를 보호하고','/na/resources/upfiles/2022052923504183807.png',to_date('22/05/05','RR/MM/DD'),'Y');
Insert into NA.PRODUCT (PRO_NO,PRO_NAME,PRO_PRICE,PRO_STOCK,PRO_EFFICACY,PRO_DESCRIPTION,PRO_IMG_PATH,PRO_ENROLL_DATE,PRO_STATUS) values (6021,'밀크씨슬C',25000,300,'면역력증진',' 국제표준인증(GMP, ISO_900, ISO_22000)을 받은 인도산 코엔자임Q10 원료를 식약처 1일 섭취량 (100 mg)만큼 충분히 담았습니다.','/na/resources/upfiles/2022052923525277862.png',to_date('22/05/29','RR/MM/DD'),'Y');
Insert into NA.PRODUCT (PRO_NO,PRO_NAME,PRO_PRICE,PRO_STOCK,PRO_EFFICACY,PRO_DESCRIPTION,PRO_IMG_PATH,PRO_ENROLL_DATE,PRO_STATUS) values (6022,'비타민 CV',34000,200,'혈액개선','"활성산소로부터 인체를 보호하고','/na/resources/upfiles/2022052923541758533.png',to_date('22/05/01','RR/MM/DD'),'Y');
Insert into NA.PRODUCT (PRO_NO,PRO_NAME,PRO_PRICE,PRO_STOCK,PRO_EFFICACY,PRO_DESCRIPTION,PRO_IMG_PATH,PRO_ENROLL_DATE,PRO_STATUS) values (6025,'프로바이오틱스N',63000,200,'에너지충전',' 국제표준인증(GMP, ISO_900, ISO_22000)을 받은 인도산 코엔자임Q10 원료를 식약처 1일 섭취량 (100 mg)만큼 충분히 담았습니다.','/na/resources/upfiles/2022052923481025901.png',to_date('22/05/14','RR/MM/DD'),'Y');
Insert into NA.PRODUCT (PRO_NO,PRO_NAME,PRO_PRICE,PRO_STOCK,PRO_EFFICACY,PRO_DESCRIPTION,PRO_IMG_PATH,PRO_ENROLL_DATE,PRO_STATUS) values (6031,'루테인TY',83000,200,'피부건강','아사이베리추출분말, 빌베리 추출물, 포도씨앗유 등 부원료 함유"','/na/resources/upfiles/2022052923525277862.png',to_date('22/05/01','RR/MM/DD'),'Y');
Insert into NA.PRODUCT (PRO_NO,PRO_NAME,PRO_PRICE,PRO_STOCK,PRO_EFFICACY,PRO_DESCRIPTION,PRO_IMG_PATH,PRO_ENROLL_DATE,PRO_STATUS) values (6032,'마그네슘YU',91000,200,'면역력증진','뼈를 형성하는 칼슘은 신경과 근육 기능 유지와 정상적인 혈액 응고에 필요하며 골다공증 발생 위험 감소에 도움을 줍니다."','/na/resources/upfiles/2022052923541758533.png',to_date('22/05/05','RR/MM/DD'),'Y');
Insert into NA.PRODUCT (PRO_NO,PRO_NAME,PRO_PRICE,PRO_STOCK,PRO_EFFICACY,PRO_DESCRIPTION,PRO_IMG_PATH,PRO_ENROLL_DATE,PRO_STATUS) values (6034,'비타민 IO',12000,200,'피부건강','노화로 인해 망막의 황반색소 밀도가 줄어들지 않도록 루테인이 눈 건강에 도움을 줄 수 있습니다.','/na/resources/upfiles/2022052923454526304.png',to_date('22/05/12','RR/MM/DD'),'Y');
Insert into NA.PRODUCT (PRO_NO,PRO_NAME,PRO_PRICE,PRO_STOCK,PRO_EFFICACY,PRO_DESCRIPTION,PRO_IMG_PATH,PRO_ENROLL_DATE,PRO_STATUS) values (6037,'프로바이오틱스SD',34000,300,'혈액개선','루테인은 인체내에서 합성되지 않기 때문에 채소나 보충용 제품을 통해 보충하여야 합니다.','/na/resources/upfiles/2022052923481025901.png',to_date('22/05/04','RR/MM/DD'),'Y');
Insert into NA.PRODUCT (PRO_NO,PRO_NAME,PRO_PRICE,PRO_STOCK,PRO_EFFICACY,PRO_DESCRIPTION,PRO_IMG_PATH,PRO_ENROLL_DATE,PRO_STATUS) values (6041,'비타민 BGH',74000,200,'간기능개선',' 국제표준인증(GMP, ISO_900, ISO_22000)을 받은 인도산 코엔자임Q10 원료를 식약처 1일 섭취량 (100 mg)만큼 충분히 담았습니다.','/na/resources/upfiles/2022052923511777809.png',to_date('22/05/29','RR/MM/DD'),'Y');
Insert into NA.PRODUCT (PRO_NO,PRO_NAME,PRO_PRICE,PRO_STOCK,PRO_EFFICACY,PRO_DESCRIPTION,PRO_IMG_PATH,PRO_ENROLL_DATE,PRO_STATUS) values (6042,'비타민 EHJ',78000,300,'배변활동','홍삼에는 사포닌의 일종인 진세노사이드가 함유되어 있어 면역력 증진 및 피로개선 그리고 기억력 개선에 도움을 줄 수 있습니다.','/na/resources/upfiles/2022052923520468949.png',to_date('22/05/29','RR/MM/DD'),'Y');
Insert into NA.PRODUCT (PRO_NO,PRO_NAME,PRO_PRICE,PRO_STOCK,PRO_EFFICACY,PRO_DESCRIPTION,PRO_IMG_PATH,PRO_ENROLL_DATE,PRO_STATUS) values (6050,'밀크씨슬BN',12000,200,'에너지충전','스피루리나의 항산화물질은 활성산소로 인한 세포 내 산화스트레스 감소에 도움을 줄 수 있습니다."','/na/resources/upfiles/2022052923491291683.png',to_date('22/05/01','RR/MM/DD'),'Y');
Insert into NA.PRODUCT (PRO_NO,PRO_NAME,PRO_PRICE,PRO_STOCK,PRO_EFFICACY,PRO_DESCRIPTION,PRO_IMG_PATH,PRO_ENROLL_DATE,PRO_STATUS) values (6051,'비타민 CNM',15000,200,'간기능개선','피부 속 진피층에서 체내 수분을 저장하는 히알루론산의 보충으로 피부 보습에 도움을 줄 수 있습니다.','/na/resources/upfiles/2022052923495955697.png',to_date('22/05/04','RR/MM/DD'),'Y');
Insert into NA.PRODUCT (PRO_NO,PRO_NAME,PRO_PRICE,PRO_STOCK,PRO_EFFICACY,PRO_DESCRIPTION,PRO_IMG_PATH,PRO_ENROLL_DATE,PRO_STATUS) values (6054,'프로바이오틱스3',74000,300,'면역력증진','스피루리나의 항산화물질은 활성산소로 인한 세포 내 산화스트레스 감소에 도움을 줄 수 있습니다."','/na/resources/upfiles/2022052923520468949.png',to_date('22/05/15','RR/MM/DD'),'Y');
Insert into NA.PRODUCT (PRO_NO,PRO_NAME,PRO_PRICE,PRO_STOCK,PRO_EFFICACY,PRO_DESCRIPTION,PRO_IMG_PATH,PRO_ENROLL_DATE,PRO_STATUS) values (6057,'리턴업 발효효소 베이직6',91000,150,'에너지충전','스피루리나의 항산화물질은 활성산소로 인한 세포 내 산화스트레스 감소에 도움을 줄 수 있습니다."','/na/resources/upfiles/2022052923495955697.png',to_date('22/05/24','RR/MM/DD'),'Y');
Insert into NA.PRODUCT (PRO_NO,PRO_NAME,PRO_PRICE,PRO_STOCK,PRO_EFFICACY,PRO_DESCRIPTION,PRO_IMG_PATH,PRO_ENROLL_DATE,PRO_STATUS) values (6060,'루테인9',15000,200,'시력개선','스피루리나의 항산화물질은 활성산소로 인한 세포 내 산화스트레스 감소에 도움을 줄 수 있습니다."','/na/resources/upfiles/2022052923520468949.png',to_date('22/05/05','RR/MM/DD'),'Y');
Insert into NA.PRODUCT (PRO_NO,PRO_NAME,PRO_PRICE,PRO_STOCK,PRO_EFFICACY,PRO_DESCRIPTION,PRO_IMG_PATH,PRO_ENROLL_DATE,PRO_STATUS) values (6062,'밀크씨슬12',34000,200,'에너지충전','스피루리나의 항산화물질은 활성산소로 인한 세포 내 산화스트레스 감소에 도움을 줄 수 있습니다."','/na/resources/upfiles/2022052923541758533.png',to_date('22/05/12','RR/MM/DD'),'Y');
Insert into NA.PRODUCT (PRO_NO,PRO_NAME,PRO_PRICE,PRO_STOCK,PRO_EFFICACY,PRO_DESCRIPTION,PRO_IMG_PATH,PRO_ENROLL_DATE,PRO_STATUS) values (6063,'비타민 C23',42000,200,'면역력증진','홍삼에는 사포닌의 일종인 진세노사이드가 함유되어 있어 면역력 증진 및 피로개선 그리고 기억력 개선에 도움을 줄 수 있습니다.','/na/resources/upfiles/2022052923444297363.png',to_date('22/05/29','RR/MM/DD'),'Y');
Insert into NA.PRODUCT (PRO_NO,PRO_NAME,PRO_PRICE,PRO_STOCK,PRO_EFFICACY,PRO_DESCRIPTION,PRO_IMG_PATH,PRO_ENROLL_DATE,PRO_STATUS) values (6064,'오메가34',54000,200,'에너지충전','홍삼에는 사포닌의 일종인 진세노사이드가 함유되어 있어 면역력 증진 및 피로개선 그리고 기억력 개선에 도움을 줄 수 있습니다.','/na/resources/upfiles/2022052923454526304.png',to_date('22/05/01','RR/MM/DD'),'Y');
Insert into NA.PRODUCT (PRO_NO,PRO_NAME,PRO_PRICE,PRO_STOCK,PRO_EFFICACY,PRO_DESCRIPTION,PRO_IMG_PATH,PRO_ENROLL_DATE,PRO_STATUS) values (6065,'옥티코사놀45',63000,200,'피부건강','홍삼에는 사포닌의 일종인 진세노사이드가 함유되어 있어 면역력 증진 및 피로개선 그리고 기억력 개선에 도움을 줄 수 있습니다.','/na/resources/upfiles/2022052923463873635.png',to_date('22/05/04','RR/MM/DD'),'Y');
Insert into NA.PRODUCT (PRO_NO,PRO_NAME,PRO_PRICE,PRO_STOCK,PRO_EFFICACY,PRO_DESCRIPTION,PRO_IMG_PATH,PRO_ENROLL_DATE,PRO_STATUS) values (6066,'프로바이오틱스56',74000,300,'에너지충전','홍삼에는 사포닌의 일종인 진세노사이드가 함유되어 있어 면역력 증진 및 피로개선 그리고 기억력 개선에 도움을 줄 수 있습니다.','/na/resources/upfiles/2022052923472354166.png',to_date('22/05/22','RR/MM/DD'),'Y');
Insert into NA.PRODUCT (PRO_NO,PRO_NAME,PRO_PRICE,PRO_STOCK,PRO_EFFICACY,PRO_DESCRIPTION,PRO_IMG_PATH,PRO_ENROLL_DATE,PRO_STATUS) values (6067,'코엔자임 Q1067',78000,240,'면역력증진','홍삼에는 사포닌의 일종인 진세노사이드가 함유되어 있어 면역력 증진 및 피로개선 그리고 기억력 개선에 도움을 줄 수 있습니다.','/na/resources/upfiles/2022052923481025901.png',to_date('22/05/14','RR/MM/DD'),'Y');
Insert into NA.PRODUCT (PRO_NO,PRO_NAME,PRO_PRICE,PRO_STOCK,PRO_EFFICACY,PRO_DESCRIPTION,PRO_IMG_PATH,PRO_ENROLL_DATE,PRO_STATUS) values (6068,'히알루론산 스피루리나78',63000,100,'혈액개선','홍삼에는 사포닌의 일종인 진세노사이드가 함유되어 있어 면역력 증진 및 피로개선 그리고 기억력 개선에 도움을 줄 수 있습니다.','/na/resources/upfiles/2022052923491291683.png',to_date('22/05/15','RR/MM/DD'),'Y');
Insert into NA.PRODUCT (PRO_NO,PRO_NAME,PRO_PRICE,PRO_STOCK,PRO_EFFICACY,PRO_DESCRIPTION,PRO_IMG_PATH,PRO_ENROLL_DATE,PRO_STATUS) values (6072,'루테인WS',91000,200,'간기능개선',' 국제표준인증(GMP, ISO_900, ISO_22000)을 받은 인도산 코엔자임Q10 원료를 식약처 1일 섭취량 (100 mg)만큼 충분히 담았습니다.','/na/resources/upfiles/2022052923520468949.png',to_date('22/05/29','RR/MM/DD'),'Y');
Insert into NA.PRODUCT (PRO_NO,PRO_NAME,PRO_PRICE,PRO_STOCK,PRO_EFFICACY,PRO_DESCRIPTION,PRO_IMG_PATH,PRO_ENROLL_DATE,PRO_STATUS) values (6075,'비타민 CRF',15000,300,'면역력증진','활성산소로부터 인체를 보호하고높은 혈압 감소에 도움을 줄 수 있는필리 코엔자임Q10 국제표준인증(GMP, ISO_900, ISO_22000)을 받은 인도산 코엔자임Q10 원료를 식약처 1일 섭취량 (100 mg)만큼 충분히 담았습니다. 아사이베리추출분말 등 부원료 함유아사이베리추출분말, 빌베리 추출물, 포도씨앗유 등 부원료 함유비타민B1, 판토텐산, 비오틴은 탄수화물, 단백질 또는 지방의 대사에 필요하며 에너지 생성에 필요합니다.비타민B2, 나이아신은 체내 에너지 생성에 필요합니다. 활력이 없는 현대인에게 필요한 영양성분입니다.비타민B6의 섭취량은 혈중 호모시스테인 수준을 유지하는데 필요합니다.뼈를 형성하는 칼슘은 신경과 근육 기능 유지와 정상적인 혈액 응고에 필요하며 골다공증 발생 위험 감소에 도움을 줍니다.에너지 이용에 필요하고신경과 근육 기능 유지에 필요뼈와 치아의 구성요소인 마그네슘은 세포막을 안정시키고 신경의 자극을 전달하며 지방, 단백질, 핵산의 합성에 관여합니다.칼슘을 도와뼈의 형성과 유지에 필요몸안의 칼슘농도를 안정적으로 유지시키는 비타민D는 골다공증 발생 위험 감소에 도움을 주는 것으로 알려져 있습니다.','/na/resources/upfiles/2022052923444297363.png',to_date('22/05/02','RR/MM/DD'),'Y');
Insert into NA.PRODUCT (PRO_NO,PRO_NAME,PRO_PRICE,PRO_STOCK,PRO_EFFICACY,PRO_DESCRIPTION,PRO_IMG_PATH,PRO_ENROLL_DATE,PRO_STATUS) values (6085,'히알루론산 스피루리나RR',100000,200,'면역력증진','홍삼에는 사포닌의 일종인 진세노사이드가 함유되어 있어 면역력 증진 및 피로개선 그리고 기억력 개선에 도움을 줄 수 있습니다.','/na/resources/upfiles/2022052923481025901.png',to_date('22/05/15','RR/MM/DD'),'Y');
Insert into NA.PRODUCT (PRO_NO,PRO_NAME,PRO_PRICE,PRO_STOCK,PRO_EFFICACY,PRO_DESCRIPTION,PRO_IMG_PATH,PRO_ENROLL_DATE,PRO_STATUS) values (6087,'비타민 BYY',15000,300,'피부건강','아사이베리추출분말, 빌베리 추출물, 포도씨앗유 등 부원료 함유','/na/resources/upfiles/2022052923495955697.png',to_date('22/05/29','RR/MM/DD'),'Y');
Insert into NA.PRODUCT (PRO_NO,PRO_NAME,PRO_PRICE,PRO_STOCK,PRO_EFFICACY,PRO_DESCRIPTION,PRO_IMG_PATH,PRO_ENROLL_DATE,PRO_STATUS) values (6089,'루테인AA',63000,100,'면역력증진','비타민B2, 나이아신은 체내 에너지 생성에 필요합니다. 활력이 없는 현대인에게 필요한 영양성분입니다.','/na/resources/upfiles/2022052923511777809.png',to_date('22/05/22','RR/MM/DD'),'Y');
Insert into NA.PRODUCT (PRO_NO,PRO_NAME,PRO_PRICE,PRO_STOCK,PRO_EFFICACY,PRO_DESCRIPTION,PRO_IMG_PATH,PRO_ENROLL_DATE,PRO_STATUS) values (6090,'마그네슘SS',74000,150,'혈액개선','비타민B6의 섭취량은 혈중 호모시스테인 수준을 유지하는데 필요합니다.','/na/resources/upfiles/2022052923520468949.png',to_date('22/05/14','RR/MM/DD'),'Y');
Insert into NA.PRODUCT (PRO_NO,PRO_NAME,PRO_PRICE,PRO_STOCK,PRO_EFFICACY,PRO_DESCRIPTION,PRO_IMG_PATH,PRO_ENROLL_DATE,PRO_STATUS) values (6091,'밀크씨슬DD',78000,150,'시력개선','홍삼에는 사포닌의 일종인 진세노사이드가 함유되어 있어 면역력 증진 및 피로개선 그리고 기억력 개선에 도움을 줄 수 있습니다.','/na/resources/upfiles/2022052923525277862.png',to_date('22/05/15','RR/MM/DD'),'Y');
Insert into NA.PRODUCT (PRO_NO,PRO_NAME,PRO_PRICE,PRO_STOCK,PRO_EFFICACY,PRO_DESCRIPTION,PRO_IMG_PATH,PRO_ENROLL_DATE,PRO_STATUS) values (6092,'비타민 CFF',83000,200,'면역력증진','홍삼에는 사포닌의 일종인 진세노사이드가 함유되어 있어 면역력 증진 및 피로개선 그리고 기억력 개선에 도움을 줄 수 있습니다.','/na/resources/upfiles/2022052923541758533.png',to_date('22/05/29','RR/MM/DD'),'Y');
Insert into NA.PRODUCT (PRO_NO,PRO_NAME,PRO_PRICE,PRO_STOCK,PRO_EFFICACY,PRO_DESCRIPTION,PRO_IMG_PATH,PRO_ENROLL_DATE,PRO_STATUS) values (6095,'프로바이오틱스ZZ',12000,200,'피부건강','뼈와 치아의 구성요소인 마그네슘은 세포막을 안정시키고 신경의 자극을 전달하며 지방, 단백질, 핵산의 합성에 관여합니다.','/na/resources/upfiles/2022052923463873635.png',to_date('22/05/02','RR/MM/DD'),'Y');
Insert into NA.PRODUCT (PRO_NO,PRO_NAME,PRO_PRICE,PRO_STOCK,PRO_EFFICACY,PRO_DESCRIPTION,PRO_IMG_PATH,PRO_ENROLL_DATE,PRO_STATUS) values (6096,'코엔자임 Q10XX',15000,200,'에너지충전','홍삼에는 사포닌의 일종인 진세노사이드가 함유되어 있어 면역력 증진 및 피로개선 그리고 기억력 개선에 도움을 줄 수 있습니다.','/na/resources/upfiles/2022052923472354166.png',to_date('22/05/01','RR/MM/DD'),'Y');
Insert into NA.PRODUCT (PRO_NO,PRO_NAME,PRO_PRICE,PRO_STOCK,PRO_EFFICACY,PRO_DESCRIPTION,PRO_IMG_PATH,PRO_ENROLL_DATE,PRO_STATUS) values (6099,'비타민 BBB',42000,300,'시력개선','몸안의 칼슘농도를 안정적으로 유지시키는 비타민D는 골다공증 발생 위험 감소에 도움을 주는 것으로 알려져 있습니다.','/na/resources/upfiles/2022052923495955697.png',to_date('22/05/12','RR/MM/DD'),'Y');
Insert into NA.PRODUCT (PRO_NO,PRO_NAME,PRO_PRICE,PRO_STOCK,PRO_EFFICACY,PRO_DESCRIPTION,PRO_IMG_PATH,PRO_ENROLL_DATE,PRO_STATUS) values (6100,'비타민 ENN',54000,240,'면역력증진','홍삼에는 사포닌의 일종인 진세노사이드가 함유되어 있어 면역력 증진 및 피로개선 그리고 기억력 개선에 도움을 줄 수 있습니다.','/na/resources/upfiles/2022052923504183807.png',to_date('22/05/29','RR/MM/DD'),'Y');
Insert into NA.PRODUCT (PRO_NO,PRO_NAME,PRO_PRICE,PRO_STOCK,PRO_EFFICACY,PRO_DESCRIPTION,PRO_IMG_PATH,PRO_ENROLL_DATE,PRO_STATUS) values (6104,'비타민 C33',63000,200,'피부건강','홍삼에는 사포닌의 일종인 진세노사이드가 함유되어 있어 면역력 증진 및 피로개선 그리고 기억력 개선에 도움을 줄 수 있습니다.','/na/resources/upfiles/2022052923541758533.png',to_date('22/05/14','RR/MM/DD'),'Y');
Insert into NA.PRODUCT (PRO_NO,PRO_NAME,PRO_PRICE,PRO_STOCK,PRO_EFFICACY,PRO_DESCRIPTION,PRO_IMG_PATH,PRO_ENROLL_DATE,PRO_STATUS) values (6107,'마그네슘66',83000,200,'피부건강','홍삼에는 사포닌의 일종인 진세노사이드가 함유되어 있어 면역력 증진 및 피로개선 그리고 기억력 개선에 도움을 줄 수 있습니다.','/na/resources/upfiles/2022052923463873635.png',to_date('22/05/29','RR/MM/DD'),'Y');
Insert into NA.PRODUCT (PRO_NO,PRO_NAME,PRO_PRICE,PRO_STOCK,PRO_EFFICACY,PRO_DESCRIPTION,PRO_IMG_PATH,PRO_ENROLL_DATE,PRO_STATUS) values (6109,'비타민 C88',100000,240,'면역력증진','홍삼에는 사포닌의 일종인 진세노사이드가 함유되어 있어 면역력 증진 및 피로개선 그리고 기억력 개선에 도움을 줄 수 있습니다.','/na/resources/upfiles/2022052923481025901.png',to_date('22/05/22','RR/MM/DD'),'Y');
Insert into NA.PRODUCT (PRO_NO,PRO_NAME,PRO_PRICE,PRO_STOCK,PRO_EFFICACY,PRO_DESCRIPTION,PRO_IMG_PATH,PRO_ENROLL_DATE,PRO_STATUS) values (6112,'프로바이오틱스EF',25000,150,'간기능개선','홍삼에는 사포닌의 일종인 진세노사이드가 함유되어 있어 면역력 증진 및 피로개선 그리고 기억력 개선에 도움을 줄 수 있습니다.','/na/resources/upfiles/2022052923504183807.png',to_date('22/05/29','RR/MM/DD'),'Y');
Insert into NA.PRODUCT (PRO_NO,PRO_NAME,PRO_PRICE,PRO_STOCK,PRO_EFFICACY,PRO_DESCRIPTION,PRO_IMG_PATH,PRO_ENROLL_DATE,PRO_STATUS) values (6115,'리턴업 발효효소 베이직YJ',54000,300,'면역력증진','홍삼에는 사포닌의 일종인 진세노사이드가 함유되어 있어 면역력 증진 및 피로개선 그리고 기억력 개선에 도움을 줄 수 있습니다.','/na/resources/upfiles/2022052923481025901.png',to_date('22/05/02','RR/MM/DD'),'Y');
Insert into NA.PRODUCT (PRO_NO,PRO_NAME,PRO_PRICE,PRO_STOCK,PRO_EFFICACY,PRO_DESCRIPTION,PRO_IMG_PATH,PRO_ENROLL_DATE,PRO_STATUS) values (6117,'비타민 EIL',74000,200,'피부건강','홍삼에는 사포닌의 일종인 진세노사이드가 함유되어 있어 면역력 증진 및 피로개선 그리고 기억력 개선에 도움을 줄 수 있습니다.','/na/resources/upfiles/2022052923495955697.png',to_date('22/05/05','RR/MM/DD'),'Y');
Insert into NA.PRODUCT (PRO_NO,PRO_NAME,PRO_PRICE,PRO_STOCK,PRO_EFFICACY,PRO_DESCRIPTION,PRO_IMG_PATH,PRO_ENROLL_DATE,PRO_STATUS) values (11,'코엔자임 Q10',100000,300,'피부건강','활성산소로부터 인체를 보호하고높은 혈압 감소에 도움을 줄 수 있는필리 코엔자임Q10 국제표준인증(GMP, ISO_900, ISO_22000)을 받은 인도산 코엔자임Q10 원료를 식약처 1일 섭취량 (100 mg)만큼 충분히 담았습니다. 아사이베리추출분말 등 부원료 함유아사이베리추출분말, 빌베리 추출물, 포도씨앗유 등 부원료 함유비타민B1, 판토텐산, 비오틴은 탄수화물, 단백질 또는 지방의 대사에 필요하며 에너지 생성에 필요합니다.비타민B2, 나이아신은 체내 에너지 생성에 필요합니다. 활력이 없는 현대인에게 필요한 영양성분입니다.비타민B6의 섭취량은 혈중 호모시스테인 수준을 유지하는데 필요합니다.뼈를 형성하는 칼슘은 신경과 근육 기능 유지와 정상적인 혈액 응고에 필요하며 골다공증 발생 위험 감소에 도움을 줍니다.에너지 이용에 필요하고신경과 근육 기능 유지에 필요뼈와 치아의 구성요소인 마그네슘은 세포막을 안정시키고 신경의 자극을 전달하며 지방, 단백질, 핵산의 합성에 관여합니다.칼슘을 도와뼈의 형성과 유지에 필요몸안의 칼슘농도를 안정적으로 유지시키는 비타민D는 골다공증 발생 위험 감소에 도움을 주는 것으로 알려져 있습니다.','/na/resources/upfiles/2022052923525277862.png',to_date('22/05/29','RR/MM/DD'),'Y');
Insert into NA.PRODUCT (PRO_NO,PRO_NAME,PRO_PRICE,PRO_STOCK,PRO_EFFICACY,PRO_DESCRIPTION,PRO_IMG_PATH,PRO_ENROLL_DATE,PRO_STATUS) values (6001,'비타민 EA',34000,200,'시력개선','활성산소로부터 인체를 보호하고높은 혈압 감소에 도움을 줄 수 있는필리 코엔자임Q10 국제표준인증(GMP, ISO_900, ISO_22000)을 받은 인도산 코엔자임Q10 원료를 식약처 1일 섭취량 (100 mg)만큼 충분히 담았습니다. 아사이베리추출분말 등 부원료 함유아사이베리추출분말, 빌베리 추출물, 포도씨앗유 등 부원료 함유비타민B1, 판토텐산, 비오틴은 탄수화물, 단백질 또는 지방의 대사에 필요하며 에너지 생성에 필요합니다.비타민B2, 나이아신은 체내 에너지 생성에 필요합니다. 활력이 없는 현대인에게 필요한 영양성분입니다.비타민B6의 섭취량은 혈중 호모시스테인 수준을 유지하는데 필요합니다.뼈를 형성하는 칼슘은 신경과 근육 기능 유지와 정상적인 혈액 응고에 필요하며 골다공증 발생 위험 감소에 도움을 줍니다.에너지 이용에 필요하고신경과 근육 기능 유지에 필요뼈와 치아의 구성요소인 마그네슘은 세포막을 안정시키고 신경의 자극을 전달하며 지방, 단백질, 핵산의 합성에 관여합니다.칼슘을 도와뼈의 형성과 유지에 필요몸안의 칼슘농도를 안정적으로 유지시키는 비타민D는 골다공증 발생 위험 감소에 도움을 주는 것으로 알려져 있습니다.','/na/resources/upfiles/2022052923463873635.png',to_date('22/05/24','RR/MM/DD'),'Y');
Insert into NA.PRODUCT (PRO_NO,PRO_NAME,PRO_PRICE,PRO_STOCK,PRO_EFFICACY,PRO_DESCRIPTION,PRO_IMG_PATH,PRO_ENROLL_DATE,PRO_STATUS) values (6004,'밀크씨슬E',63000,100,'간기능개선','활성산소로부터 인체를 보호하고높은 혈압 감소에 도움을 줄 수 있는필리 코엔자임Q10 국제표준인증(GMP, ISO_900, ISO_22000)을 받은 인도산 코엔자임Q10 원료를 식약처 1일 섭취량 (100 mg)만큼 충분히 담았습니다. 아사이베리추출분말 등 부원료 함유아사이베리추출분말, 빌베리 추출물, 포도씨앗유 등 부원료 함유비타민B1, 판토텐산, 비오틴은 탄수화물, 단백질 또는 지방의 대사에 필요하며 에너지 생성에 필요합니다.비타민B2, 나이아신은 체내 에너지 생성에 필요합니다. 활력이 없는 현대인에게 필요한 영양성분입니다.비타민B6의 섭취량은 혈중 호모시스테인 수준을 유지하는데 필요합니다.뼈를 형성하는 칼슘은 신경과 근육 기능 유지와 정상적인 혈액 응고에 필요하며 골다공증 발생 위험 감소에 도움을 줍니다.에너지 이용에 필요하고신경과 근육 기능 유지에 필요뼈와 치아의 구성요소인 마그네슘은 세포막을 안정시키고 신경의 자극을 전달하며 지방, 단백질, 핵산의 합성에 관여합니다.칼슘을 도와뼈의 형성과 유지에 필요몸안의 칼슘농도를 안정적으로 유지시키는 비타민D는 골다공증 발생 위험 감소에 도움을 주는 것으로 알려져 있습니다.','/na/resources/upfiles/2022052923491291683.png',to_date('22/05/05','RR/MM/DD'),'Y');
Insert into NA.PRODUCT (PRO_NO,PRO_NAME,PRO_PRICE,PRO_STOCK,PRO_EFFICACY,PRO_DESCRIPTION,PRO_IMG_PATH,PRO_ENROLL_DATE,PRO_STATUS) values (6006,'오메가T',78000,150,'피부건강','활성산소로부터 인체를 보호하고높은 혈압 감소에 도움을 줄 수 있는필리 코엔자임Q10 국제표준인증(GMP, ISO_900, ISO_22000)을 받은 인도산 코엔자임Q10 원료를 식약처 1일 섭취량 (100 mg)만큼 충분히 담았습니다. 아사이베리추출분말 등 부원료 함유아사이베리추출분말, 빌베리 추출물, 포도씨앗유 등 부원료 함유비타민B1, 판토텐산, 비오틴은 탄수화물, 단백질 또는 지방의 대사에 필요하며 에너지 생성에 필요합니다.비타민B2, 나이아신은 체내 에너지 생성에 필요합니다. 활력이 없는 현대인에게 필요한 영양성분입니다.비타민B6의 섭취량은 혈중 호모시스테인 수준을 유지하는데 필요합니다.뼈를 형성하는 칼슘은 신경과 근육 기능 유지와 정상적인 혈액 응고에 필요하며 골다공증 발생 위험 감소에 도움을 줍니다.에너지 이용에 필요하고신경과 근육 기능 유지에 필요뼈와 치아의 구성요소인 마그네슘은 세포막을 안정시키고 신경의 자극을 전달하며 지방, 단백질, 핵산의 합성에 관여합니다.칼슘을 도와뼈의 형성과 유지에 필요몸안의 칼슘농도를 안정적으로 유지시키는 비타민D는 골다공증 발생 위험 감소에 도움을 주는 것으로 알려져 있습니다.','/na/resources/upfiles/2022052923504183807.png',to_date('22/05/12','RR/MM/DD'),'Y');
Insert into NA.PRODUCT (PRO_NO,PRO_NAME,PRO_PRICE,PRO_STOCK,PRO_EFFICACY,PRO_DESCRIPTION,PRO_IMG_PATH,PRO_ENROLL_DATE,PRO_STATUS) values (6008,'프로바이오틱스U',91000,200,'에너지충전','활성산소로부터 인체를 보호하고높은 혈압 감소에 도움을 줄 수 있는필리 코엔자임Q10 국제표준인증(GMP, ISO_900, ISO_22000)을 받은 인도산 코엔자임Q10 원료를 식약처 1일 섭취량 (100 mg)만큼 충분히 담았습니다. 아사이베리추출분말 등 부원료 함유아사이베리추출분말, 빌베리 추출물, 포도씨앗유 등 부원료 함유비타민B1, 판토텐산, 비오틴은 탄수화물, 단백질 또는 지방의 대사에 필요하며 에너지 생성에 필요합니다.비타민B2, 나이아신은 체내 에너지 생성에 필요합니다. 활력이 없는 현대인에게 필요한 영양성분입니다.비타민B6의 섭취량은 혈중 호모시스테인 수준을 유지하는데 필요합니다.뼈를 형성하는 칼슘은 신경과 근육 기능 유지와 정상적인 혈액 응고에 필요하며 골다공증 발생 위험 감소에 도움을 줍니다.에너지 이용에 필요하고신경과 근육 기능 유지에 필요뼈와 치아의 구성요소인 마그네슘은 세포막을 안정시키고 신경의 자극을 전달하며 지방, 단백질, 핵산의 합성에 관여합니다.칼슘을 도와뼈의 형성과 유지에 필요몸안의 칼슘농도를 안정적으로 유지시키는 비타민D는 골다공증 발생 위험 감소에 도움을 주는 것으로 알려져 있습니다.','/na/resources/upfiles/2022052923520468949.png',to_date('22/05/01','RR/MM/DD'),'Y');
Insert into NA.PRODUCT (PRO_NO,PRO_NAME,PRO_PRICE,PRO_STOCK,PRO_EFFICACY,PRO_DESCRIPTION,PRO_IMG_PATH,PRO_ENROLL_DATE,PRO_STATUS) values (6010,'히알루론산 스피루리나O',12000,200,'에너지충전','활성산소로부터 인체를 보호하고높은 혈압 감소에 도움을 줄 수 있는필리 코엔자임Q10 국제표준인증(GMP, ISO_900, ISO_22000)을 받은 인도산 코엔자임Q10 원료를 식약처 1일 섭취량 (100 mg)만큼 충분히 담았습니다. 아사이베리추출분말 등 부원료 함유아사이베리추출분말, 빌베리 추출물, 포도씨앗유 등 부원료 함유비타민B1, 판토텐산, 비오틴은 탄수화물, 단백질 또는 지방의 대사에 필요하며 에너지 생성에 필요합니다.비타민B2, 나이아신은 체내 에너지 생성에 필요합니다. 활력이 없는 현대인에게 필요한 영양성분입니다.비타민B6의 섭취량은 혈중 호모시스테인 수준을 유지하는데 필요합니다.뼈를 형성하는 칼슘은 신경과 근육 기능 유지와 정상적인 혈액 응고에 필요하며 골다공증 발생 위험 감소에 도움을 줍니다.에너지 이용에 필요하고신경과 근육 기능 유지에 필요뼈와 치아의 구성요소인 마그네슘은 세포막을 안정시키고 신경의 자극을 전달하며 지방, 단백질, 핵산의 합성에 관여합니다.칼슘을 도와뼈의 형성과 유지에 필요몸안의 칼슘농도를 안정적으로 유지시키는 비타민D는 골다공증 발생 위험 감소에 도움을 주는 것으로 알려져 있습니다.','/na/resources/upfiles/2022052923541758533.png',to_date('22/05/22','RR/MM/DD'),'Y');
Insert into NA.PRODUCT (PRO_NO,PRO_NAME,PRO_PRICE,PRO_STOCK,PRO_EFFICACY,PRO_DESCRIPTION,PRO_IMG_PATH,PRO_ENROLL_DATE,PRO_STATUS) values (6012,'비타민 BJ',25000,200,'혈액개선','활성산소로부터 인체를 보호하고높은 혈압 감소에 도움을 줄 수 있는필리 코엔자임Q10 국제표준인증(GMP, ISO_900, ISO_22000)을 받은 인도산 코엔자임Q10 원료를 식약처 1일 섭취량 (100 mg)만큼 충분히 담았습니다. 아사이베리추출분말 등 부원료 함유아사이베리추출분말, 빌베리 추출물, 포도씨앗유 등 부원료 함유비타민B1, 판토텐산, 비오틴은 탄수화물, 단백질 또는 지방의 대사에 필요하며 에너지 생성에 필요합니다.비타민B2, 나이아신은 체내 에너지 생성에 필요합니다. 활력이 없는 현대인에게 필요한 영양성분입니다.비타민B6의 섭취량은 혈중 호모시스테인 수준을 유지하는데 필요합니다.뼈를 형성하는 칼슘은 신경과 근육 기능 유지와 정상적인 혈액 응고에 필요하며 골다공증 발생 위험 감소에 도움을 줍니다.에너지 이용에 필요하고신경과 근육 기능 유지에 필요뼈와 치아의 구성요소인 마그네슘은 세포막을 안정시키고 신경의 자극을 전달하며 지방, 단백질, 핵산의 합성에 관여합니다.칼슘을 도와뼈의 형성과 유지에 필요몸안의 칼슘농도를 안정적으로 유지시키는 비타민D는 골다공증 발생 위험 감소에 도움을 주는 것으로 알려져 있습니다.','/na/resources/upfiles/2022052923454526304.png',to_date('22/05/15','RR/MM/DD'),'Y');
Insert into NA.PRODUCT (PRO_NO,PRO_NAME,PRO_PRICE,PRO_STOCK,PRO_EFFICACY,PRO_DESCRIPTION,PRO_IMG_PATH,PRO_ENROLL_DATE,PRO_STATUS) values (6014,'루테인G',74000,300,'간기능개선','활성산소로부터 인체를 보호하고높은 혈압 감소에 도움을 줄 수 있는필리 코엔자임Q10 국제표준인증(GMP, ISO_900, ISO_22000)을 받은 인도산 코엔자임Q10 원료를 식약처 1일 섭취량 (100 mg)만큼 충분히 담았습니다. 아사이베리추출분말 등 부원료 함유아사이베리추출분말, 빌베리 추출물, 포도씨앗유 등 부원료 함유비타민B1, 판토텐산, 비오틴은 탄수화물, 단백질 또는 지방의 대사에 필요하며 에너지 생성에 필요합니다.비타민B2, 나이아신은 체내 에너지 생성에 필요합니다. 활력이 없는 현대인에게 필요한 영양성분입니다.비타민B6의 섭취량은 혈중 호모시스테인 수준을 유지하는데 필요합니다.뼈를 형성하는 칼슘은 신경과 근육 기능 유지와 정상적인 혈액 응고에 필요하며 골다공증 발생 위험 감소에 도움을 줍니다.에너지 이용에 필요하고신경과 근육 기능 유지에 필요뼈와 치아의 구성요소인 마그네슘은 세포막을 안정시키고 신경의 자극을 전달하며 지방, 단백질, 핵산의 합성에 관여합니다.칼슘을 도와뼈의 형성과 유지에 필요몸안의 칼슘농도를 안정적으로 유지시키는 비타민D는 골다공증 발생 위험 감소에 도움을 주는 것으로 알려져 있습니다.','/na/resources/upfiles/2022052923472354166.png',to_date('22/05/29','RR/MM/DD'),'Y');
Insert into NA.PRODUCT (PRO_NO,PRO_NAME,PRO_PRICE,PRO_STOCK,PRO_EFFICACY,PRO_DESCRIPTION,PRO_IMG_PATH,PRO_ENROLL_DATE,PRO_STATUS) values (6016,'밀크씨슬D',83000,100,'피부건강','활성산소로부터 인체를 보호하고높은 혈압 감소에 도움을 줄 수 있는필리 코엔자임Q10 국제표준인증(GMP, ISO_900, ISO_22000)을 받은 인도산 코엔자임Q10 원료를 식약처 1일 섭취량 (100 mg)만큼 충분히 담았습니다. 아사이베리추출분말 등 부원료 함유아사이베리추출분말, 빌베리 추출물, 포도씨앗유 등 부원료 함유비타민B1, 판토텐산, 비오틴은 탄수화물, 단백질 또는 지방의 대사에 필요하며 에너지 생성에 필요합니다.비타민B2, 나이아신은 체내 에너지 생성에 필요합니다. 활력이 없는 현대인에게 필요한 영양성분입니다.비타민B6의 섭취량은 혈중 호모시스테인 수준을 유지하는데 필요합니다.뼈를 형성하는 칼슘은 신경과 근육 기능 유지와 정상적인 혈액 응고에 필요하며 골다공증 발생 위험 감소에 도움을 줍니다.에너지 이용에 필요하고신경과 근육 기능 유지에 필요뼈와 치아의 구성요소인 마그네슘은 세포막을 안정시키고 신경의 자극을 전달하며 지방, 단백질, 핵산의 합성에 관여합니다.칼슘을 도와뼈의 형성과 유지에 필요몸안의 칼슘농도를 안정적으로 유지시키는 비타민D는 골다공증 발생 위험 감소에 도움을 주는 것으로 알려져 있습니다.','/na/resources/upfiles/2022052923491291683.png',to_date('22/05/02','RR/MM/DD'),'Y');
Insert into NA.PRODUCT (PRO_NO,PRO_NAME,PRO_PRICE,PRO_STOCK,PRO_EFFICACY,PRO_DESCRIPTION,PRO_IMG_PATH,PRO_ENROLL_DATE,PRO_STATUS) values (6019,'루테인Z',12000,200,'피부건강','활성산소로부터 인체를 보호하고높은 혈압 감소에 도움을 줄 수 있는필리 코엔자임Q10 국제표준인증(GMP, ISO_900, ISO_22000)을 받은 인도산 코엔자임Q10 원료를 식약처 1일 섭취량 (100 mg)만큼 충분히 담았습니다. 아사이베리추출분말 등 부원료 함유아사이베리추출분말, 빌베리 추출물, 포도씨앗유 등 부원료 함유비타민B1, 판토텐산, 비오틴은 탄수화물, 단백질 또는 지방의 대사에 필요하며 에너지 생성에 필요합니다.비타민B2, 나이아신은 체내 에너지 생성에 필요합니다. 활력이 없는 현대인에게 필요한 영양성분입니다.비타민B6의 섭취량은 혈중 호모시스테인 수준을 유지하는데 필요합니다.뼈를 형성하는 칼슘은 신경과 근육 기능 유지와 정상적인 혈액 응고에 필요하며 골다공증 발생 위험 감소에 도움을 줍니다.에너지 이용에 필요하고신경과 근육 기능 유지에 필요뼈와 치아의 구성요소인 마그네슘은 세포막을 안정시키고 신경의 자극을 전달하며 지방, 단백질, 핵산의 합성에 관여합니다.칼슘을 도와뼈의 형성과 유지에 필요몸안의 칼슘농도를 안정적으로 유지시키는 비타민D는 골다공증 발생 위험 감소에 도움을 주는 것으로 알려져 있습니다.','/na/resources/upfiles/2022052923511777809.png',to_date('22/05/23','RR/MM/DD'),'Y');
Insert into NA.PRODUCT (PRO_NO,PRO_NAME,PRO_PRICE,PRO_STOCK,PRO_EFFICACY,PRO_DESCRIPTION,PRO_IMG_PATH,PRO_ENROLL_DATE,PRO_STATUS) values (6020,'마그네슘X',15000,200,'에너지충전','활성산소로부터 인체를 보호하고높은 혈압 감소에 도움을 줄 수 있는필리 코엔자임Q10 국제표준인증(GMP, ISO_900, ISO_22000)을 받은 인도산 코엔자임Q10 원료를 식약처 1일 섭취량 (100 mg)만큼 충분히 담았습니다. 아사이베리추출분말 등 부원료 함유아사이베리추출분말, 빌베리 추출물, 포도씨앗유 등 부원료 함유비타민B1, 판토텐산, 비오틴은 탄수화물, 단백질 또는 지방의 대사에 필요하며 에너지 생성에 필요합니다.비타민B2, 나이아신은 체내 에너지 생성에 필요합니다. 활력이 없는 현대인에게 필요한 영양성분입니다.비타민B6의 섭취량은 혈중 호모시스테인 수준을 유지하는데 필요합니다.뼈를 형성하는 칼슘은 신경과 근육 기능 유지와 정상적인 혈액 응고에 필요하며 골다공증 발생 위험 감소에 도움을 줍니다.에너지 이용에 필요하고신경과 근육 기능 유지에 필요뼈와 치아의 구성요소인 마그네슘은 세포막을 안정시키고 신경의 자극을 전달하며 지방, 단백질, 핵산의 합성에 관여합니다.칼슘을 도와뼈의 형성과 유지에 필요몸안의 칼슘농도를 안정적으로 유지시키는 비타민D는 골다공증 발생 위험 감소에 도움을 주는 것으로 알려져 있습니다.','/na/resources/upfiles/2022052923520468949.png',to_date('22/05/12','RR/MM/DD'),'Y');
Insert into NA.PRODUCT (PRO_NO,PRO_NAME,PRO_PRICE,PRO_STOCK,PRO_EFFICACY,PRO_DESCRIPTION,PRO_IMG_PATH,PRO_ENROLL_DATE,PRO_STATUS) values (6023,'오메가V',42000,200,'시력개선','활성산소로부터 인체를 보호하고높은 혈압 감소에 도움을 줄 수 있는필리 코엔자임Q10 국제표준인증(GMP, ISO_900, ISO_22000)을 받은 인도산 코엔자임Q10 원료를 식약처 1일 섭취량 (100 mg)만큼 충분히 담았습니다. 아사이베리추출분말 등 부원료 함유아사이베리추출분말, 빌베리 추출물, 포도씨앗유 등 부원료 함유비타민B1, 판토텐산, 비오틴은 탄수화물, 단백질 또는 지방의 대사에 필요하며 에너지 생성에 필요합니다.비타민B2, 나이아신은 체내 에너지 생성에 필요합니다. 활력이 없는 현대인에게 필요한 영양성분입니다.비타민B6의 섭취량은 혈중 호모시스테인 수준을 유지하는데 필요합니다.뼈를 형성하는 칼슘은 신경과 근육 기능 유지와 정상적인 혈액 응고에 필요하며 골다공증 발생 위험 감소에 도움을 줍니다.에너지 이용에 필요하고신경과 근육 기능 유지에 필요뼈와 치아의 구성요소인 마그네슘은 세포막을 안정시키고 신경의 자극을 전달하며 지방, 단백질, 핵산의 합성에 관여합니다.칼슘을 도와뼈의 형성과 유지에 필요몸안의 칼슘농도를 안정적으로 유지시키는 비타민D는 골다공증 발생 위험 감소에 도움을 주는 것으로 알려져 있습니다.','/na/resources/upfiles/2022052923444297363.png',to_date('22/05/04','RR/MM/DD'),'Y');
Insert into NA.PRODUCT (PRO_NO,PRO_NAME,PRO_PRICE,PRO_STOCK,PRO_EFFICACY,PRO_DESCRIPTION,PRO_IMG_PATH,PRO_ENROLL_DATE,PRO_STATUS) values (6024,'옥티코사놀B',54000,200,'면역력증진','활성산소로부터 인체를 보호하고높은 혈압 감소에 도움을 줄 수 있는필리 코엔자임Q10 국제표준인증(GMP, ISO_900, ISO_22000)을 받은 인도산 코엔자임Q10 원료를 식약처 1일 섭취량 (100 mg)만큼 충분히 담았습니다. 아사이베리추출분말 등 부원료 함유아사이베리추출분말, 빌베리 추출물, 포도씨앗유 등 부원료 함유비타민B1, 판토텐산, 비오틴은 탄수화물, 단백질 또는 지방의 대사에 필요하며 에너지 생성에 필요합니다.비타민B2, 나이아신은 체내 에너지 생성에 필요합니다. 활력이 없는 현대인에게 필요한 영양성분입니다.비타민B6의 섭취량은 혈중 호모시스테인 수준을 유지하는데 필요합니다.뼈를 형성하는 칼슘은 신경과 근육 기능 유지와 정상적인 혈액 응고에 필요하며 골다공증 발생 위험 감소에 도움을 줍니다.에너지 이용에 필요하고신경과 근육 기능 유지에 필요뼈와 치아의 구성요소인 마그네슘은 세포막을 안정시키고 신경의 자극을 전달하며 지방, 단백질, 핵산의 합성에 관여합니다.칼슘을 도와뼈의 형성과 유지에 필요몸안의 칼슘농도를 안정적으로 유지시키는 비타민D는 골다공증 발생 위험 감소에 도움을 주는 것으로 알려져 있습니다.','/na/resources/upfiles/2022052923454526304.png',to_date('22/05/22','RR/MM/DD'),'Y');
Insert into NA.PRODUCT (PRO_NO,PRO_NAME,PRO_PRICE,PRO_STOCK,PRO_EFFICACY,PRO_DESCRIPTION,PRO_IMG_PATH,PRO_ENROLL_DATE,PRO_STATUS) values (6026,'코엔자임 Q10M',74000,300,'간기능개선','활성산소로부터 인체를 보호하고높은 혈압 감소에 도움을 줄 수 있는필리 코엔자임Q10 국제표준인증(GMP, ISO_900, ISO_22000)을 받은 인도산 코엔자임Q10 원료를 식약처 1일 섭취량 (100 mg)만큼 충분히 담았습니다. 아사이베리추출분말 등 부원료 함유아사이베리추출분말, 빌베리 추출물, 포도씨앗유 등 부원료 함유비타민B1, 판토텐산, 비오틴은 탄수화물, 단백질 또는 지방의 대사에 필요하며 에너지 생성에 필요합니다.비타민B2, 나이아신은 체내 에너지 생성에 필요합니다. 활력이 없는 현대인에게 필요한 영양성분입니다.비타민B6의 섭취량은 혈중 호모시스테인 수준을 유지하는데 필요합니다.뼈를 형성하는 칼슘은 신경과 근육 기능 유지와 정상적인 혈액 응고에 필요하며 골다공증 발생 위험 감소에 도움을 줍니다.에너지 이용에 필요하고신경과 근육 기능 유지에 필요뼈와 치아의 구성요소인 마그네슘은 세포막을 안정시키고 신경의 자극을 전달하며 지방, 단백질, 핵산의 합성에 관여합니다.칼슘을 도와뼈의 형성과 유지에 필요몸안의 칼슘농도를 안정적으로 유지시키는 비타민D는 골다공증 발생 위험 감소에 도움을 주는 것으로 알려져 있습니다.','/na/resources/upfiles/2022052923491291683.png',to_date('22/05/15','RR/MM/DD'),'Y');
Insert into NA.PRODUCT (PRO_NO,PRO_NAME,PRO_PRICE,PRO_STOCK,PRO_EFFICACY,PRO_DESCRIPTION,PRO_IMG_PATH,PRO_ENROLL_DATE,PRO_STATUS) values (6027,'히알루론산 스피루리나QW',78000,240,'배변활동','활성산소로부터 인체를 보호하고높은 혈압 감소에 도움을 줄 수 있는필리 코엔자임Q10 국제표준인증(GMP, ISO_900, ISO_22000)을 받은 인도산 코엔자임Q10 원료를 식약처 1일 섭취량 (100 mg)만큼 충분히 담았습니다. 아사이베리추출분말 등 부원료 함유아사이베리추출분말, 빌베리 추출물, 포도씨앗유 등 부원료 함유비타민B1, 판토텐산, 비오틴은 탄수화물, 단백질 또는 지방의 대사에 필요하며 에너지 생성에 필요합니다.비타민B2, 나이아신은 체내 에너지 생성에 필요합니다. 활력이 없는 현대인에게 필요한 영양성분입니다.비타민B6의 섭취량은 혈중 호모시스테인 수준을 유지하는데 필요합니다.뼈를 형성하는 칼슘은 신경과 근육 기능 유지와 정상적인 혈액 응고에 필요하며 골다공증 발생 위험 감소에 도움을 줍니다.에너지 이용에 필요하고신경과 근육 기능 유지에 필요뼈와 치아의 구성요소인 마그네슘은 세포막을 안정시키고 신경의 자극을 전달하며 지방, 단백질, 핵산의 합성에 관여합니다.칼슘을 도와뼈의 형성과 유지에 필요몸안의 칼슘농도를 안정적으로 유지시키는 비타민D는 골다공증 발생 위험 감소에 도움을 주는 것으로 알려져 있습니다.','/na/resources/upfiles/2022052923495955697.png',to_date('22/05/29','RR/MM/DD'),'Y');
Insert into NA.PRODUCT (PRO_NO,PRO_NAME,PRO_PRICE,PRO_STOCK,PRO_EFFICACY,PRO_DESCRIPTION,PRO_IMG_PATH,PRO_ENROLL_DATE,PRO_STATUS) values (6028,'리턴업 발효효소 베이직WE',63000,100,'피부건강','활성산소로부터 인체를 보호하고높은 혈압 감소에 도움을 줄 수 있는필리 코엔자임Q10 국제표준인증(GMP, ISO_900, ISO_22000)을 받은 인도산 코엔자임Q10 원료를 식약처 1일 섭취량 (100 mg)만큼 충분히 담았습니다. 아사이베리추출분말 등 부원료 함유아사이베리추출분말, 빌베리 추출물, 포도씨앗유 등 부원료 함유비타민B1, 판토텐산, 비오틴은 탄수화물, 단백질 또는 지방의 대사에 필요하며 에너지 생성에 필요합니다.비타민B2, 나이아신은 체내 에너지 생성에 필요합니다. 활력이 없는 현대인에게 필요한 영양성분입니다.비타민B6의 섭취량은 혈중 호모시스테인 수준을 유지하는데 필요합니다.뼈를 형성하는 칼슘은 신경과 근육 기능 유지와 정상적인 혈액 응고에 필요하며 골다공증 발생 위험 감소에 도움을 줍니다.에너지 이용에 필요하고신경과 근육 기능 유지에 필요뼈와 치아의 구성요소인 마그네슘은 세포막을 안정시키고 신경의 자극을 전달하며 지방, 단백질, 핵산의 합성에 관여합니다.칼슘을 도와뼈의 형성과 유지에 필요몸안의 칼슘농도를 안정적으로 유지시키는 비타민D는 골다공증 발생 위험 감소에 도움을 주는 것으로 알려져 있습니다.','/na/resources/upfiles/2022052923504183807.png',to_date('22/05/29','RR/MM/DD'),'Y');
Insert into NA.PRODUCT (PRO_NO,PRO_NAME,PRO_PRICE,PRO_STOCK,PRO_EFFICACY,PRO_DESCRIPTION,PRO_IMG_PATH,PRO_ENROLL_DATE,PRO_STATUS) values (6029,'비타민 BER',74000,150,'면역력증진','활성산소로부터 인체를 보호하고높은 혈압 감소에 도움을 줄 수 있는필리 코엔자임Q10 국제표준인증(GMP, ISO_900, ISO_22000)을 받은 인도산 코엔자임Q10 원료를 식약처 1일 섭취량 (100 mg)만큼 충분히 담았습니다. 아사이베리추출분말 등 부원료 함유아사이베리추출분말, 빌베리 추출물, 포도씨앗유 등 부원료 함유비타민B1, 판토텐산, 비오틴은 탄수화물, 단백질 또는 지방의 대사에 필요하며 에너지 생성에 필요합니다.비타민B2, 나이아신은 체내 에너지 생성에 필요합니다. 활력이 없는 현대인에게 필요한 영양성분입니다.비타민B6의 섭취량은 혈중 호모시스테인 수준을 유지하는데 필요합니다.뼈를 형성하는 칼슘은 신경과 근육 기능 유지와 정상적인 혈액 응고에 필요하며 골다공증 발생 위험 감소에 도움을 줍니다.에너지 이용에 필요하고신경과 근육 기능 유지에 필요뼈와 치아의 구성요소인 마그네슘은 세포막을 안정시키고 신경의 자극을 전달하며 지방, 단백질, 핵산의 합성에 관여합니다.칼슘을 도와뼈의 형성과 유지에 필요몸안의 칼슘농도를 안정적으로 유지시키는 비타민D는 골다공증 발생 위험 감소에 도움을 주는 것으로 알려져 있습니다.','/na/resources/upfiles/2022052923511777809.png',to_date('22/05/24','RR/MM/DD'),'Y');
Insert into NA.PRODUCT (PRO_NO,PRO_NAME,PRO_PRICE,PRO_STOCK,PRO_EFFICACY,PRO_DESCRIPTION,PRO_IMG_PATH,PRO_ENROLL_DATE,PRO_STATUS) values (6030,'비타민 ERT',78000,150,'에너지충전','활성산소로부터 인체를 보호하고높은 혈압 감소에 도움을 줄 수 있는필리 코엔자임Q10 국제표준인증(GMP, ISO_900, ISO_22000)을 받은 인도산 코엔자임Q10 원료를 식약처 1일 섭취량 (100 mg)만큼 충분히 담았습니다. 아사이베리추출분말 등 부원료 함유아사이베리추출분말, 빌베리 추출물, 포도씨앗유 등 부원료 함유비타민B1, 판토텐산, 비오틴은 탄수화물, 단백질 또는 지방의 대사에 필요하며 에너지 생성에 필요합니다.비타민B2, 나이아신은 체내 에너지 생성에 필요합니다. 활력이 없는 현대인에게 필요한 영양성분입니다.비타민B6의 섭취량은 혈중 호모시스테인 수준을 유지하는데 필요합니다.뼈를 형성하는 칼슘은 신경과 근육 기능 유지와 정상적인 혈액 응고에 필요하며 골다공증 발생 위험 감소에 도움을 줍니다.에너지 이용에 필요하고신경과 근육 기능 유지에 필요뼈와 치아의 구성요소인 마그네슘은 세포막을 안정시키고 신경의 자극을 전달하며 지방, 단백질, 핵산의 합성에 관여합니다.칼슘을 도와뼈의 형성과 유지에 필요몸안의 칼슘농도를 안정적으로 유지시키는 비타민D는 골다공증 발생 위험 감소에 도움을 주는 것으로 알려져 있습니다.','/na/resources/upfiles/2022052923520468949.png',to_date('22/05/02','RR/MM/DD'),'Y');
Insert into NA.PRODUCT (PRO_NO,PRO_NAME,PRO_PRICE,PRO_STOCK,PRO_EFFICACY,PRO_DESCRIPTION,PRO_IMG_PATH,PRO_ENROLL_DATE,PRO_STATUS) values (6033,'밀크씨슬UI',100000,300,'에너지충전','활성산소로부터 인체를 보호하고높은 혈압 감소에 도움을 줄 수 있는필리 코엔자임Q10 국제표준인증(GMP, ISO_900, ISO_22000)을 받은 인도산 코엔자임Q10 원료를 식약처 1일 섭취량 (100 mg)만큼 충분히 담았습니다. 아사이베리추출분말 등 부원료 함유아사이베리추출분말, 빌베리 추출물, 포도씨앗유 등 부원료 함유비타민B1, 판토텐산, 비오틴은 탄수화물, 단백질 또는 지방의 대사에 필요하며 에너지 생성에 필요합니다.비타민B2, 나이아신은 체내 에너지 생성에 필요합니다. 활력이 없는 현대인에게 필요한 영양성분입니다.비타민B6의 섭취량은 혈중 호모시스테인 수준을 유지하는데 필요합니다.뼈를 형성하는 칼슘은 신경과 근육 기능 유지와 정상적인 혈액 응고에 필요하며 골다공증 발생 위험 감소에 도움을 줍니다.에너지 이용에 필요하고신경과 근육 기능 유지에 필요뼈와 치아의 구성요소인 마그네슘은 세포막을 안정시키고 신경의 자극을 전달하며 지방, 단백질, 핵산의 합성에 관여합니다.칼슘을 도와뼈의 형성과 유지에 필요몸안의 칼슘농도를 안정적으로 유지시키는 비타민D는 골다공증 발생 위험 감소에 도움을 주는 것으로 알려져 있습니다.','/na/resources/upfiles/2022052923444297363.png',to_date('22/05/23','RR/MM/DD'),'Y');
Insert into NA.PRODUCT (PRO_NO,PRO_NAME,PRO_PRICE,PRO_STOCK,PRO_EFFICACY,PRO_DESCRIPTION,PRO_IMG_PATH,PRO_ENROLL_DATE,PRO_STATUS) values (6035,'오메가OP',15000,200,'에너지충전','활성산소로부터 인체를 보호하고높은 혈압 감소에 도움을 줄 수 있는필리 코엔자임Q10 국제표준인증(GMP, ISO_900, ISO_22000)을 받은 인도산 코엔자임Q10 원료를 식약처 1일 섭취량 (100 mg)만큼 충분히 담았습니다. 아사이베리추출분말 등 부원료 함유아사이베리추출분말, 빌베리 추출물, 포도씨앗유 등 부원료 함유비타민B1, 판토텐산, 비오틴은 탄수화물, 단백질 또는 지방의 대사에 필요하며 에너지 생성에 필요합니다.비타민B2, 나이아신은 체내 에너지 생성에 필요합니다. 활력이 없는 현대인에게 필요한 영양성분입니다.비타민B6의 섭취량은 혈중 호모시스테인 수준을 유지하는데 필요합니다.뼈를 형성하는 칼슘은 신경과 근육 기능 유지와 정상적인 혈액 응고에 필요하며 골다공증 발생 위험 감소에 도움을 줍니다.에너지 이용에 필요하고신경과 근육 기능 유지에 필요뼈와 치아의 구성요소인 마그네슘은 세포막을 안정시키고 신경의 자극을 전달하며 지방, 단백질, 핵산의 합성에 관여합니다.칼슘을 도와뼈의 형성과 유지에 필요몸안의 칼슘농도를 안정적으로 유지시키는 비타민D는 골다공증 발생 위험 감소에 도움을 주는 것으로 알려져 있습니다.','/na/resources/upfiles/2022052923463873635.png',to_date('22/05/29','RR/MM/DD'),'Y');
Insert into NA.PRODUCT (PRO_NO,PRO_NAME,PRO_PRICE,PRO_STOCK,PRO_EFFICACY,PRO_DESCRIPTION,PRO_IMG_PATH,PRO_ENROLL_DATE,PRO_STATUS) values (6036,'옥티코사놀AS',25000,200,'면역력증진','활성산소로부터 인체를 보호하고높은 혈압 감소에 도움을 줄 수 있는필리 코엔자임Q10 국제표준인증(GMP, ISO_900, ISO_22000)을 받은 인도산 코엔자임Q10 원료를 식약처 1일 섭취량 (100 mg)만큼 충분히 담았습니다. 아사이베리추출분말 등 부원료 함유아사이베리추출분말, 빌베리 추출물, 포도씨앗유 등 부원료 함유비타민B1, 판토텐산, 비오틴은 탄수화물, 단백질 또는 지방의 대사에 필요하며 에너지 생성에 필요합니다.비타민B2, 나이아신은 체내 에너지 생성에 필요합니다. 활력이 없는 현대인에게 필요한 영양성분입니다.비타민B6의 섭취량은 혈중 호모시스테인 수준을 유지하는데 필요합니다.뼈를 형성하는 칼슘은 신경과 근육 기능 유지와 정상적인 혈액 응고에 필요하며 골다공증 발생 위험 감소에 도움을 줍니다.에너지 이용에 필요하고신경과 근육 기능 유지에 필요뼈와 치아의 구성요소인 마그네슘은 세포막을 안정시키고 신경의 자극을 전달하며 지방, 단백질, 핵산의 합성에 관여합니다.칼슘을 도와뼈의 형성과 유지에 필요몸안의 칼슘농도를 안정적으로 유지시키는 비타민D는 골다공증 발생 위험 감소에 도움을 주는 것으로 알려져 있습니다.','/na/resources/upfiles/2022052923472354166.png',to_date('22/05/01','RR/MM/DD'),'Y');
Insert into NA.PRODUCT (PRO_NO,PRO_NAME,PRO_PRICE,PRO_STOCK,PRO_EFFICACY,PRO_DESCRIPTION,PRO_IMG_PATH,PRO_ENROLL_DATE,PRO_STATUS) values (6038,'코엔자임 Q10SDF',42000,200,'시력개선','활성산소로부터 인체를 보호하고높은 혈압 감소에 도움을 줄 수 있는필리 코엔자임Q10 국제표준인증(GMP, ISO_900, ISO_22000)을 받은 인도산 코엔자임Q10 원료를 식약처 1일 섭취량 (100 mg)만큼 충분히 담았습니다. 아사이베리추출분말 등 부원료 함유아사이베리추출분말, 빌베리 추출물, 포도씨앗유 등 부원료 함유비타민B1, 판토텐산, 비오틴은 탄수화물, 단백질 또는 지방의 대사에 필요하며 에너지 생성에 필요합니다.비타민B2, 나이아신은 체내 에너지 생성에 필요합니다. 활력이 없는 현대인에게 필요한 영양성분입니다.비타민B6의 섭취량은 혈중 호모시스테인 수준을 유지하는데 필요합니다.뼈를 형성하는 칼슘은 신경과 근육 기능 유지와 정상적인 혈액 응고에 필요하며 골다공증 발생 위험 감소에 도움을 줍니다.에너지 이용에 필요하고신경과 근육 기능 유지에 필요뼈와 치아의 구성요소인 마그네슘은 세포막을 안정시키고 신경의 자극을 전달하며 지방, 단백질, 핵산의 합성에 관여합니다.칼슘을 도와뼈의 형성과 유지에 필요몸안의 칼슘농도를 안정적으로 유지시키는 비타민D는 골다공증 발생 위험 감소에 도움을 주는 것으로 알려져 있습니다.','/na/resources/upfiles/2022052923491291683.png',to_date('22/05/22','RR/MM/DD'),'Y');
Insert into NA.PRODUCT (PRO_NO,PRO_NAME,PRO_PRICE,PRO_STOCK,PRO_EFFICACY,PRO_DESCRIPTION,PRO_IMG_PATH,PRO_ENROLL_DATE,PRO_STATUS) values (6039,'히알루론산 스피루리나DF',54000,200,'면역력증진','활성산소로부터 인체를 보호하고높은 혈압 감소에 도움을 줄 수 있는필리 코엔자임Q10 국제표준인증(GMP, ISO_900, ISO_22000)을 받은 인도산 코엔자임Q10 원료를 식약처 1일 섭취량 (100 mg)만큼 충분히 담았습니다. 아사이베리추출분말 등 부원료 함유아사이베리추출분말, 빌베리 추출물, 포도씨앗유 등 부원료 함유비타민B1, 판토텐산, 비오틴은 탄수화물, 단백질 또는 지방의 대사에 필요하며 에너지 생성에 필요합니다.비타민B2, 나이아신은 체내 에너지 생성에 필요합니다. 활력이 없는 현대인에게 필요한 영양성분입니다.비타민B6의 섭취량은 혈중 호모시스테인 수준을 유지하는데 필요합니다.뼈를 형성하는 칼슘은 신경과 근육 기능 유지와 정상적인 혈액 응고에 필요하며 골다공증 발생 위험 감소에 도움을 줍니다.에너지 이용에 필요하고신경과 근육 기능 유지에 필요뼈와 치아의 구성요소인 마그네슘은 세포막을 안정시키고 신경의 자극을 전달하며 지방, 단백질, 핵산의 합성에 관여합니다.칼슘을 도와뼈의 형성과 유지에 필요몸안의 칼슘농도를 안정적으로 유지시키는 비타민D는 골다공증 발생 위험 감소에 도움을 주는 것으로 알려져 있습니다.','/na/resources/upfiles/2022052923495955697.png',to_date('22/05/14','RR/MM/DD'),'Y');
Insert into NA.PRODUCT (PRO_NO,PRO_NAME,PRO_PRICE,PRO_STOCK,PRO_EFFICACY,PRO_DESCRIPTION,PRO_IMG_PATH,PRO_ENROLL_DATE,PRO_STATUS) values (6040,'리턴업 발효효소 베이직FG',63000,200,'에너지충전','활성산소로부터 인체를 보호하고높은 혈압 감소에 도움을 줄 수 있는필리 코엔자임Q10 국제표준인증(GMP, ISO_900, ISO_22000)을 받은 인도산 코엔자임Q10 원료를 식약처 1일 섭취량 (100 mg)만큼 충분히 담았습니다. 아사이베리추출분말 등 부원료 함유아사이베리추출분말, 빌베리 추출물, 포도씨앗유 등 부원료 함유비타민B1, 판토텐산, 비오틴은 탄수화물, 단백질 또는 지방의 대사에 필요하며 에너지 생성에 필요합니다.비타민B2, 나이아신은 체내 에너지 생성에 필요합니다. 활력이 없는 현대인에게 필요한 영양성분입니다.비타민B6의 섭취량은 혈중 호모시스테인 수준을 유지하는데 필요합니다.뼈를 형성하는 칼슘은 신경과 근육 기능 유지와 정상적인 혈액 응고에 필요하며 골다공증 발생 위험 감소에 도움을 줍니다.에너지 이용에 필요하고신경과 근육 기능 유지에 필요뼈와 치아의 구성요소인 마그네슘은 세포막을 안정시키고 신경의 자극을 전달하며 지방, 단백질, 핵산의 합성에 관여합니다.칼슘을 도와뼈의 형성과 유지에 필요몸안의 칼슘농도를 안정적으로 유지시키는 비타민D는 골다공증 발생 위험 감소에 도움을 주는 것으로 알려져 있습니다.','/na/resources/upfiles/2022052923504183807.png',to_date('22/05/15','RR/MM/DD'),'Y');
Insert into NA.PRODUCT (PRO_NO,PRO_NAME,PRO_PRICE,PRO_STOCK,PRO_EFFICACY,PRO_DESCRIPTION,PRO_IMG_PATH,PRO_ENROLL_DATE,PRO_STATUS) values (6043,'루테인JK',54000,240,'피부건강','활성산소로부터 인체를 보호하고높은 혈압 감소에 도움을 줄 수 있는필리 코엔자임Q10 국제표준인증(GMP, ISO_900, ISO_22000)을 받은 인도산 코엔자임Q10 원료를 식약처 1일 섭취량 (100 mg)만큼 충분히 담았습니다. 아사이베리추출분말 등 부원료 함유아사이베리추출분말, 빌베리 추출물, 포도씨앗유 등 부원료 함유비타민B1, 판토텐산, 비오틴은 탄수화물, 단백질 또는 지방의 대사에 필요하며 에너지 생성에 필요합니다.비타민B2, 나이아신은 체내 에너지 생성에 필요합니다. 활력이 없는 현대인에게 필요한 영양성분입니다.비타민B6의 섭취량은 혈중 호모시스테인 수준을 유지하는데 필요합니다.뼈를 형성하는 칼슘은 신경과 근육 기능 유지와 정상적인 혈액 응고에 필요하며 골다공증 발생 위험 감소에 도움을 줍니다.에너지 이용에 필요하고신경과 근육 기능 유지에 필요뼈와 치아의 구성요소인 마그네슘은 세포막을 안정시키고 신경의 자극을 전달하며 지방, 단백질, 핵산의 합성에 관여합니다.칼슘을 도와뼈의 형성과 유지에 필요몸안의 칼슘농도를 안정적으로 유지시키는 비타민D는 골다공증 발생 위험 감소에 도움을 주는 것으로 알려져 있습니다.','/na/resources/upfiles/2022052923525277862.png',to_date('22/05/24','RR/MM/DD'),'Y');
Insert into NA.PRODUCT (PRO_NO,PRO_NAME,PRO_PRICE,PRO_STOCK,PRO_EFFICACY,PRO_DESCRIPTION,PRO_IMG_PATH,PRO_ENROLL_DATE,PRO_STATUS) values (6044,'마그네슘KL',63000,100,'면역력증진','활성산소로부터 인체를 보호하고높은 혈압 감소에 도움을 줄 수 있는필리 코엔자임Q10 국제표준인증(GMP, ISO_900, ISO_22000)을 받은 인도산 코엔자임Q10 원료를 식약처 1일 섭취량 (100 mg)만큼 충분히 담았습니다. 아사이베리추출분말 등 부원료 함유아사이베리추출분말, 빌베리 추출물, 포도씨앗유 등 부원료 함유비타민B1, 판토텐산, 비오틴은 탄수화물, 단백질 또는 지방의 대사에 필요하며 에너지 생성에 필요합니다.비타민B2, 나이아신은 체내 에너지 생성에 필요합니다. 활력이 없는 현대인에게 필요한 영양성분입니다.비타민B6의 섭취량은 혈중 호모시스테인 수준을 유지하는데 필요합니다.뼈를 형성하는 칼슘은 신경과 근육 기능 유지와 정상적인 혈액 응고에 필요하며 골다공증 발생 위험 감소에 도움을 줍니다.에너지 이용에 필요하고신경과 근육 기능 유지에 필요뼈와 치아의 구성요소인 마그네슘은 세포막을 안정시키고 신경의 자극을 전달하며 지방, 단백질, 핵산의 합성에 관여합니다.칼슘을 도와뼈의 형성과 유지에 필요몸안의 칼슘농도를 안정적으로 유지시키는 비타민D는 골다공증 발생 위험 감소에 도움을 주는 것으로 알려져 있습니다.','/na/resources/upfiles/2022052923541758533.png',to_date('22/05/02','RR/MM/DD'),'Y');
Insert into NA.PRODUCT (PRO_NO,PRO_NAME,PRO_PRICE,PRO_STOCK,PRO_EFFICACY,PRO_DESCRIPTION,PRO_IMG_PATH,PRO_ENROLL_DATE,PRO_STATUS) values (6045,'밀크씨슬L',74000,150,'에너지충전','활성산소로부터 인체를 보호하고높은 혈압 감소에 도움을 줄 수 있는필리 코엔자임Q10 국제표준인증(GMP, ISO_900, ISO_22000)을 받은 인도산 코엔자임Q10 원료를 식약처 1일 섭취량 (100 mg)만큼 충분히 담았습니다. 아사이베리추출분말 등 부원료 함유아사이베리추출분말, 빌베리 추출물, 포도씨앗유 등 부원료 함유비타민B1, 판토텐산, 비오틴은 탄수화물, 단백질 또는 지방의 대사에 필요하며 에너지 생성에 필요합니다.비타민B2, 나이아신은 체내 에너지 생성에 필요합니다. 활력이 없는 현대인에게 필요한 영양성분입니다.비타민B6의 섭취량은 혈중 호모시스테인 수준을 유지하는데 필요합니다.뼈를 형성하는 칼슘은 신경과 근육 기능 유지와 정상적인 혈액 응고에 필요하며 골다공증 발생 위험 감소에 도움을 줍니다.에너지 이용에 필요하고신경과 근육 기능 유지에 필요뼈와 치아의 구성요소인 마그네슘은 세포막을 안정시키고 신경의 자극을 전달하며 지방, 단백질, 핵산의 합성에 관여합니다.칼슘을 도와뼈의 형성과 유지에 필요몸안의 칼슘농도를 안정적으로 유지시키는 비타민D는 골다공증 발생 위험 감소에 도움을 주는 것으로 알려져 있습니다.','/na/resources/upfiles/2022052923444297363.png',to_date('22/05/01','RR/MM/DD'),'Y');
Insert into NA.PRODUCT (PRO_NO,PRO_NAME,PRO_PRICE,PRO_STOCK,PRO_EFFICACY,PRO_DESCRIPTION,PRO_IMG_PATH,PRO_ENROLL_DATE,PRO_STATUS) values (6046,'비타민 CZX',78000,150,'피부건강','활성산소로부터 인체를 보호하고높은 혈압 감소에 도움을 줄 수 있는필리 코엔자임Q10 국제표준인증(GMP, ISO_900, ISO_22000)을 받은 인도산 코엔자임Q10 원료를 식약처 1일 섭취량 (100 mg)만큼 충분히 담았습니다. 아사이베리추출분말 등 부원료 함유아사이베리추출분말, 빌베리 추출물, 포도씨앗유 등 부원료 함유비타민B1, 판토텐산, 비오틴은 탄수화물, 단백질 또는 지방의 대사에 필요하며 에너지 생성에 필요합니다.비타민B2, 나이아신은 체내 에너지 생성에 필요합니다. 활력이 없는 현대인에게 필요한 영양성분입니다.비타민B6의 섭취량은 혈중 호모시스테인 수준을 유지하는데 필요합니다.뼈를 형성하는 칼슘은 신경과 근육 기능 유지와 정상적인 혈액 응고에 필요하며 골다공증 발생 위험 감소에 도움을 줍니다.에너지 이용에 필요하고신경과 근육 기능 유지에 필요뼈와 치아의 구성요소인 마그네슘은 세포막을 안정시키고 신경의 자극을 전달하며 지방, 단백질, 핵산의 합성에 관여합니다.칼슘을 도와뼈의 형성과 유지에 필요몸안의 칼슘농도를 안정적으로 유지시키는 비타민D는 골다공증 발생 위험 감소에 도움을 주는 것으로 알려져 있습니다.','/na/resources/upfiles/2022052923454526304.png',to_date('22/05/05','RR/MM/DD'),'Y');
Insert into NA.PRODUCT (PRO_NO,PRO_NAME,PRO_PRICE,PRO_STOCK,PRO_EFFICACY,PRO_DESCRIPTION,PRO_IMG_PATH,PRO_ENROLL_DATE,PRO_STATUS) values (6047,'비타민 EXC',83000,200,'에너지충전','활성산소로부터 인체를 보호하고높은 혈압 감소에 도움을 줄 수 있는필리 코엔자임Q10 국제표준인증(GMP, ISO_900, ISO_22000)을 받은 인도산 코엔자임Q10 원료를 식약처 1일 섭취량 (100 mg)만큼 충분히 담았습니다. 아사이베리추출분말 등 부원료 함유아사이베리추출분말, 빌베리 추출물, 포도씨앗유 등 부원료 함유비타민B1, 판토텐산, 비오틴은 탄수화물, 단백질 또는 지방의 대사에 필요하며 에너지 생성에 필요합니다.비타민B2, 나이아신은 체내 에너지 생성에 필요합니다. 활력이 없는 현대인에게 필요한 영양성분입니다.비타민B6의 섭취량은 혈중 호모시스테인 수준을 유지하는데 필요합니다.뼈를 형성하는 칼슘은 신경과 근육 기능 유지와 정상적인 혈액 응고에 필요하며 골다공증 발생 위험 감소에 도움을 줍니다.에너지 이용에 필요하고신경과 근육 기능 유지에 필요뼈와 치아의 구성요소인 마그네슘은 세포막을 안정시키고 신경의 자극을 전달하며 지방, 단백질, 핵산의 합성에 관여합니다.칼슘을 도와뼈의 형성과 유지에 필요몸안의 칼슘농도를 안정적으로 유지시키는 비타민D는 골다공증 발생 위험 감소에 도움을 주는 것으로 알려져 있습니다.','/na/resources/upfiles/2022052923463873635.png',to_date('22/05/23','RR/MM/DD'),'Y');
Insert into NA.PRODUCT (PRO_NO,PRO_NAME,PRO_PRICE,PRO_STOCK,PRO_EFFICACY,PRO_DESCRIPTION,PRO_IMG_PATH,PRO_ENROLL_DATE,PRO_STATUS) values (6048,'루테인CV',91000,200,'면역력증진','활성산소로부터 인체를 보호하고높은 혈압 감소에 도움을 줄 수 있는필리 코엔자임Q10 국제표준인증(GMP, ISO_900, ISO_22000)을 받은 인도산 코엔자임Q10 원료를 식약처 1일 섭취량 (100 mg)만큼 충분히 담았습니다. 아사이베리추출분말 등 부원료 함유아사이베리추출분말, 빌베리 추출물, 포도씨앗유 등 부원료 함유비타민B1, 판토텐산, 비오틴은 탄수화물, 단백질 또는 지방의 대사에 필요하며 에너지 생성에 필요합니다.비타민B2, 나이아신은 체내 에너지 생성에 필요합니다. 활력이 없는 현대인에게 필요한 영양성분입니다.비타민B6의 섭취량은 혈중 호모시스테인 수준을 유지하는데 필요합니다.뼈를 형성하는 칼슘은 신경과 근육 기능 유지와 정상적인 혈액 응고에 필요하며 골다공증 발생 위험 감소에 도움을 줍니다.에너지 이용에 필요하고신경과 근육 기능 유지에 필요뼈와 치아의 구성요소인 마그네슘은 세포막을 안정시키고 신경의 자극을 전달하며 지방, 단백질, 핵산의 합성에 관여합니다.칼슘을 도와뼈의 형성과 유지에 필요몸안의 칼슘농도를 안정적으로 유지시키는 비타민D는 골다공증 발생 위험 감소에 도움을 주는 것으로 알려져 있습니다.','/na/resources/upfiles/2022052923472354166.png',to_date('22/05/12','RR/MM/DD'),'Y');
Insert into NA.PRODUCT (PRO_NO,PRO_NAME,PRO_PRICE,PRO_STOCK,PRO_EFFICACY,PRO_DESCRIPTION,PRO_IMG_PATH,PRO_ENROLL_DATE,PRO_STATUS) values (6049,'마그네슘VB',100000,300,'혈액개선','활성산소로부터 인체를 보호하고높은 혈압 감소에 도움을 줄 수 있는필리 코엔자임Q10 국제표준인증(GMP, ISO_900, ISO_22000)을 받은 인도산 코엔자임Q10 원료를 식약처 1일 섭취량 (100 mg)만큼 충분히 담았습니다. 아사이베리추출분말 등 부원료 함유아사이베리추출분말, 빌베리 추출물, 포도씨앗유 등 부원료 함유비타민B1, 판토텐산, 비오틴은 탄수화물, 단백질 또는 지방의 대사에 필요하며 에너지 생성에 필요합니다.비타민B2, 나이아신은 체내 에너지 생성에 필요합니다. 활력이 없는 현대인에게 필요한 영양성분입니다.비타민B6의 섭취량은 혈중 호모시스테인 수준을 유지하는데 필요합니다.뼈를 형성하는 칼슘은 신경과 근육 기능 유지와 정상적인 혈액 응고에 필요하며 골다공증 발생 위험 감소에 도움을 줍니다.에너지 이용에 필요하고신경과 근육 기능 유지에 필요뼈와 치아의 구성요소인 마그네슘은 세포막을 안정시키고 신경의 자극을 전달하며 지방, 단백질, 핵산의 합성에 관여합니다.칼슘을 도와뼈의 형성과 유지에 필요몸안의 칼슘농도를 안정적으로 유지시키는 비타민D는 골다공증 발생 위험 감소에 도움을 주는 것으로 알려져 있습니다.','/na/resources/upfiles/2022052923481025901.png',to_date('22/05/29','RR/MM/DD'),'Y');
Insert into NA.PRODUCT (PRO_NO,PRO_NAME,PRO_PRICE,PRO_STOCK,PRO_EFFICACY,PRO_DESCRIPTION,PRO_IMG_PATH,PRO_ENROLL_DATE,PRO_STATUS) values (6052,'오메가M3',25000,200,'배변활동','활성산소로부터 인체를 보호하고높은 혈압 감소에 도움을 줄 수 있는필리 코엔자임Q10 국제표준인증(GMP, ISO_900, ISO_22000)을 받은 인도산 코엔자임Q10 원료를 식약처 1일 섭취량 (100 mg)만큼 충분히 담았습니다. 아사이베리추출분말 등 부원료 함유아사이베리추출분말, 빌베리 추출물, 포도씨앗유 등 부원료 함유비타민B1, 판토텐산, 비오틴은 탄수화물, 단백질 또는 지방의 대사에 필요하며 에너지 생성에 필요합니다.비타민B2, 나이아신은 체내 에너지 생성에 필요합니다. 활력이 없는 현대인에게 필요한 영양성분입니다.비타민B6의 섭취량은 혈중 호모시스테인 수준을 유지하는데 필요합니다.뼈를 형성하는 칼슘은 신경과 근육 기능 유지와 정상적인 혈액 응고에 필요하며 골다공증 발생 위험 감소에 도움을 줍니다.에너지 이용에 필요하고신경과 근육 기능 유지에 필요뼈와 치아의 구성요소인 마그네슘은 세포막을 안정시키고 신경의 자극을 전달하며 지방, 단백질, 핵산의 합성에 관여합니다.칼슘을 도와뼈의 형성과 유지에 필요몸안의 칼슘농도를 안정적으로 유지시키는 비타민D는 골다공증 발생 위험 감소에 도움을 주는 것으로 알려져 있습니다.','/na/resources/upfiles/2022052923504183807.png',to_date('22/05/22','RR/MM/DD'),'Y');
Insert into NA.PRODUCT (PRO_NO,PRO_NAME,PRO_PRICE,PRO_STOCK,PRO_EFFICACY,PRO_DESCRIPTION,PRO_IMG_PATH,PRO_ENROLL_DATE,PRO_STATUS) values (6053,'옥티코사놀12',63000,200,'피부건강','활성산소로부터 인체를 보호하고높은 혈압 감소에 도움을 줄 수 있는필리 코엔자임Q10 국제표준인증(GMP, ISO_900, ISO_22000)을 받은 인도산 코엔자임Q10 원료를 식약처 1일 섭취량 (100 mg)만큼 충분히 담았습니다. 아사이베리추출분말 등 부원료 함유아사이베리추출분말, 빌베리 추출물, 포도씨앗유 등 부원료 함유비타민B1, 판토텐산, 비오틴은 탄수화물, 단백질 또는 지방의 대사에 필요하며 에너지 생성에 필요합니다.비타민B2, 나이아신은 체내 에너지 생성에 필요합니다. 활력이 없는 현대인에게 필요한 영양성분입니다.비타민B6의 섭취량은 혈중 호모시스테인 수준을 유지하는데 필요합니다.뼈를 형성하는 칼슘은 신경과 근육 기능 유지와 정상적인 혈액 응고에 필요하며 골다공증 발생 위험 감소에 도움을 줍니다.에너지 이용에 필요하고신경과 근육 기능 유지에 필요뼈와 치아의 구성요소인 마그네슘은 세포막을 안정시키고 신경의 자극을 전달하며 지방, 단백질, 핵산의 합성에 관여합니다.칼슘을 도와뼈의 형성과 유지에 필요몸안의 칼슘농도를 안정적으로 유지시키는 비타민D는 골다공증 발생 위험 감소에 도움을 주는 것으로 알려져 있습니다.','/na/resources/upfiles/2022052923511777809.png',to_date('22/05/14','RR/MM/DD'),'Y');
Insert into NA.PRODUCT (PRO_NO,PRO_NAME,PRO_PRICE,PRO_STOCK,PRO_EFFICACY,PRO_DESCRIPTION,PRO_IMG_PATH,PRO_ENROLL_DATE,PRO_STATUS) values (6055,'코엔자임 Q104',78000,240,'에너지충전','활성산소로부터 인체를 보호하고높은 혈압 감소에 도움을 줄 수 있는필리 코엔자임Q10 국제표준인증(GMP, ISO_900, ISO_22000)을 받은 인도산 코엔자임Q10 원료를 식약처 1일 섭취량 (100 mg)만큼 충분히 담았습니다. 아사이베리추출분말 등 부원료 함유아사이베리추출분말, 빌베리 추출물, 포도씨앗유 등 부원료 함유비타민B1, 판토텐산, 비오틴은 탄수화물, 단백질 또는 지방의 대사에 필요하며 에너지 생성에 필요합니다.비타민B2, 나이아신은 체내 에너지 생성에 필요합니다. 활력이 없는 현대인에게 필요한 영양성분입니다.비타민B6의 섭취량은 혈중 호모시스테인 수준을 유지하는데 필요합니다.뼈를 형성하는 칼슘은 신경과 근육 기능 유지와 정상적인 혈액 응고에 필요하며 골다공증 발생 위험 감소에 도움을 줍니다.에너지 이용에 필요하고신경과 근육 기능 유지에 필요뼈와 치아의 구성요소인 마그네슘은 세포막을 안정시키고 신경의 자극을 전달하며 지방, 단백질, 핵산의 합성에 관여합니다.칼슘을 도와뼈의 형성과 유지에 필요몸안의 칼슘농도를 안정적으로 유지시키는 비타민D는 골다공증 발생 위험 감소에 도움을 주는 것으로 알려져 있습니다.','/na/resources/upfiles/2022052923481025901.png',to_date('22/05/29','RR/MM/DD'),'Y');
Insert into NA.PRODUCT (PRO_NO,PRO_NAME,PRO_PRICE,PRO_STOCK,PRO_EFFICACY,PRO_DESCRIPTION,PRO_IMG_PATH,PRO_ENROLL_DATE,PRO_STATUS) values (6056,'히알루론산 스피루리나5',83000,100,'피부건강','활성산소로부터 인체를 보호하고높은 혈압 감소에 도움을 줄 수 있는필리 코엔자임Q10 국제표준인증(GMP, ISO_900, ISO_22000)을 받은 인도산 코엔자임Q10 원료를 식약처 1일 섭취량 (100 mg)만큼 충분히 담았습니다. 아사이베리추출분말 등 부원료 함유아사이베리추출분말, 빌베리 추출물, 포도씨앗유 등 부원료 함유비타민B1, 판토텐산, 비오틴은 탄수화물, 단백질 또는 지방의 대사에 필요하며 에너지 생성에 필요합니다.비타민B2, 나이아신은 체내 에너지 생성에 필요합니다. 활력이 없는 현대인에게 필요한 영양성분입니다.비타민B6의 섭취량은 혈중 호모시스테인 수준을 유지하는데 필요합니다.뼈를 형성하는 칼슘은 신경과 근육 기능 유지와 정상적인 혈액 응고에 필요하며 골다공증 발생 위험 감소에 도움을 줍니다.에너지 이용에 필요하고신경과 근육 기능 유지에 필요뼈와 치아의 구성요소인 마그네슘은 세포막을 안정시키고 신경의 자극을 전달하며 지방, 단백질, 핵산의 합성에 관여합니다.칼슘을 도와뼈의 형성과 유지에 필요몸안의 칼슘농도를 안정적으로 유지시키는 비타민D는 골다공증 발생 위험 감소에 도움을 주는 것으로 알려져 있습니다.','/na/resources/upfiles/2022052923491291683.png',to_date('22/05/29','RR/MM/DD'),'Y');
Insert into NA.PRODUCT (PRO_NO,PRO_NAME,PRO_PRICE,PRO_STOCK,PRO_EFFICACY,PRO_DESCRIPTION,PRO_IMG_PATH,PRO_ENROLL_DATE,PRO_STATUS) values (6058,'비타민 7',100000,150,'면역력증진','활성산소로부터 인체를 보호하고높은 혈압 감소에 도움을 줄 수 있는필리 코엔자임Q10 국제표준인증(GMP, ISO_900, ISO_22000)을 받은 인도산 코엔자임Q10 원료를 식약처 1일 섭취량 (100 mg)만큼 충분히 담았습니다. 아사이베리추출분말 등 부원료 함유아사이베리추출분말, 빌베리 추출물, 포도씨앗유 등 부원료 함유비타민B1, 판토텐산, 비오틴은 탄수화물, 단백질 또는 지방의 대사에 필요하며 에너지 생성에 필요합니다.비타민B2, 나이아신은 체내 에너지 생성에 필요합니다. 활력이 없는 현대인에게 필요한 영양성분입니다.비타민B6의 섭취량은 혈중 호모시스테인 수준을 유지하는데 필요합니다.뼈를 형성하는 칼슘은 신경과 근육 기능 유지와 정상적인 혈액 응고에 필요하며 골다공증 발생 위험 감소에 도움을 줍니다.에너지 이용에 필요하고신경과 근육 기능 유지에 필요뼈와 치아의 구성요소인 마그네슘은 세포막을 안정시키고 신경의 자극을 전달하며 지방, 단백질, 핵산의 합성에 관여합니다.칼슘을 도와뼈의 형성과 유지에 필요몸안의 칼슘농도를 안정적으로 유지시키는 비타민D는 골다공증 발생 위험 감소에 도움을 주는 것으로 알려져 있습니다.','/na/resources/upfiles/2022052923504183807.png',to_date('22/05/02','RR/MM/DD'),'Y');
Insert into NA.PRODUCT (PRO_NO,PRO_NAME,PRO_PRICE,PRO_STOCK,PRO_EFFICACY,PRO_DESCRIPTION,PRO_IMG_PATH,PRO_ENROLL_DATE,PRO_STATUS) values (6059,'비타민 E8',12000,200,'혈액개선','활성산소로부터 인체를 보호하고높은 혈압 감소에 도움을 줄 수 있는필리 코엔자임Q10 국제표준인증(GMP, ISO_900, ISO_22000)을 받은 인도산 코엔자임Q10 원료를 식약처 1일 섭취량 (100 mg)만큼 충분히 담았습니다. 아사이베리추출분말 등 부원료 함유아사이베리추출분말, 빌베리 추출물, 포도씨앗유 등 부원료 함유비타민B1, 판토텐산, 비오틴은 탄수화물, 단백질 또는 지방의 대사에 필요하며 에너지 생성에 필요합니다.비타민B2, 나이아신은 체내 에너지 생성에 필요합니다. 활력이 없는 현대인에게 필요한 영양성분입니다.비타민B6의 섭취량은 혈중 호모시스테인 수준을 유지하는데 필요합니다.뼈를 형성하는 칼슘은 신경과 근육 기능 유지와 정상적인 혈액 응고에 필요하며 골다공증 발생 위험 감소에 도움을 줍니다.에너지 이용에 필요하고신경과 근육 기능 유지에 필요뼈와 치아의 구성요소인 마그네슘은 세포막을 안정시키고 신경의 자극을 전달하며 지방, 단백질, 핵산의 합성에 관여합니다.칼슘을 도와뼈의 형성과 유지에 필요몸안의 칼슘농도를 안정적으로 유지시키는 비타민D는 골다공증 발생 위험 감소에 도움을 주는 것으로 알려져 있습니다.','/na/resources/upfiles/2022052923511777809.png',to_date('22/05/01','RR/MM/DD'),'Y');
Insert into NA.PRODUCT (PRO_NO,PRO_NAME,PRO_PRICE,PRO_STOCK,PRO_EFFICACY,PRO_DESCRIPTION,PRO_IMG_PATH,PRO_ENROLL_DATE,PRO_STATUS) values (6061,'마그네슘0',25000,300,'면역력증진','활성산소로부터 인체를 보호하고높은 혈압 감소에 도움을 줄 수 있는필리 코엔자임Q10 국제표준인증(GMP, ISO_900, ISO_22000)을 받은 인도산 코엔자임Q10 원료를 식약처 1일 섭취량 (100 mg)만큼 충분히 담았습니다. 아사이베리추출분말 등 부원료 함유아사이베리추출분말, 빌베리 추출물, 포도씨앗유 등 부원료 함유비타민B1, 판토텐산, 비오틴은 탄수화물, 단백질 또는 지방의 대사에 필요하며 에너지 생성에 필요합니다.비타민B2, 나이아신은 체내 에너지 생성에 필요합니다. 활력이 없는 현대인에게 필요한 영양성분입니다.비타민B6의 섭취량은 혈중 호모시스테인 수준을 유지하는데 필요합니다.뼈를 형성하는 칼슘은 신경과 근육 기능 유지와 정상적인 혈액 응고에 필요하며 골다공증 발생 위험 감소에 도움을 줍니다.에너지 이용에 필요하고신경과 근육 기능 유지에 필요뼈와 치아의 구성요소인 마그네슘은 세포막을 안정시키고 신경의 자극을 전달하며 지방, 단백질, 핵산의 합성에 관여합니다.칼슘을 도와뼈의 형성과 유지에 필요몸안의 칼슘농도를 안정적으로 유지시키는 비타민D는 골다공증 발생 위험 감소에 도움을 주는 것으로 알려져 있습니다.','/na/resources/upfiles/2022052923525277862.png',to_date('22/05/23','RR/MM/DD'),'Y');
Insert into NA.PRODUCT (PRO_NO,PRO_NAME,PRO_PRICE,PRO_STOCK,PRO_EFFICACY,PRO_DESCRIPTION,PRO_IMG_PATH,PRO_ENROLL_DATE,PRO_STATUS) values (6069,'리턴업 발효효소 베이직89',74000,150,'시력개선','활성산소로부터 인체를 보호하고높은 혈압 감소에 도움을 줄 수 있는필리 코엔자임Q10 국제표준인증(GMP, ISO_900, ISO_22000)을 받은 인도산 코엔자임Q10 원료를 식약처 1일 섭취량 (100 mg)만큼 충분히 담았습니다. 아사이베리추출분말 등 부원료 함유아사이베리추출분말, 빌베리 추출물, 포도씨앗유 등 부원료 함유비타민B1, 판토텐산, 비오틴은 탄수화물, 단백질 또는 지방의 대사에 필요하며 에너지 생성에 필요합니다.비타민B2, 나이아신은 체내 에너지 생성에 필요합니다. 활력이 없는 현대인에게 필요한 영양성분입니다.비타민B6의 섭취량은 혈중 호모시스테인 수준을 유지하는데 필요합니다.뼈를 형성하는 칼슘은 신경과 근육 기능 유지와 정상적인 혈액 응고에 필요하며 골다공증 발생 위험 감소에 도움을 줍니다.에너지 이용에 필요하고신경과 근육 기능 유지에 필요뼈와 치아의 구성요소인 마그네슘은 세포막을 안정시키고 신경의 자극을 전달하며 지방, 단백질, 핵산의 합성에 관여합니다.칼슘을 도와뼈의 형성과 유지에 필요몸안의 칼슘농도를 안정적으로 유지시키는 비타민D는 골다공증 발생 위험 감소에 도움을 주는 것으로 알려져 있습니다.','/na/resources/upfiles/2022052923495955697.png',to_date('22/05/22','RR/MM/DD'),'Y');
Insert into NA.PRODUCT (PRO_NO,PRO_NAME,PRO_PRICE,PRO_STOCK,PRO_EFFICACY,PRO_DESCRIPTION,PRO_IMG_PATH,PRO_ENROLL_DATE,PRO_STATUS) values (6070,'비타민 B90',78000,300,'면역력증진','활성산소로부터 인체를 보호하고높은 혈압 감소에 도움을 줄 수 있는필리 코엔자임Q10 국제표준인증(GMP, ISO_900, ISO_22000)을 받은 인도산 코엔자임Q10 원료를 식약처 1일 섭취량 (100 mg)만큼 충분히 담았습니다. 아사이베리추출분말 등 부원료 함유아사이베리추출분말, 빌베리 추출물, 포도씨앗유 등 부원료 함유비타민B1, 판토텐산, 비오틴은 탄수화물, 단백질 또는 지방의 대사에 필요하며 에너지 생성에 필요합니다.비타민B2, 나이아신은 체내 에너지 생성에 필요합니다. 활력이 없는 현대인에게 필요한 영양성분입니다.비타민B6의 섭취량은 혈중 호모시스테인 수준을 유지하는데 필요합니다.뼈를 형성하는 칼슘은 신경과 근육 기능 유지와 정상적인 혈액 응고에 필요하며 골다공증 발생 위험 감소에 도움을 줍니다.에너지 이용에 필요하고신경과 근육 기능 유지에 필요뼈와 치아의 구성요소인 마그네슘은 세포막을 안정시키고 신경의 자극을 전달하며 지방, 단백질, 핵산의 합성에 관여합니다.칼슘을 도와뼈의 형성과 유지에 필요몸안의 칼슘농도를 안정적으로 유지시키는 비타민D는 골다공증 발생 위험 감소에 도움을 주는 것으로 알려져 있습니다.','/na/resources/upfiles/2022052923504183807.png',to_date('22/05/14','RR/MM/DD'),'Y');
Insert into NA.PRODUCT (PRO_NO,PRO_NAME,PRO_PRICE,PRO_STOCK,PRO_EFFICACY,PRO_DESCRIPTION,PRO_IMG_PATH,PRO_ENROLL_DATE,PRO_STATUS) values (6071,'비타민 EAQ',83000,200,'에너지충전','활성산소로부터 인체를 보호하고높은 혈압 감소에 도움을 줄 수 있는필리 코엔자임Q10 국제표준인증(GMP, ISO_900, ISO_22000)을 받은 인도산 코엔자임Q10 원료를 식약처 1일 섭취량 (100 mg)만큼 충분히 담았습니다. 아사이베리추출분말 등 부원료 함유아사이베리추출분말, 빌베리 추출물, 포도씨앗유 등 부원료 함유비타민B1, 판토텐산, 비오틴은 탄수화물, 단백질 또는 지방의 대사에 필요하며 에너지 생성에 필요합니다.비타민B2, 나이아신은 체내 에너지 생성에 필요합니다. 활력이 없는 현대인에게 필요한 영양성분입니다.비타민B6의 섭취량은 혈중 호모시스테인 수준을 유지하는데 필요합니다.뼈를 형성하는 칼슘은 신경과 근육 기능 유지와 정상적인 혈액 응고에 필요하며 골다공증 발생 위험 감소에 도움을 줍니다.에너지 이용에 필요하고신경과 근육 기능 유지에 필요뼈와 치아의 구성요소인 마그네슘은 세포막을 안정시키고 신경의 자극을 전달하며 지방, 단백질, 핵산의 합성에 관여합니다.칼슘을 도와뼈의 형성과 유지에 필요몸안의 칼슘농도를 안정적으로 유지시키는 비타민D는 골다공증 발생 위험 감소에 도움을 주는 것으로 알려져 있습니다.','/na/resources/upfiles/2022052923511777809.png',to_date('22/05/15','RR/MM/DD'),'Y');
Insert into NA.PRODUCT (PRO_NO,PRO_NAME,PRO_PRICE,PRO_STOCK,PRO_EFFICACY,PRO_DESCRIPTION,PRO_IMG_PATH,PRO_ENROLL_DATE,PRO_STATUS) values (6073,'마그네슘ED',100000,200,'배변활동','활성산소로부터 인체를 보호하고높은 혈압 감소에 도움을 줄 수 있는필리 코엔자임Q10 국제표준인증(GMP, ISO_900, ISO_22000)을 받은 인도산 코엔자임Q10 원료를 식약처 1일 섭취량 (100 mg)만큼 충분히 담았습니다. 아사이베리추출분말 등 부원료 함유아사이베리추출분말, 빌베리 추출물, 포도씨앗유 등 부원료 함유비타민B1, 판토텐산, 비오틴은 탄수화물, 단백질 또는 지방의 대사에 필요하며 에너지 생성에 필요합니다.비타민B2, 나이아신은 체내 에너지 생성에 필요합니다. 활력이 없는 현대인에게 필요한 영양성분입니다.비타민B6의 섭취량은 혈중 호모시스테인 수준을 유지하는데 필요합니다.뼈를 형성하는 칼슘은 신경과 근육 기능 유지와 정상적인 혈액 응고에 필요하며 골다공증 발생 위험 감소에 도움을 줍니다.에너지 이용에 필요하고신경과 근육 기능 유지에 필요뼈와 치아의 구성요소인 마그네슘은 세포막을 안정시키고 신경의 자극을 전달하며 지방, 단백질, 핵산의 합성에 관여합니다.칼슘을 도와뼈의 형성과 유지에 필요몸안의 칼슘농도를 안정적으로 유지시키는 비타민D는 골다공증 발생 위험 감소에 도움을 주는 것으로 알려져 있습니다.','/na/resources/upfiles/2022052923525277862.png',to_date('22/05/29','RR/MM/DD'),'Y');
Insert into NA.PRODUCT (PRO_NO,PRO_NAME,PRO_PRICE,PRO_STOCK,PRO_EFFICACY,PRO_DESCRIPTION,PRO_IMG_PATH,PRO_ENROLL_DATE,PRO_STATUS) values (6074,'밀크씨슬ED',12000,200,'피부건강','활성산소로부터 인체를 보호하고높은 혈압 감소에 도움을 줄 수 있는필리 코엔자임Q10 국제표준인증(GMP, ISO_900, ISO_22000)을 받은 인도산 코엔자임Q10 원료를 식약처 1일 섭취량 (100 mg)만큼 충분히 담았습니다. 아사이베리추출분말 등 부원료 함유아사이베리추출분말, 빌베리 추출물, 포도씨앗유 등 부원료 함유비타민B1, 판토텐산, 비오틴은 탄수화물, 단백질 또는 지방의 대사에 필요하며 에너지 생성에 필요합니다.비타민B2, 나이아신은 체내 에너지 생성에 필요합니다. 활력이 없는 현대인에게 필요한 영양성분입니다.비타민B6의 섭취량은 혈중 호모시스테인 수준을 유지하는데 필요합니다.뼈를 형성하는 칼슘은 신경과 근육 기능 유지와 정상적인 혈액 응고에 필요하며 골다공증 발생 위험 감소에 도움을 줍니다.에너지 이용에 필요하고신경과 근육 기능 유지에 필요뼈와 치아의 구성요소인 마그네슘은 세포막을 안정시키고 신경의 자극을 전달하며 지방, 단백질, 핵산의 합성에 관여합니다.칼슘을 도와뼈의 형성과 유지에 필요몸안의 칼슘농도를 안정적으로 유지시키는 비타민D는 골다공증 발생 위험 감소에 도움을 주는 것으로 알려져 있습니다.','/na/resources/upfiles/2022052923541758533.png',to_date('22/05/24','RR/MM/DD'),'Y');
Insert into NA.PRODUCT (PRO_NO,PRO_NAME,PRO_PRICE,PRO_STOCK,PRO_EFFICACY,PRO_DESCRIPTION,PRO_IMG_PATH,PRO_ENROLL_DATE,PRO_STATUS) values (6076,'비타민 ETG',25000,240,'에너지충전','활성산소로부터 인체를 보호하고높은 혈압 감소에 도움을 줄 수 있는필리 코엔자임Q10 국제표준인증(GMP, ISO_900, ISO_22000)을 받은 인도산 코엔자임Q10 원료를 식약처 1일 섭취량 (100 mg)만큼 충분히 담았습니다. 아사이베리추출분말 등 부원료 함유아사이베리추출분말, 빌베리 추출물, 포도씨앗유 등 부원료 함유비타민B1, 판토텐산, 비오틴은 탄수화물, 단백질 또는 지방의 대사에 필요하며 에너지 생성에 필요합니다.비타민B2, 나이아신은 체내 에너지 생성에 필요합니다. 활력이 없는 현대인에게 필요한 영양성분입니다.비타민B6의 섭취량은 혈중 호모시스테인 수준을 유지하는데 필요합니다.뼈를 형성하는 칼슘은 신경과 근육 기능 유지와 정상적인 혈액 응고에 필요하며 골다공증 발생 위험 감소에 도움을 줍니다.에너지 이용에 필요하고신경과 근육 기능 유지에 필요뼈와 치아의 구성요소인 마그네슘은 세포막을 안정시키고 신경의 자극을 전달하며 지방, 단백질, 핵산의 합성에 관여합니다.칼슘을 도와뼈의 형성과 유지에 필요몸안의 칼슘농도를 안정적으로 유지시키는 비타민D는 골다공증 발생 위험 감소에 도움을 주는 것으로 알려져 있습니다.','/na/resources/upfiles/2022052923454526304.png',to_date('22/05/01','RR/MM/DD'),'Y');
Insert into NA.PRODUCT (PRO_NO,PRO_NAME,PRO_PRICE,PRO_STOCK,PRO_EFFICACY,PRO_DESCRIPTION,PRO_IMG_PATH,PRO_ENROLL_DATE,PRO_STATUS) values (6077,'루테인YH',34000,100,'피부건강','활성산소로부터 인체를 보호하고높은 혈압 감소에 도움을 줄 수 있는필리 코엔자임Q10 국제표준인증(GMP, ISO_900, ISO_22000)을 받은 인도산 코엔자임Q10 원료를 식약처 1일 섭취량 (100 mg)만큼 충분히 담았습니다. 아사이베리추출분말 등 부원료 함유아사이베리추출분말, 빌베리 추출물, 포도씨앗유 등 부원료 함유비타민B1, 판토텐산, 비오틴은 탄수화물, 단백질 또는 지방의 대사에 필요하며 에너지 생성에 필요합니다.비타민B2, 나이아신은 체내 에너지 생성에 필요합니다. 활력이 없는 현대인에게 필요한 영양성분입니다.비타민B6의 섭취량은 혈중 호모시스테인 수준을 유지하는데 필요합니다.뼈를 형성하는 칼슘은 신경과 근육 기능 유지와 정상적인 혈액 응고에 필요하며 골다공증 발생 위험 감소에 도움을 줍니다.에너지 이용에 필요하고신경과 근육 기능 유지에 필요뼈와 치아의 구성요소인 마그네슘은 세포막을 안정시키고 신경의 자극을 전달하며 지방, 단백질, 핵산의 합성에 관여합니다.칼슘을 도와뼈의 형성과 유지에 필요몸안의 칼슘농도를 안정적으로 유지시키는 비타민D는 골다공증 발생 위험 감소에 도움을 주는 것으로 알려져 있습니다.','/na/resources/upfiles/2022052923463873635.png',to_date('22/05/05','RR/MM/DD'),'Y');
Insert into NA.PRODUCT (PRO_NO,PRO_NAME,PRO_PRICE,PRO_STOCK,PRO_EFFICACY,PRO_DESCRIPTION,PRO_IMG_PATH,PRO_ENROLL_DATE,PRO_STATUS) values (6078,'마그네슘UJ',42000,150,'에너지충전','활성산소로부터 인체를 보호하고높은 혈압 감소에 도움을 줄 수 있는필리 코엔자임Q10 국제표준인증(GMP, ISO_900, ISO_22000)을 받은 인도산 코엔자임Q10 원료를 식약처 1일 섭취량 (100 mg)만큼 충분히 담았습니다. 아사이베리추출분말 등 부원료 함유아사이베리추출분말, 빌베리 추출물, 포도씨앗유 등 부원료 함유비타민B1, 판토텐산, 비오틴은 탄수화물, 단백질 또는 지방의 대사에 필요하며 에너지 생성에 필요합니다.비타민B2, 나이아신은 체내 에너지 생성에 필요합니다. 활력이 없는 현대인에게 필요한 영양성분입니다.비타민B6의 섭취량은 혈중 호모시스테인 수준을 유지하는데 필요합니다.뼈를 형성하는 칼슘은 신경과 근육 기능 유지와 정상적인 혈액 응고에 필요하며 골다공증 발생 위험 감소에 도움을 줍니다.에너지 이용에 필요하고신경과 근육 기능 유지에 필요뼈와 치아의 구성요소인 마그네슘은 세포막을 안정시키고 신경의 자극을 전달하며 지방, 단백질, 핵산의 합성에 관여합니다.칼슘을 도와뼈의 형성과 유지에 필요몸안의 칼슘농도를 안정적으로 유지시키는 비타민D는 골다공증 발생 위험 감소에 도움을 주는 것으로 알려져 있습니다.','/na/resources/upfiles/2022052923472354166.png',to_date('22/05/23','RR/MM/DD'),'Y');
Insert into NA.PRODUCT (PRO_NO,PRO_NAME,PRO_PRICE,PRO_STOCK,PRO_EFFICACY,PRO_DESCRIPTION,PRO_IMG_PATH,PRO_ENROLL_DATE,PRO_STATUS) values (6079,'밀크씨슬IK',54000,150,'면역력증진','활성산소로부터 인체를 보호하고높은 혈압 감소에 도움을 줄 수 있는필리 코엔자임Q10 국제표준인증(GMP, ISO_900, ISO_22000)을 받은 인도산 코엔자임Q10 원료를 식약처 1일 섭취량 (100 mg)만큼 충분히 담았습니다. 아사이베리추출분말 등 부원료 함유아사이베리추출분말, 빌베리 추출물, 포도씨앗유 등 부원료 함유비타민B1, 판토텐산, 비오틴은 탄수화물, 단백질 또는 지방의 대사에 필요하며 에너지 생성에 필요합니다.비타민B2, 나이아신은 체내 에너지 생성에 필요합니다. 활력이 없는 현대인에게 필요한 영양성분입니다.비타민B6의 섭취량은 혈중 호모시스테인 수준을 유지하는데 필요합니다.뼈를 형성하는 칼슘은 신경과 근육 기능 유지와 정상적인 혈액 응고에 필요하며 골다공증 발생 위험 감소에 도움을 줍니다.에너지 이용에 필요하고신경과 근육 기능 유지에 필요뼈와 치아의 구성요소인 마그네슘은 세포막을 안정시키고 신경의 자극을 전달하며 지방, 단백질, 핵산의 합성에 관여합니다.칼슘을 도와뼈의 형성과 유지에 필요몸안의 칼슘농도를 안정적으로 유지시키는 비타민D는 골다공증 발생 위험 감소에 도움을 주는 것으로 알려져 있습니다.','/na/resources/upfiles/2022052923481025901.png',to_date('22/05/12','RR/MM/DD'),'Y');
Insert into NA.PRODUCT (PRO_NO,PRO_NAME,PRO_PRICE,PRO_STOCK,PRO_EFFICACY,PRO_DESCRIPTION,PRO_IMG_PATH,PRO_ENROLL_DATE,PRO_STATUS) values (6080,'비타민 COL',63000,200,'혈액개선','활성산소로부터 인체를 보호하고높은 혈압 감소에 도움을 줄 수 있는필리 코엔자임Q10 국제표준인증(GMP, ISO_900, ISO_22000)을 받은 인도산 코엔자임Q10 원료를 식약처 1일 섭취량 (100 mg)만큼 충분히 담았습니다. 아사이베리추출분말 등 부원료 함유아사이베리추출분말, 빌베리 추출물, 포도씨앗유 등 부원료 함유비타민B1, 판토텐산, 비오틴은 탄수화물, 단백질 또는 지방의 대사에 필요하며 에너지 생성에 필요합니다.비타민B2, 나이아신은 체내 에너지 생성에 필요합니다. 활력이 없는 현대인에게 필요한 영양성분입니다.비타민B6의 섭취량은 혈중 호모시스테인 수준을 유지하는데 필요합니다.뼈를 형성하는 칼슘은 신경과 근육 기능 유지와 정상적인 혈액 응고에 필요하며 골다공증 발생 위험 감소에 도움을 줍니다.에너지 이용에 필요하고신경과 근육 기능 유지에 필요뼈와 치아의 구성요소인 마그네슘은 세포막을 안정시키고 신경의 자극을 전달하며 지방, 단백질, 핵산의 합성에 관여합니다.칼슘을 도와뼈의 형성과 유지에 필요몸안의 칼슘농도를 안정적으로 유지시키는 비타민D는 골다공증 발생 위험 감소에 도움을 주는 것으로 알려져 있습니다.','/na/resources/upfiles/2022052923491291683.png',to_date('22/05/29','RR/MM/DD'),'Y');
Insert into NA.PRODUCT (PRO_NO,PRO_NAME,PRO_PRICE,PRO_STOCK,PRO_EFFICACY,PRO_DESCRIPTION,PRO_IMG_PATH,PRO_ENROLL_DATE,PRO_STATUS) values (6081,'오메가PPP',74000,200,'에너지충전','활성산소로부터 인체를 보호하고높은 혈압 감소에 도움을 줄 수 있는필리 코엔자임Q10 국제표준인증(GMP, ISO_900, ISO_22000)을 받은 인도산 코엔자임Q10 원료를 식약처 1일 섭취량 (100 mg)만큼 충분히 담았습니다. 아사이베리추출분말 등 부원료 함유아사이베리추출분말, 빌베리 추출물, 포도씨앗유 등 부원료 함유비타민B1, 판토텐산, 비오틴은 탄수화물, 단백질 또는 지방의 대사에 필요하며 에너지 생성에 필요합니다.비타민B2, 나이아신은 체내 에너지 생성에 필요합니다. 활력이 없는 현대인에게 필요한 영양성분입니다.비타민B6의 섭취량은 혈중 호모시스테인 수준을 유지하는데 필요합니다.뼈를 형성하는 칼슘은 신경과 근육 기능 유지와 정상적인 혈액 응고에 필요하며 골다공증 발생 위험 감소에 도움을 줍니다.에너지 이용에 필요하고신경과 근육 기능 유지에 필요뼈와 치아의 구성요소인 마그네슘은 세포막을 안정시키고 신경의 자극을 전달하며 지방, 단백질, 핵산의 합성에 관여합니다.칼슘을 도와뼈의 형성과 유지에 필요몸안의 칼슘농도를 안정적으로 유지시키는 비타민D는 골다공증 발생 위험 감소에 도움을 주는 것으로 알려져 있습니다.','/na/resources/upfiles/2022052923495955697.png',to_date('22/05/01','RR/MM/DD'),'Y');
Insert into NA.PRODUCT (PRO_NO,PRO_NAME,PRO_PRICE,PRO_STOCK,PRO_EFFICACY,PRO_DESCRIPTION,PRO_IMG_PATH,PRO_ENROLL_DATE,PRO_STATUS) values (6082,'옥티코사놀QQ',78000,300,'간기능개선','활성산소로부터 인체를 보호하고높은 혈압 감소에 도움을 줄 수 있는필리 코엔자임Q10 국제표준인증(GMP, ISO_900, ISO_22000)을 받은 인도산 코엔자임Q10 원료를 식약처 1일 섭취량 (100 mg)만큼 충분히 담았습니다. 아사이베리추출분말 등 부원료 함유아사이베리추출분말, 빌베리 추출물, 포도씨앗유 등 부원료 함유비타민B1, 판토텐산, 비오틴은 탄수화물, 단백질 또는 지방의 대사에 필요하며 에너지 생성에 필요합니다.비타민B2, 나이아신은 체내 에너지 생성에 필요합니다. 활력이 없는 현대인에게 필요한 영양성분입니다.비타민B6의 섭취량은 혈중 호모시스테인 수준을 유지하는데 필요합니다.뼈를 형성하는 칼슘은 신경과 근육 기능 유지와 정상적인 혈액 응고에 필요하며 골다공증 발생 위험 감소에 도움을 줍니다.에너지 이용에 필요하고신경과 근육 기능 유지에 필요뼈와 치아의 구성요소인 마그네슘은 세포막을 안정시키고 신경의 자극을 전달하며 지방, 단백질, 핵산의 합성에 관여합니다.칼슘을 도와뼈의 형성과 유지에 필요몸안의 칼슘농도를 안정적으로 유지시키는 비타민D는 골다공증 발생 위험 감소에 도움을 주는 것으로 알려져 있습니다.','/na/resources/upfiles/2022052923504183807.png',to_date('22/05/04','RR/MM/DD'),'Y');
Insert into NA.PRODUCT (PRO_NO,PRO_NAME,PRO_PRICE,PRO_STOCK,PRO_EFFICACY,PRO_DESCRIPTION,PRO_IMG_PATH,PRO_ENROLL_DATE,PRO_STATUS) values (6083,'프로바이오틱스WW',83000,200,'배변활동','활성산소로부터 인체를 보호하고높은 혈압 감소에 도움을 줄 수 있는필리 코엔자임Q10 국제표준인증(GMP, ISO_900, ISO_22000)을 받은 인도산 코엔자임Q10 원료를 식약처 1일 섭취량 (100 mg)만큼 충분히 담았습니다. 아사이베리추출분말 등 부원료 함유아사이베리추출분말, 빌베리 추출물, 포도씨앗유 등 부원료 함유비타민B1, 판토텐산, 비오틴은 탄수화물, 단백질 또는 지방의 대사에 필요하며 에너지 생성에 필요합니다.비타민B2, 나이아신은 체내 에너지 생성에 필요합니다. 활력이 없는 현대인에게 필요한 영양성분입니다.비타민B6의 섭취량은 혈중 호모시스테인 수준을 유지하는데 필요합니다.뼈를 형성하는 칼슘은 신경과 근육 기능 유지와 정상적인 혈액 응고에 필요하며 골다공증 발생 위험 감소에 도움을 줍니다.에너지 이용에 필요하고신경과 근육 기능 유지에 필요뼈와 치아의 구성요소인 마그네슘은 세포막을 안정시키고 신경의 자극을 전달하며 지방, 단백질, 핵산의 합성에 관여합니다.칼슘을 도와뼈의 형성과 유지에 필요몸안의 칼슘농도를 안정적으로 유지시키는 비타민D는 골다공증 발생 위험 감소에 도움을 주는 것으로 알려져 있습니다.','/na/resources/upfiles/2022052923511777809.png',to_date('22/05/22','RR/MM/DD'),'Y');
Insert into NA.PRODUCT (PRO_NO,PRO_NAME,PRO_PRICE,PRO_STOCK,PRO_EFFICACY,PRO_DESCRIPTION,PRO_IMG_PATH,PRO_ENROLL_DATE,PRO_STATUS) values (6084,'코엔자임 Q10EE',91000,200,'피부건강','활성산소로부터 인체를 보호하고높은 혈압 감소에 도움을 줄 수 있는필리 코엔자임Q10 국제표준인증(GMP, ISO_900, ISO_22000)을 받은 인도산 코엔자임Q10 원료를 식약처 1일 섭취량 (100 mg)만큼 충분히 담았습니다. 아사이베리추출분말 등 부원료 함유아사이베리추출분말, 빌베리 추출물, 포도씨앗유 등 부원료 함유비타민B1, 판토텐산, 비오틴은 탄수화물, 단백질 또는 지방의 대사에 필요하며 에너지 생성에 필요합니다.비타민B2, 나이아신은 체내 에너지 생성에 필요합니다. 활력이 없는 현대인에게 필요한 영양성분입니다.비타민B6의 섭취량은 혈중 호모시스테인 수준을 유지하는데 필요합니다.뼈를 형성하는 칼슘은 신경과 근육 기능 유지와 정상적인 혈액 응고에 필요하며 골다공증 발생 위험 감소에 도움을 줍니다.에너지 이용에 필요하고신경과 근육 기능 유지에 필요뼈와 치아의 구성요소인 마그네슘은 세포막을 안정시키고 신경의 자극을 전달하며 지방, 단백질, 핵산의 합성에 관여합니다.칼슘을 도와뼈의 형성과 유지에 필요몸안의 칼슘농도를 안정적으로 유지시키는 비타민D는 골다공증 발생 위험 감소에 도움을 주는 것으로 알려져 있습니다.','/na/resources/upfiles/2022052923520468949.png',to_date('22/05/14','RR/MM/DD'),'Y');
Insert into NA.PRODUCT (PRO_NO,PRO_NAME,PRO_PRICE,PRO_STOCK,PRO_EFFICACY,PRO_DESCRIPTION,PRO_IMG_PATH,PRO_ENROLL_DATE,PRO_STATUS) values (6086,'리턴업 발효효소 베이직TT',12000,200,'에너지충전','활성산소로부터 인체를 보호하고높은 혈압 감소에 도움을 줄 수 있는필리 코엔자임Q10 국제표준인증(GMP, ISO_900, ISO_22000)을 받은 인도산 코엔자임Q10 원료를 식약처 1일 섭취량 (100 mg)만큼 충분히 담았습니다. 아사이베리추출분말 등 부원료 함유아사이베리추출분말, 빌베리 추출물, 포도씨앗유 등 부원료 함유비타민B1, 판토텐산, 비오틴은 탄수화물, 단백질 또는 지방의 대사에 필요하며 에너지 생성에 필요합니다.비타민B2, 나이아신은 체내 에너지 생성에 필요합니다. 활력이 없는 현대인에게 필요한 영양성분입니다.비타민B6의 섭취량은 혈중 호모시스테인 수준을 유지하는데 필요합니다.뼈를 형성하는 칼슘은 신경과 근육 기능 유지와 정상적인 혈액 응고에 필요하며 골다공증 발생 위험 감소에 도움을 줍니다.에너지 이용에 필요하고신경과 근육 기능 유지에 필요뼈와 치아의 구성요소인 마그네슘은 세포막을 안정시키고 신경의 자극을 전달하며 지방, 단백질, 핵산의 합성에 관여합니다.칼슘을 도와뼈의 형성과 유지에 필요몸안의 칼슘농도를 안정적으로 유지시키는 비타민D는 골다공증 발생 위험 감소에 도움을 주는 것으로 알려져 있습니다.','/na/resources/upfiles/2022052923491291683.png',to_date('22/05/29','RR/MM/DD'),'Y');
Insert into NA.PRODUCT (PRO_NO,PRO_NAME,PRO_PRICE,PRO_STOCK,PRO_EFFICACY,PRO_DESCRIPTION,PRO_IMG_PATH,PRO_ENROLL_DATE,PRO_STATUS) values (6088,'비타민 EUU',25000,240,'에너지충전','활성산소로부터 인체를 보호하고높은 혈압 감소에 도움을 줄 수 있는필리 코엔자임Q10 국제표준인증(GMP, ISO_900, ISO_22000)을 받은 인도산 코엔자임Q10 원료를 식약처 1일 섭취량 (100 mg)만큼 충분히 담았습니다. 아사이베리추출분말 등 부원료 함유아사이베리추출분말, 빌베리 추출물, 포도씨앗유 등 부원료 함유비타민B1, 판토텐산, 비오틴은 탄수화물, 단백질 또는 지방의 대사에 필요하며 에너지 생성에 필요합니다.비타민B2, 나이아신은 체내 에너지 생성에 필요합니다. 활력이 없는 현대인에게 필요한 영양성분입니다.비타민B6의 섭취량은 혈중 호모시스테인 수준을 유지하는데 필요합니다.뼈를 형성하는 칼슘은 신경과 근육 기능 유지와 정상적인 혈액 응고에 필요하며 골다공증 발생 위험 감소에 도움을 줍니다.에너지 이용에 필요하고신경과 근육 기능 유지에 필요뼈와 치아의 구성요소인 마그네슘은 세포막을 안정시키고 신경의 자극을 전달하며 지방, 단백질, 핵산의 합성에 관여합니다.칼슘을 도와뼈의 형성과 유지에 필요몸안의 칼슘농도를 안정적으로 유지시키는 비타민D는 골다공증 발생 위험 감소에 도움을 주는 것으로 알려져 있습니다.','/na/resources/upfiles/2022052923504183807.png',to_date('22/05/24','RR/MM/DD'),'Y');
Insert into NA.PRODUCT (PRO_NO,PRO_NAME,PRO_PRICE,PRO_STOCK,PRO_EFFICACY,PRO_DESCRIPTION,PRO_IMG_PATH,PRO_ENROLL_DATE,PRO_STATUS) values (6093,'오메가GG',91000,200,'면역력증진','활성산소로부터 인체를 보호하고높은 혈압 감소에 도움을 줄 수 있는필리 코엔자임Q10 국제표준인증(GMP, ISO_900, ISO_22000)을 받은 인도산 코엔자임Q10 원료를 식약처 1일 섭취량 (100 mg)만큼 충분히 담았습니다. 아사이베리추출분말 등 부원료 함유아사이베리추출분말, 빌베리 추출물, 포도씨앗유 등 부원료 함유비타민B1, 판토텐산, 비오틴은 탄수화물, 단백질 또는 지방의 대사에 필요하며 에너지 생성에 필요합니다.비타민B2, 나이아신은 체내 에너지 생성에 필요합니다. 활력이 없는 현대인에게 필요한 영양성분입니다.비타민B6의 섭취량은 혈중 호모시스테인 수준을 유지하는데 필요합니다.뼈를 형성하는 칼슘은 신경과 근육 기능 유지와 정상적인 혈액 응고에 필요하며 골다공증 발생 위험 감소에 도움을 줍니다.에너지 이용에 필요하고신경과 근육 기능 유지에 필요뼈와 치아의 구성요소인 마그네슘은 세포막을 안정시키고 신경의 자극을 전달하며 지방, 단백질, 핵산의 합성에 관여합니다.칼슘을 도와뼈의 형성과 유지에 필요몸안의 칼슘농도를 안정적으로 유지시키는 비타민D는 골다공증 발생 위험 감소에 도움을 주는 것으로 알려져 있습니다.','/na/resources/upfiles/2022052923444297363.png',to_date('22/05/29','RR/MM/DD'),'Y');
Insert into NA.PRODUCT (PRO_NO,PRO_NAME,PRO_PRICE,PRO_STOCK,PRO_EFFICACY,PRO_DESCRIPTION,PRO_IMG_PATH,PRO_ENROLL_DATE,PRO_STATUS) values (6094,'옥티코사놀HH',100000,300,'에너지충전','활성산소로부터 인체를 보호하고높은 혈압 감소에 도움을 줄 수 있는필리 코엔자임Q10 국제표준인증(GMP, ISO_900, ISO_22000)을 받은 인도산 코엔자임Q10 원료를 식약처 1일 섭취량 (100 mg)만큼 충분히 담았습니다. 아사이베리추출분말 등 부원료 함유아사이베리추출분말, 빌베리 추출물, 포도씨앗유 등 부원료 함유비타민B1, 판토텐산, 비오틴은 탄수화물, 단백질 또는 지방의 대사에 필요하며 에너지 생성에 필요합니다.비타민B2, 나이아신은 체내 에너지 생성에 필요합니다. 활력이 없는 현대인에게 필요한 영양성분입니다.비타민B6의 섭취량은 혈중 호모시스테인 수준을 유지하는데 필요합니다.뼈를 형성하는 칼슘은 신경과 근육 기능 유지와 정상적인 혈액 응고에 필요하며 골다공증 발생 위험 감소에 도움을 줍니다.에너지 이용에 필요하고신경과 근육 기능 유지에 필요뼈와 치아의 구성요소인 마그네슘은 세포막을 안정시키고 신경의 자극을 전달하며 지방, 단백질, 핵산의 합성에 관여합니다.칼슘을 도와뼈의 형성과 유지에 필요몸안의 칼슘농도를 안정적으로 유지시키는 비타민D는 골다공증 발생 위험 감소에 도움을 주는 것으로 알려져 있습니다.','/na/resources/upfiles/2022052923454526304.png',to_date('22/05/24','RR/MM/DD'),'Y');
Insert into NA.PRODUCT (PRO_NO,PRO_NAME,PRO_PRICE,PRO_STOCK,PRO_EFFICACY,PRO_DESCRIPTION,PRO_IMG_PATH,PRO_ENROLL_DATE,PRO_STATUS) values (6097,'히알루론산 스피루리나CC',25000,200,'면역력증진','활성산소로부터 인체를 보호하고높은 혈압 감소에 도움을 줄 수 있는필리 코엔자임Q10 국제표준인증(GMP, ISO_900, ISO_22000)을 받은 인도산 코엔자임Q10 원료를 식약처 1일 섭취량 (100 mg)만큼 충분히 담았습니다. 아사이베리추출분말 등 부원료 함유아사이베리추출분말, 빌베리 추출물, 포도씨앗유 등 부원료 함유비타민B1, 판토텐산, 비오틴은 탄수화물, 단백질 또는 지방의 대사에 필요하며 에너지 생성에 필요합니다.비타민B2, 나이아신은 체내 에너지 생성에 필요합니다. 활력이 없는 현대인에게 필요한 영양성분입니다.비타민B6의 섭취량은 혈중 호모시스테인 수준을 유지하는데 필요합니다.뼈를 형성하는 칼슘은 신경과 근육 기능 유지와 정상적인 혈액 응고에 필요하며 골다공증 발생 위험 감소에 도움을 줍니다.에너지 이용에 필요하고신경과 근육 기능 유지에 필요뼈와 치아의 구성요소인 마그네슘은 세포막을 안정시키고 신경의 자극을 전달하며 지방, 단백질, 핵산의 합성에 관여합니다.칼슘을 도와뼈의 형성과 유지에 필요몸안의 칼슘농도를 안정적으로 유지시키는 비타민D는 골다공증 발생 위험 감소에 도움을 주는 것으로 알려져 있습니다.','/na/resources/upfiles/2022052923481025901.png',to_date('22/05/05','RR/MM/DD'),'Y');
Insert into NA.PRODUCT (PRO_NO,PRO_NAME,PRO_PRICE,PRO_STOCK,PRO_EFFICACY,PRO_DESCRIPTION,PRO_IMG_PATH,PRO_ENROLL_DATE,PRO_STATUS) values (6098,'리턴업 발효효소 베이직VV',34000,200,'혈액개선','활성산소로부터 인체를 보호하고높은 혈압 감소에 도움을 줄 수 있는필리 코엔자임Q10 국제표준인증(GMP, ISO_900, ISO_22000)을 받은 인도산 코엔자임Q10 원료를 식약처 1일 섭취량 (100 mg)만큼 충분히 담았습니다. 아사이베리추출분말 등 부원료 함유아사이베리추출분말, 빌베리 추출물, 포도씨앗유 등 부원료 함유비타민B1, 판토텐산, 비오틴은 탄수화물, 단백질 또는 지방의 대사에 필요하며 에너지 생성에 필요합니다.비타민B2, 나이아신은 체내 에너지 생성에 필요합니다. 활력이 없는 현대인에게 필요한 영양성분입니다.비타민B6의 섭취량은 혈중 호모시스테인 수준을 유지하는데 필요합니다.뼈를 형성하는 칼슘은 신경과 근육 기능 유지와 정상적인 혈액 응고에 필요하며 골다공증 발생 위험 감소에 도움을 줍니다.에너지 이용에 필요하고신경과 근육 기능 유지에 필요뼈와 치아의 구성요소인 마그네슘은 세포막을 안정시키고 신경의 자극을 전달하며 지방, 단백질, 핵산의 합성에 관여합니다.칼슘을 도와뼈의 형성과 유지에 필요몸안의 칼슘농도를 안정적으로 유지시키는 비타민D는 골다공증 발생 위험 감소에 도움을 주는 것으로 알려져 있습니다.','/na/resources/upfiles/2022052923491291683.png',to_date('22/05/23','RR/MM/DD'),'Y');
Insert into NA.PRODUCT (PRO_NO,PRO_NAME,PRO_PRICE,PRO_STOCK,PRO_EFFICACY,PRO_DESCRIPTION,PRO_IMG_PATH,PRO_ENROLL_DATE,PRO_STATUS) values (6101,'루테인MM',63000,100,'에너지충전','활성산소로부터 인체를 보호하고높은 혈압 감소에 도움을 줄 수 있는필리 코엔자임Q10 국제표준인증(GMP, ISO_900, ISO_22000)을 받은 인도산 코엔자임Q10 원료를 식약처 1일 섭취량 (100 mg)만큼 충분히 담았습니다. 아사이베리추출분말 등 부원료 함유아사이베리추출분말, 빌베리 추출물, 포도씨앗유 등 부원료 함유비타민B1, 판토텐산, 비오틴은 탄수화물, 단백질 또는 지방의 대사에 필요하며 에너지 생성에 필요합니다.비타민B2, 나이아신은 체내 에너지 생성에 필요합니다. 활력이 없는 현대인에게 필요한 영양성분입니다.비타민B6의 섭취량은 혈중 호모시스테인 수준을 유지하는데 필요합니다.뼈를 형성하는 칼슘은 신경과 근육 기능 유지와 정상적인 혈액 응고에 필요하며 골다공증 발생 위험 감소에 도움을 줍니다.에너지 이용에 필요하고신경과 근육 기능 유지에 필요뼈와 치아의 구성요소인 마그네슘은 세포막을 안정시키고 신경의 자극을 전달하며 지방, 단백질, 핵산의 합성에 관여합니다.칼슘을 도와뼈의 형성과 유지에 필요몸안의 칼슘농도를 안정적으로 유지시키는 비타민D는 골다공증 발생 위험 감소에 도움을 주는 것으로 알려져 있습니다.','/na/resources/upfiles/2022052923511777809.png',to_date('22/05/01','RR/MM/DD'),'Y');
Insert into NA.PRODUCT (PRO_NO,PRO_NAME,PRO_PRICE,PRO_STOCK,PRO_EFFICACY,PRO_DESCRIPTION,PRO_IMG_PATH,PRO_ENROLL_DATE,PRO_STATUS) values (6102,'마그네슘11',74000,150,'간기능개선','홍삼에는 사포닌의 일종인 진세노사이드가 함유되어 있어 면역력 증진 및 피로개선 그리고 기억력 개선에 도움을 줄 수 있습니다.','/na/resources/upfiles/2022052923520468949.png',to_date('22/05/04','RR/MM/DD'),'Y');
Insert into NA.PRODUCT (PRO_NO,PRO_NAME,PRO_PRICE,PRO_STOCK,PRO_EFFICACY,PRO_DESCRIPTION,PRO_IMG_PATH,PRO_ENROLL_DATE,PRO_STATUS) values (6103,'밀크씨슬22',78000,300,'배변활동','활성산소로부터 인체를 보호하고높은 혈압 감소에 도움을 줄 수 있는필리 코엔자임Q10 국제표준인증(GMP, ISO_900, ISO_22000)을 받은 인도산 코엔자임Q10 원료를 식약처 1일 섭취량 (100 mg)만큼 충분히 담았습니다. 아사이베리추출분말 등 부원료 함유아사이베리추출분말, 빌베리 추출물, 포도씨앗유 등 부원료 함유비타민B1, 판토텐산, 비오틴은 탄수화물, 단백질 또는 지방의 대사에 필요하며 에너지 생성에 필요합니다.비타민B2, 나이아신은 체내 에너지 생성에 필요합니다. 활력이 없는 현대인에게 필요한 영양성분입니다.비타민B6의 섭취량은 혈중 호모시스테인 수준을 유지하는데 필요합니다.뼈를 형성하는 칼슘은 신경과 근육 기능 유지와 정상적인 혈액 응고에 필요하며 골다공증 발생 위험 감소에 도움을 줍니다.에너지 이용에 필요하고신경과 근육 기능 유지에 필요뼈와 치아의 구성요소인 마그네슘은 세포막을 안정시키고 신경의 자극을 전달하며 지방, 단백질, 핵산의 합성에 관여합니다.칼슘을 도와뼈의 형성과 유지에 필요몸안의 칼슘농도를 안정적으로 유지시키는 비타민D는 골다공증 발생 위험 감소에 도움을 주는 것으로 알려져 있습니다.','/na/resources/upfiles/2022052923525277862.png',to_date('22/05/22','RR/MM/DD'),'Y');
Insert into NA.PRODUCT (PRO_NO,PRO_NAME,PRO_PRICE,PRO_STOCK,PRO_EFFICACY,PRO_DESCRIPTION,PRO_IMG_PATH,PRO_ENROLL_DATE,PRO_STATUS) values (6105,'비타민 E44',74000,200,'면역력증진','홍삼에는 사포닌의 일종인 진세노사이드가 함유되어 있어 면역력 증진 및 피로개선 그리고 기억력 개선에 도움을 줄 수 있습니다.','/na/resources/upfiles/2022052923444297363.png',to_date('22/05/15','RR/MM/DD'),'Y');
Insert into NA.PRODUCT (PRO_NO,PRO_NAME,PRO_PRICE,PRO_STOCK,PRO_EFFICACY,PRO_DESCRIPTION,PRO_IMG_PATH,PRO_ENROLL_DATE,PRO_STATUS) values (6106,'루테인55',78000,200,'에너지충전','활성산소로부터 인체를 보호하고높은 혈압 감소에 도움을 줄 수 있는필리 코엔자임Q10 국제표준인증(GMP, ISO_900, ISO_22000)을 받은 인도산 코엔자임Q10 원료를 식약처 1일 섭취량 (100 mg)만큼 충분히 담았습니다. 아사이베리추출분말 등 부원료 함유아사이베리추출분말, 빌베리 추출물, 포도씨앗유 등 부원료 함유비타민B1, 판토텐산, 비오틴은 탄수화물, 단백질 또는 지방의 대사에 필요하며 에너지 생성에 필요합니다.비타민B2, 나이아신은 체내 에너지 생성에 필요합니다. 활력이 없는 현대인에게 필요한 영양성분입니다.비타민B6의 섭취량은 혈중 호모시스테인 수준을 유지하는데 필요합니다.뼈를 형성하는 칼슘은 신경과 근육 기능 유지와 정상적인 혈액 응고에 필요하며 골다공증 발생 위험 감소에 도움을 줍니다.에너지 이용에 필요하고신경과 근육 기능 유지에 필요뼈와 치아의 구성요소인 마그네슘은 세포막을 안정시키고 신경의 자극을 전달하며 지방, 단백질, 핵산의 합성에 관여합니다.칼슘을 도와뼈의 형성과 유지에 필요몸안의 칼슘농도를 안정적으로 유지시키는 비타민D는 골다공증 발생 위험 감소에 도움을 주는 것으로 알려져 있습니다.','/na/resources/upfiles/2022052923454526304.png',to_date('22/05/29','RR/MM/DD'),'Y');
Insert into NA.PRODUCT (PRO_NO,PRO_NAME,PRO_PRICE,PRO_STOCK,PRO_EFFICACY,PRO_DESCRIPTION,PRO_IMG_PATH,PRO_ENROLL_DATE,PRO_STATUS) values (6108,'밀크씨슬77',91000,300,'에너지충전','활성산소로부터 인체를 보호하고높은 혈압 감소에 도움을 줄 수 있는필리 코엔자임Q10 국제표준인증(GMP, ISO_900, ISO_22000)을 받은 인도산 코엔자임Q10 원료를 식약처 1일 섭취량 (100 mg)만큼 충분히 담았습니다. 아사이베리추출분말 등 부원료 함유아사이베리추출분말, 빌베리 추출물, 포도씨앗유 등 부원료 함유비타민B1, 판토텐산, 비오틴은 탄수화물, 단백질 또는 지방의 대사에 필요하며 에너지 생성에 필요합니다.비타민B2, 나이아신은 체내 에너지 생성에 필요합니다. 활력이 없는 현대인에게 필요한 영양성분입니다.비타민B6의 섭취량은 혈중 호모시스테인 수준을 유지하는데 필요합니다.뼈를 형성하는 칼슘은 신경과 근육 기능 유지와 정상적인 혈액 응고에 필요하며 골다공증 발생 위험 감소에 도움을 줍니다.에너지 이용에 필요하고신경과 근육 기능 유지에 필요뼈와 치아의 구성요소인 마그네슘은 세포막을 안정시키고 신경의 자극을 전달하며 지방, 단백질, 핵산의 합성에 관여합니다.칼슘을 도와뼈의 형성과 유지에 필요몸안의 칼슘농도를 안정적으로 유지시키는 비타민D는 골다공증 발생 위험 감소에 도움을 주는 것으로 알려져 있습니다.','/na/resources/upfiles/2022052923472354166.png',to_date('22/05/24','RR/MM/DD'),'Y');
Insert into NA.PRODUCT (PRO_NO,PRO_NAME,PRO_PRICE,PRO_STOCK,PRO_EFFICACY,PRO_DESCRIPTION,PRO_IMG_PATH,PRO_ENROLL_DATE,PRO_STATUS) values (6110,'오메가99',12000,100,'혈액개선','홍삼에는 사포닌의 일종인 진세노사이드가 함유되어 있어 면역력 증진 및 피로개선 그리고 기억력 개선에 도움을 줄 수 있습니다.','/na/resources/upfiles/2022052923491291683.png',to_date('22/05/14','RR/MM/DD'),'Y');
Insert into NA.PRODUCT (PRO_NO,PRO_NAME,PRO_PRICE,PRO_STOCK,PRO_EFFICACY,PRO_DESCRIPTION,PRO_IMG_PATH,PRO_ENROLL_DATE,PRO_STATUS) values (6111,'옥티코사놀WF',15000,150,'에너지충전','활성산소로부터 인체를 보호하고높은 혈압 감소에 도움을 줄 수 있는필리 코엔자임Q10 국제표준인증(GMP, ISO_900, ISO_22000)을 받은 인도산 코엔자임Q10 원료를 식약처 1일 섭취량 (100 mg)만큼 충분히 담았습니다. 아사이베리추출분말 등 부원료 함유아사이베리추출분말, 빌베리 추출물, 포도씨앗유 등 부원료 함유비타민B1, 판토텐산, 비오틴은 탄수화물, 단백질 또는 지방의 대사에 필요하며 에너지 생성에 필요합니다.비타민B2, 나이아신은 체내 에너지 생성에 필요합니다. 활력이 없는 현대인에게 필요한 영양성분입니다.비타민B6의 섭취량은 혈중 호모시스테인 수준을 유지하는데 필요합니다.뼈를 형성하는 칼슘은 신경과 근육 기능 유지와 정상적인 혈액 응고에 필요하며 골다공증 발생 위험 감소에 도움을 줍니다.에너지 이용에 필요하고신경과 근육 기능 유지에 필요뼈와 치아의 구성요소인 마그네슘은 세포막을 안정시키고 신경의 자극을 전달하며 지방, 단백질, 핵산의 합성에 관여합니다.칼슘을 도와뼈의 형성과 유지에 필요몸안의 칼슘농도를 안정적으로 유지시키는 비타민D는 골다공증 발생 위험 감소에 도움을 주는 것으로 알려져 있습니다.','/na/resources/upfiles/2022052923495955697.png',to_date('22/05/15','RR/MM/DD'),'Y');
Insert into NA.PRODUCT (PRO_NO,PRO_NAME,PRO_PRICE,PRO_STOCK,PRO_EFFICACY,PRO_DESCRIPTION,PRO_IMG_PATH,PRO_ENROLL_DATE,PRO_STATUS) values (6113,'코엔자임 Q10RG',34000,200,'배변활동','홍삼에는 사포닌의 일종인 진세노사이드가 함유되어 있어 면역력 증진 및 피로개선 그리고 기억력 개선에 도움을 줄 수 있습니다.','/na/resources/upfiles/2022052923511777809.png',to_date('22/05/29','RR/MM/DD'),'Y');
Insert into NA.PRODUCT (PRO_NO,PRO_NAME,PRO_PRICE,PRO_STOCK,PRO_EFFICACY,PRO_DESCRIPTION,PRO_IMG_PATH,PRO_ENROLL_DATE,PRO_STATUS) values (6114,'히알루론산 스피루리나TH',42000,200,'피부건강','활성산소로부터 인체를 보호하고높은 혈압 감소에 도움을 줄 수 있는필리 코엔자임Q10 국제표준인증(GMP, ISO_900, ISO_22000)을 받은 인도산 코엔자임Q10 원료를 식약처 1일 섭취량 (100 mg)만큼 충분히 담았습니다. 아사이베리추출분말 등 부원료 함유아사이베리추출분말, 빌베리 추출물, 포도씨앗유 등 부원료 함유비타민B1, 판토텐산, 비오틴은 탄수화물, 단백질 또는 지방의 대사에 필요하며 에너지 생성에 필요합니다.비타민B2, 나이아신은 체내 에너지 생성에 필요합니다. 활력이 없는 현대인에게 필요한 영양성분입니다.비타민B6의 섭취량은 혈중 호모시스테인 수준을 유지하는데 필요합니다.뼈를 형성하는 칼슘은 신경과 근육 기능 유지와 정상적인 혈액 응고에 필요하며 골다공증 발생 위험 감소에 도움을 줍니다.에너지 이용에 필요하고신경과 근육 기능 유지에 필요뼈와 치아의 구성요소인 마그네슘은 세포막을 안정시키고 신경의 자극을 전달하며 지방, 단백질, 핵산의 합성에 관여합니다.칼슘을 도와뼈의 형성과 유지에 필요몸안의 칼슘농도를 안정적으로 유지시키는 비타민D는 골다공증 발생 위험 감소에 도움을 주는 것으로 알려져 있습니다.','/na/resources/upfiles/2022052923520468949.png',to_date('22/05/24','RR/MM/DD'),'Y');
Insert into NA.PRODUCT (PRO_NO,PRO_NAME,PRO_PRICE,PRO_STOCK,PRO_EFFICACY,PRO_DESCRIPTION,PRO_IMG_PATH,PRO_ENROLL_DATE,PRO_STATUS) values (6116,'비타민 BUK',63000,200,'에너지충전','홍삼에는 사포닌의 일종인 진세노사이드가 함유되어 있어 면역력 증진 및 피로개선 그리고 기억력 개선에 도움을 줄 수 있습니다.','/na/resources/upfiles/2022052923491291683.png',to_date('22/05/01','RR/MM/DD'),'Y');
--------------------------------------------------------
--  DDL for Index SYS_C007703
--------------------------------------------------------

  CREATE UNIQUE INDEX "NA"."SYS_C007703" ON "NA"."PRODUCT" ("PRO_NO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index SYS_C007704
--------------------------------------------------------

  CREATE UNIQUE INDEX "NA"."SYS_C007704" ON "NA"."PRODUCT" ("PRO_NAME") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  Constraints for Table PRODUCT
--------------------------------------------------------

  ALTER TABLE "NA"."PRODUCT" ADD UNIQUE ("PRO_NAME")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "NA"."PRODUCT" ADD PRIMARY KEY ("PRO_NO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "NA"."PRODUCT" MODIFY ("PRO_PRICE" NOT NULL ENABLE);
