/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.78
 * Generated at: 2022-05-30 01:00:37 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.views.user.product;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.util.ArrayList;
import com.na.user.product.model.vo.Product;
import com.na.template.model.vo.PageInfo;
import com.na.user.member.model.vo.Member;

public final class proList_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("/views/user/product/../common/header.jsp", Long.valueOf(1653811761050L));
    _jspx_dependants.put("/views/user/product/../common/footer.jsp", Long.valueOf(1653837857511L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("com.na.user.product.model.vo.Product");
    _jspx_imports_classes.add("com.na.user.member.model.vo.Member");
    _jspx_imports_classes.add("java.util.ArrayList");
    _jspx_imports_classes.add("com.na.template.model.vo.PageInfo");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");

	ArrayList<Product> list = (ArrayList<Product>)request.getAttribute("list");
	PageInfo pi = (PageInfo)request.getAttribute("pi");
	
	int currentPage = pi.getCurrentPage();
	int startPage = pi.getStartPage();
	int endPage = pi.getEndPage();
	int maxPage = pi.getMaxPage();
	

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"en\">\r\n");
      out.write("<head>\r\n");
      out.write("    <meta charset=\"UTF-8\">\r\n");
      out.write("    <meta http-equiv=\"X-UA-Compatible\" content=\"IE=edge\">\r\n");
      out.write("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\r\n");
      out.write("    <link rel=\"preconnect\" href=\"https://fonts.googleapis.com\">\r\n");
      out.write("    <link rel=\"preconnect\" href=\"https://fonts.gstatic.com\" crossorigin>\r\n");
      out.write("    <link href=\"https://fonts.googleapis.com/css2?family=Noto+Sans+KR:wght@400&display=swap\" rel=\"stylesheet\">\r\n");
      out.write("    <script src=\"https://ajax.googleapis.com/ajax/libs/jquery/3.6.0/jquery.min.js\"></script>\r\n");
      out.write("\r\n");
      out.write("<!-- Latest compiled and minified CSS -->\r\n");
      out.write("<link rel=\"stylesheet\" href=\"https://cdn.jsdelivr.net/npm/bootstrap@4.6.1/dist/css/bootstrap.min.css\">\r\n");
      out.write("\r\n");
      out.write("<!-- Popper JS -->\r\n");
      out.write("<script src=\"https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js\"></script>\r\n");
      out.write("\r\n");
      out.write("<!-- Latest compiled JavaScript -->\r\n");
      out.write("<script src=\"https://cdn.jsdelivr.net/npm/bootstrap@4.6.1/dist/js/bootstrap.bundle.min.js\"></script>\r\n");
      out.write("    \r\n");
      out.write("    <title>제품보기</title>\r\n");
      out.write("    <style>\r\n");
      out.write("     div{\r\n");
      out.write("          box-sizing: border-box;\r\n");
      out.write("          /*border: 1px solid red; /*가이드라인*/\r\n");
      out.write("          height : 100%;\r\n");
      out.write("      }\r\n");
      out.write("      body{\r\n");
      out.write("        font-family: 'Noto Sans KR', sans-serif;\r\n");
      out.write("      }\r\n");
      out.write("\r\n");
      out.write("      .content{\r\n");
      out.write("          height : 1144px;\r\n");
      out.write("          width : 1000px;\r\n");
      out.write("          margin: auto;\r\n");
      out.write("          margin-top:50px;\r\n");
      out.write("      }\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("        /*content영역 정렬*/\r\n");
      out.write("        h2{\r\n");
      out.write("            text-align: center;\r\n");
      out.write("            color: rgba(48, 48, 49, 0.6);\r\n");
      out.write("            font-size: 25px;\r\n");
      out.write("        }\r\n");
      out.write("        /*검색영역*/\r\n");
      out.write("        .content{\r\n");
      out.write("            position: relative;\r\n");
      out.write("            height: 90%;\r\n");
      out.write("        }\r\n");
      out.write("        .content>div{height: 0;}\r\n");
      out.write("        #search{height: 450px;}\r\n");
      out.write("        #search_1{height: 110px;}\r\n");
      out.write("        #search_2{height: 40px;}\r\n");
      out.write("        #search_3{height: 270px;}\r\n");
      out.write("        #pro_orderby{height : 30px; }\r\n");
      out.write("        #pro_list1, #pro_list2{ height : 410px;}\r\n");
      out.write("        #pro_paging{ height : 30px;}\r\n");
      out.write("\r\n");
      out.write("        #search_1>h2{\r\n");
      out.write("            font-family: 'Noto Sans KR', sans-serif;\r\n");
      out.write("            color: rgba(7, 7, 7, 0.5);\r\n");
      out.write("            font-size: 30px;\r\n");
      out.write("            font-weight: 700;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        hr{color: rgba(73, 71, 71, 0.5);}\r\n");
      out.write("        #search_2>div{ float: left;}\r\n");
      out.write("        #search_2_1{ width: 220px;}\r\n");
      out.write("        #search_2_2{ width: 530px;}\r\n");
      out.write("        #search_2_3{ width: 120px;}\r\n");
      out.write("\r\n");
      out.write("        #pro_orderby>div{\r\n");
      out.write("            float: right;\r\n");
      out.write("            width: 200px;\r\n");
      out.write("        }\r\n");
      out.write("        #pro_orderby>div>a{\r\n");
      out.write("            text-decoration: none;\r\n");
      out.write("            font-size: 12px;\r\n");
      out.write("            line-height: 30px;\r\n");
      out.write("            color : rgba(73, 71, 71, 0.5);\r\n");
      out.write("        }\r\n");
      out.write("        #pro_list1>div{float: left;}\r\n");
      out.write("        #pro_list1_1, #pro_list1_7{width: 80px;}\r\n");
      out.write("        #pro_list1_3, #pro_list1_5{width: 30px;} \r\n");
      out.write("        #pro_list1_2, #pro_list1_4, #pro_list1_6{width: 258px;}\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("        #pro_list2>div{float: left;}\r\n");
      out.write("        #pro_list2_1, #pro_list2_7{width: 80px;}\r\n");
      out.write("        #pro_list2_3, #pro_list2_5{width: 30px;} \r\n");
      out.write("        #pro_list2_2, #pro_list2_4, #pro_list2_6{width: 258px;}\r\n");
      out.write("\r\n");
      out.write("        #search_2_2>input{\r\n");
      out.write("            width: 500px;\r\n");
      out.write("            height: 20px;\r\n");
      out.write("            margin-left: 10px;\r\n");
      out.write("            margin-top: 5px;\r\n");
      out.write("        }\r\n");
      out.write("        #search_2_3>input{\r\n");
      out.write("            width: 100px;\r\n");
      out.write("            margin-top : 5px;\r\n");
      out.write("        }\r\n");
      out.write("        #search_3>#cat_t{\r\n");
      out.write("            width: 900px;\r\n");
      out.write("            height: 100px;\r\n");
      out.write("            border: 5px double rgba(209, 206, 206, 0.5);\r\n");
      out.write("            margin: auto;\r\n");
      out.write("            margin-top: 50px;\r\n");
      out.write("        }\r\n");
      out.write("        #cat_t>tr{\r\n");
      out.write("            text-align: right;\r\n");
      out.write("            height: 50px;\r\n");
      out.write("            width: 40px;\r\n");
      out.write("            border: 5px double rgba(209, 206, 206, 0.5);\r\n");
      out.write("            font-size: 15px;\r\n");
      out.write("        }\r\n");
      out.write("        #cat_t th{\r\n");
      out.write("            height: 50px;\r\n");
      out.write("            width: 40px;\r\n");
      out.write("            font-size: 15px;\r\n");
      out.write("            text-align: center;\r\n");
      out.write("        }\r\n");
      out.write("        #cat_t td{\r\n");
      out.write("            text-align: right;\r\n");
      out.write("            height: 50px;\r\n");
      out.write("            width: 40px;\r\n");
      out.write("            font-size: 15px;\r\n");
      out.write("        }\r\n");
      out.write("        #cat_t a{\r\n");
      out.write("            color: black;\r\n");
      out.write("            text-decoration: none;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        #pro_list1_2>div, #pro_list1_4>div, #pro_list1_6>div{height: 0px;}\r\n");
      out.write("        #pro_list2_2>div, #pro_list2_4>div, #pro_list2_6>div{height: 0px;}\r\n");
      out.write("        \r\n");
      out.write("        #pro_list1_2>#pro_list1_2_img, #pro_list1_4>#pro_list1_4_img, #pro_list1_6>#pro_list1_6_img{ \r\n");
      out.write("            height: 330px;\r\n");
      out.write("           /* border: 1px solid rgba(209, 206, 206, 0.5); */\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        #pro_list1_2_img>img, #pro_list1_4_img>img, #pro_list1_6_img>img{ \r\n");
      out.write("            width: 100%;\r\n");
      out.write("            height: 100%;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        #pro_list2_2_img>img, #pro_list2_4_img>img, #pro_list2_6_img>img{ \r\n");
      out.write("            height: 100%;\r\n");
      out.write("            width: 100%;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        #pro_list2_2>#pro_list2_2_img, #pro_list2_4>#pro_list2_4_img, #pro_list2_6>#pro_list2_6_img{ \r\n");
      out.write("            height: 330px;\r\n");
      out.write("           /* border: 1px solid rgba(209, 206, 206, 0.5); */\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        #pro_list1_2>#pro_list1_2_detail, #pro_list1_4>#pro_list1_4_detail, #pro_list1_6>#pro_list1_6_detail{ \r\n");
      out.write("            height: 80px;\r\n");
      out.write("            /*border: 1px solid rgba(209, 206, 206, 0.5); */\r\n");
      out.write("            text-align:right;\r\n");
      out.write("        }\r\n");
      out.write("        #pro_list2_2>#pro_list2_2_detail, #pro_list2_4>#pro_list2_4_detail, #pro_list2_6>#pro_list2_6_detail{ \r\n");
      out.write("            height: 80px;\r\n");
      out.write("           /* border: 1px solid rgba(209, 206, 206, 0.5); */\r\n");
      out.write("            text-align:right;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        #pro_paging{\r\n");
      out.write("        	width:400px;\r\n");
      out.write("            margin: auto;\r\n");
      out.write("            margin-top: 50px;\r\n");
      out.write("        	margin-bottom: 50px;\r\n");
      out.write("        }\r\n");
      out.write("		#pro_list1_2:hover, #pro_list1_4:hover, #pro_list1_6:hover, #pro_list2_2:hover, #pro_list2_4:hover, #pro_list2_6:hover{\r\n");
      out.write("			opacity:0.5;\r\n");
      out.write("			cursor:pointer;\r\n");
      out.write("		}\r\n");
      out.write("	\r\n");
      out.write("    </style>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("\r\n");
 	String contextPath = request.getContextPath();
	Member loginUser = (Member)session.getAttribute("loginUser");
	String alertMsg = (String)session.getAttribute("alertMsg");

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"en\">\r\n");
      out.write("<head>\r\n");
      out.write("    <meta charset=\"UTF-8\">\r\n");
      out.write("    <meta http-equiv=\"X-UA-Compatible\" content=\"IE=edge\">\r\n");
      out.write("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\r\n");
      out.write("    <title>NUTRIENTS ALMIGHTY</title>\r\n");
      out.write("    <script src=\"https://ajax.googleapis.com/ajax/libs/jquery/3.6.0/jquery.min.js\"></script>\r\n");
      out.write("    <link rel=\"preconnect\" href=\"https://fonts.googleapis.com\">\r\n");
      out.write("    <link rel=\"preconnect\" href=\"https://fonts.gstatic.com\" crossorigin>\r\n");
      out.write("    <link href=\"https://fonts.googleapis.com/css2?family=Noto+Sans+KR:wght@400&display=swap\" rel=\"stylesheet\">\r\n");
      out.write("\r\n");
      out.write("    <style>\r\n");
      out.write("      div{\r\n");
      out.write("          box-sizing: border-box;\r\n");
      out.write("          /* border: 1px solid red; */\r\n");
      out.write("          /*가이드라인 */\r\n");
      out.write("      }\r\n");
      out.write("\r\n");
      out.write("      /* 크게 네가지 영역 */\r\n");
      out.write("       /* .wrap>div{ width: 100%; } */\r\n");
      out.write("\r\n");
      out.write("       #header,#footer{\r\n");
      out.write("            height: 205px;\r\n");
      out.write("            width:1000px;\r\n");
      out.write("            margin:auto;\r\n");
      out.write("        }\r\n");
      out.write("       #navigator { height: 41px;  font-family: 'Noto Sans KR', sans-serif; width: 1000px; margin:auto;}\r\n");
      out.write("\r\n");
      out.write("       /* 각각의 상세 영역 */\r\n");
      out.write("       #header>div{\r\n");
      out.write("           height: 100%;\r\n");
      out.write("           float: left;\r\n");
      out.write("       }\r\n");
      out.write("\r\n");
      out.write("       #header_1{ width: 15%;}\r\n");
      out.write("       #header_2{ width: 70%;}\r\n");
      out.write("       #header_3{ width: 15%;}\r\n");
      out.write("       \r\n");
      out.write("\r\n");
      out.write("       #footer{\r\n");
      out.write("          width: 1000px;\r\n");
      out.write("          height: 200px;  \r\n");
      out.write("      }\r\n");
      out.write("       \r\n");
      out.write("       #icon1{height: 20%;}\r\n");
      out.write("       #icon2{height: 20%;}\r\n");
      out.write("       #icon3{height: 0%;}\r\n");
      out.write("\r\n");
      out.write("      /*1.로고 스타일*/\r\n");
      out.write("      #header_2{\r\n");
      out.write("          position: relative;\r\n");
      out.write("      }\r\n");
      out.write("      #logo{\r\n");
      out.write("          margin: auto;\r\n");
      out.write("          position: absolute;\r\n");
      out.write("          top: 0px;\r\n");
      out.write("          bottom: 0px;\r\n");
      out.write("          left: 0px;    \r\n");
      out.write("          right: 0px;\r\n");
      out.write("      }\r\n");
      out.write("        /*3.메뉴바 */\r\n");
      out.write("         /* #navi에 대한 스타일 적용 */\r\n");
      out.write("         #navi{\r\n");
      out.write("          /* border: 1px solid blue; */\r\n");
      out.write("           list-style-type: none;\r\n");
      out.write("           text-align: center;\r\n");
      out.write("           margin: auto; \r\n");
      out.write("           padding: 0px;\r\n");
      out.write("           background-color: rgba(24,189,234, 0.5);\r\n");
      out.write("           height: 100%;\r\n");
      out.write("       }\r\n");
      out.write("       /* 메인메뉴에 대한 스타일 적용*/\r\n");
      out.write("       #navi>li {\r\n");
      out.write("          /* border: 1px solid green; */\r\n");
      out.write("           display:inline-block;\r\n");
      out.write("           width: 15%;\r\n");
      out.write("           height: 100%;\r\n");
      out.write("           text-align: center;\r\n");
      out.write("       }\r\n");
      out.write("\r\n");
      out.write("       /* 공통적인 메뉴 글씨에 대해서 스타일 적용 */\r\n");
      out.write("       #navi a { /*a태그는 인라인 요소 */\r\n");
      out.write("          /*  border: 1px solid blue; */\r\n");
      out.write("           text-decoration: none;\r\n");
      out.write("           color: white;\r\n");
      out.write("           font-size: 16px;\r\n");
      out.write("           font-weight: 900;\r\n");
      out.write("           width: 100%;\r\n");
      out.write("           height: 100%;\r\n");
      out.write("           display : block;\r\n");
      out.write("           line-height: 35px;   \r\n");
      out.write("       }\r\n");
      out.write("       #navi a:hover{\r\n");
      out.write("           color: steelblue;\r\n");
      out.write("           font-size: 18px;\r\n");
      out.write("           transform : scale(1); /* 1배 확대 */\r\n");
      out.write("       }\r\n");
      out.write("       /* 서브메뉴에 대한 스타일 적용*/\r\n");
      out.write("       #navi>li>ul{\r\n");
      out.write("           list-style-type: none;\r\n");
      out.write("           padding: 0px;\r\n");
      out.write("           display: none; \r\n");
      out.write("       }\r\n");
      out.write("       #navi>li>a:hover+ul {\r\n");
      out.write("           display: block; \r\n");
      out.write("       }\r\n");
      out.write("       #navi>li>ul:hover{\r\n");
      out.write("           display: block; \r\n");
      out.write("       }\r\n");
      out.write("\r\n");
      out.write("       /* 서브메뉴 글씨 조절 */\r\n");
      out.write("       #navi>li>ul a { font-size: 10px; }\r\n");
      out.write("       #navi>li>ul a:hover{ font-size: 13px;} \r\n");
      out.write("\r\n");
      out.write("       /*오른쪽에 장바구니, 로그인 아이콘*/\r\n");
      out.write("       #icon1, #icon2{\r\n");
      out.write("           width: 19%;\r\n");
      out.write("           height: 14%;\r\n");
      out.write("           display: inline-block;\r\n");
      out.write("           float: right;\r\n");
      out.write("           margin-top: 20px;\r\n");
      out.write("           margin-right: 15px;\r\n");
      out.write("       }\r\n");
      out.write("       #cart_icon>img, #login_icon>img{\r\n");
      out.write("           width: 100%;\r\n");
      out.write("           height: 100%;\r\n");
      out.write("           float: right;\r\n");
      out.write("       }\r\n");
      out.write("\r\n");
      out.write("        /* footer상세 영역 */\r\n");
      out.write("     #footer>table{\r\n");
      out.write("        margin: auto;\r\n");
      out.write("        margin-top: 5px;\r\n");
      out.write("     }\r\n");
      out.write("      #ft1 {\r\n");
      out.write("          float: left;\r\n");
      out.write("          margin-right: 320px;\r\n");
      out.write("      }\r\n");
      out.write("      #ft1>a{\r\n");
      out.write("        padding: 0px;\r\n");
      out.write("        margin: 0px;\r\n");
      out.write("      }\r\n");
      out.write("      #ft2 {\r\n");
      out.write("        float: right; \r\n");
      out.write("      }\r\n");
      out.write("      #ft3 {\r\n");
      out.write("        font-family: 'Noto Sans KR', sans-serif;\r\n");
      out.write("          float: left;\r\n");
      out.write("          font-size: 10px;\r\n");
      out.write("      }\r\n");
      out.write("      #ft4 {\r\n");
      out.write("         font-family: 'Noto Sans KR', sans-serif;\r\n");
      out.write("          font-size: 10px;\r\n");
      out.write("          text-align: right;\r\n");
      out.write("          float: right; \r\n");
      out.write("          margin-left: auto;\r\n");
      out.write("      }\r\n");
      out.write("      #ft1>a, #ft2>a {\r\n");
      out.write("        font-family: 'Noto Sans KR', sans-serif;\r\n");
      out.write("          text-decoration: none;\r\n");
      out.write("          color: black;\r\n");
      out.write("          font-size: 110%;\r\n");
      out.write("          font-weight: 600;\r\n");
      out.write("          margin: 15px;     \r\n");
      out.write("          vertical-align: middle; \r\n");
      out.write("      }\r\n");
      out.write("\r\n");
      out.write("      #ft5{\r\n");
      out.write("        font-size: 10px;\r\n");
      out.write("        font-family: 'Noto Sans KR', sans-serif;\r\n");
      out.write("        color: rgba(73, 71, 71, 0.5);\r\n");
      out.write("      }\r\n");
      out.write("\r\n");
      out.write("      #ft5{\r\n");
      out.write("        text-align: right;\r\n");
      out.write("      }\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("    </style>\r\n");
      out.write("<script src=\"https://ajax.googleapis.com/ajax/libs/jquery/3.6.0/jquery.min.js\"></script>\r\n");
      out.write("\r\n");
      out.write("<!-- Latest compiled and minified CSS -->\r\n");
      out.write("<link rel=\"stylesheet\" href=\"https://cdn.jsdelivr.net/npm/bootstrap@4.6.1/dist/css/bootstrap.min.css\">\r\n");
      out.write("\r\n");
      out.write("<!-- Popper JS -->\r\n");
      out.write("<script src=\"https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js\"></script>\r\n");
      out.write("\r\n");
      out.write("<!-- Latest compiled JavaScript -->\r\n");
      out.write("<script src=\"https://cdn.jsdelivr.net/npm/bootstrap@4.6.1/dist/js/bootstrap.bundle.min.js\"></script>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("	<script>\r\n");
      out.write("		var msg = \"");
      out.print(alertMsg);
      out.write("\"; // \"성공적으로 로그인이 되었습니다.\" / \"null\"\r\n");
      out.write("		if(msg != \"null\") {\r\n");
      out.write("			alert(msg);\r\n");
      out.write("			// 알림창 띄우며 해당 세션의 해당 키-밸류를 지워줘야 연속해서 안뜬다.\r\n");
      out.write("			");
 session.removeAttribute("alertMsg"); 
      out.write("\r\n");
      out.write("		}\r\n");
      out.write("	</script>		\r\n");
      out.write("		\r\n");
      out.write("       <div id=\"header\">\r\n");
      out.write("           <div id=\"header_1\"></div>\r\n");
      out.write("           <div id=\"header_2\">\r\n");
      out.write("            <a href=\"");
      out.print(contextPath);
      out.write("\" target=\"_self\">\r\n");
      out.write("                <img src=\"/na/resources/image/상호이미지.png\" id=\"logo\">\r\n");
      out.write("            </a>\r\n");
      out.write("           </div>\r\n");
      out.write("           <div id=\"header_3\">\r\n");
      out.write("               <div id=\"icon1\">\r\n");
      out.write("                    <a id=\"cart_icon\" href=\"");
      out.print(contextPath );
      out.write("/mainMycart.my\" target=\"\">\r\n");
      out.write("                      <img src=\"/na/resources/image/장바구니.png\">\r\n");
      out.write("                     </a>\r\n");
      out.write("                   </div>        \r\n");
      out.write("                <div id=\"icon2\">\r\n");
      out.write("                ");
 if (loginUser == null){ 
      out.write("\r\n");
      out.write("                    <a id=\"login_icon\" href=\"");
      out.print(contextPath);
      out.write("/beforeLog.me\" >\r\n");
      out.write("                        <img src=\"/na/resources/image/로그인.png\">\r\n");
      out.write("                    </a>\r\n");
      out.write("                ");
 } 
      out.write("\r\n");
      out.write("               </div>\r\n");
      out.write("               <div id=\"icon3\"></div>\r\n");
      out.write("           </div>\r\n");
      out.write("       </div>\r\n");
      out.write("       <div id=\"navigator\">\r\n");
      out.write("        <ul id=\"navi\">\r\n");
      out.write("            <li><a href=\"");
      out.print(contextPath);
      out.write("/proList.pr?currentPage=1\">제품보기</a></li>\r\n");
      out.write("            <li><a href=\"");
      out.print(contextPath);
      out.write("/list.mg?currentPage=1\">건강매거진</a></li>\r\n");
      out.write("            <li>\r\n");
      out.write("                <a href=\"");
      out.print(contextPath);
      out.write("/reviewlist.re?currentPage=1\">고객후기</a>\r\n");
      out.write("            </li>\r\n");
      out.write("            <li>\r\n");
      out.write("                <a href=\"");
      out.print(contextPath);
      out.write("/noticeList.no?currentPage=1\">고객센터</a>\r\n");
      out.write("            </li>\r\n");
      out.write("        </ul>\r\n");
      out.write("       </div> \r\n");
      out.write("\r\n");
      out.write("    \r\n");
      out.write("    \r\n");
      out.write("    <!-- <div id=\"footer\">\r\n");
      out.write("        <table>\r\n");
      out.write("            <tr>\r\n");
      out.write("                <td><hr style=\"border: solid 0.5px rgba(73, 71, 71, 0.1)\"></td>\r\n");
      out.write("            </tr>\r\n");
      out.write("            <tr>\r\n");
      out.write("                <td id=\"ft1\">\r\n");
      out.write("                   <a href=\"\" >이용약관</a>  |\r\n");
      out.write("                   <a href=\"\" >개인정보취급방침</a>  \r\n");
      out.write("                </td>\r\n");
      out.write("                <td id=\"ft2\">\r\n");
      out.write("                   <a href=\"\">고객센터</a>\r\n");
      out.write("                </td>\r\n");
      out.write("            </tr>\r\n");
      out.write("           <tr>\r\n");
      out.write("               <td>&nbsp;</td>\r\n");
      out.write("           </tr>\r\n");
      out.write("           <tr>\r\n");
      out.write("               <td id=\"ft3\">\r\n");
      out.write("                   (주)건강이내게5조 <br>\r\n");
      out.write("                   사업자번호: 768-34-333445 <br>\r\n");
      out.write("                   대표 : 한세인  <br>\r\n");
      out.write("                   주소 : 서울특별시 영등포구 당산동 <br>\r\n");
      out.write("                   유통판매신고 : 제 2333-330000 <br>\r\n");
      out.write("               </td>\r\n");
      out.write("               <td id=\"ft4\">\r\n");
      out.write("                  고객센터: sein151@naver.com <br>\r\n");
      out.write("                  전화 : 02-1588-3333 <br>\r\n");
      out.write("                  상담시간 : 평일 10:00 ~18:00 (점심시간 : 12:00~13:00) <br>\r\n");
      out.write("                  비지니스 문의 : sein151@naver.com\r\n");
      out.write("               </td>\r\n");
      out.write("           </tr>\r\n");
      out.write("           <tr>\r\n");
      out.write("               <td id=\"ft5\">\r\n");
      out.write("                    @content by all right\r\n");
      out.write("               </td>\r\n");
      out.write("           </tr>\r\n");
      out.write("        </table>\r\n");
      out.write("        <br><br>\r\n");
      out.write("       </div> -->\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
      out.write("\r\n");
      out.write("\r\n");
      out.write("      <!--content의 body영역-->\r\n");
      out.write("       <div class=\"content\">\r\n");
      out.write("            <!--검색정렬-->\r\n");
      out.write("            <div id=\"search\">\r\n");
      out.write("               <form id=\"search_form\" action=\"proSearch.pr\" method=\"get\">\r\n");
      out.write("                <div id=\"search_1\">\r\n");
      out.write("                    <h2 style=\"color:rgba(36, 49, 121, 0.9);\">상품검색</h2>\r\n");
      out.write("                    <hr>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div id=\"search_2\">\r\n");
      out.write("                    <div id=\"search_2_1\"></div>\r\n");
      out.write("                    <div id=\"search_2_2\">\r\n");
      out.write("                        <input type=\"text\" name=\"keyword\" placeholder=\"검색할 키워드를 입력해주세요.\" style=\"height: 36px;\" maxlength=\"20\">\r\n");
      out.write("                        <input type=\"hidden\" name=\"currentPage\" value=\"1\">\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div id=\"search_2_3\">\r\n");
      out.write("                        <input type=\"submit\" class=\"btn btn-light\" value=\"검색\" style=\"color:white; background-color:rgba(24,189,234, 0.5)\">\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div id=\"search_2_4\"></div>\r\n");
      out.write("                </div>\r\n");
      out.write("                </form>\r\n");
      out.write("                <!-- 상품 카테고리 선택 테이블 -->\r\n");
      out.write("                <form action=\"proSearch2.pr\" method=\"get\">\r\n");
      out.write("                <input type=\"hidden\" name=\"currentPage\" value=\"1\">                \r\n");
      out.write("                <div id=\"search_3\">\r\n");
      out.write("                    <table id=\"cat_t\" style=\"border:2px solid rgba(209, 206, 206, 0.5)\">\r\n");
      out.write("                        <tr>\r\n");
      out.write("                            <th style=\"background-color:rgba(24,189,234, 0.5)\">효능</th>\r\n");
      out.write("                            <td><input type=\"radio\" name=\"s1\" value=\"혈액개선\" checked> 혈액개선</td>\r\n");
      out.write("                            <td><input type=\"radio\" name=\"s1\" value=\"시력개선\"> 시력개선</td>\r\n");
      out.write("                            <td><input type=\"radio\" name=\"s1\" value=\"면역력증진\"> 면역력증진</td>\r\n");
      out.write("                            <td><input type=\"radio\" name=\"s1\" value=\"에너지충전\"> 에너지충전</td>\r\n");
      out.write("                            <td><input type=\"radio\" name=\"s1\" value=\"간기능개선\"> 간기능개선</td>\r\n");
      out.write("                            <td></td>\r\n");
      out.write("                        </tr>\r\n");
      out.write("                        <tr style=\"border-bottom:2px solid rgba(209, 206, 206, 0.5);\">\r\n");
      out.write("                            <th style=\"background-color:rgba(24,189,234, 0.5)\"></th>\r\n");
      out.write("                            <td><input type=\"radio\" name=\"s1\" value=\"배변활동\"> 배변활동</td>\r\n");
      out.write("                            <td><input type=\"radio\" name=\"s1\" value=\"피부건강\"> 피부건강</td>\r\n");
      out.write("                            <td></td>\r\n");
      out.write("                            <td></td>\r\n");
      out.write("                            <td></td>\r\n");
      out.write("                            <td></td>\r\n");
      out.write("                        </tr>\r\n");
      out.write("                        <tr>\r\n");
      out.write("                            <th style=\"background-color:rgba(24,189,234, 0.5)\">가격</th>\r\n");
      out.write("                            <td><input type=\"radio\" name=\"s2\" style=\"width:17px;\" value=\"1\" checked> 1~3만원</td>\r\n");
      out.write("                            <td><input type=\"radio\" name=\"s2\" style=\"width:20px;\" value=\"2\"> 3~5만원</td>\r\n");
      out.write("                            <td><input type=\"radio\" name=\"s2\" style=\"width:45px;\" value=\"3\"> 5~7만원</td>\r\n");
      out.write("                            <td><input type=\"radio\" name=\"s2\" style=\"width:30px;\" value=\"4\"> 7~10만원</td>\r\n");
      out.write("                            <td colspan=\"2\" style=\"padding-left:1px; width:00px;\"> </td>\r\n");
      out.write("\r\n");
      out.write("                        </tr>\r\n");
      out.write("                        <!-- 조회버튼 추가와 가격앞에 라디오박스, hr 둘중 하나 제거하고 페이징바 추가, 제품명 효능 가격 보더 색 옅게(hr색으로)\r\n");
      out.write("                              -->\r\n");
      out.write("                    </table>\r\n");
      out.write("                    <div style=\"margin-left:750px; margin-top:25px;\">\r\n");
      out.write("                        <input type=\"submit\" class=\"btn btn-light\" value=\"조회\"\r\n");
      out.write("                        style=\"color:white; width:100px; \r\n");
      out.write("                        background-color:rgba(24,189,234, 0.5);\"></div>\r\n");
      out.write("                </div>\r\n");
      out.write("                \r\n");
      out.write("                </form>\r\n");
      out.write("            </div>\r\n");
      out.write("            <hr>\r\n");
      out.write("            <!--상품리스트정렬(orderby)-->\r\n");
      out.write("            <div id=\"pro_orderby\">\r\n");
      out.write("                <div>\r\n");
      out.write("                <a href=\"");
      out.print(contextPath);
      out.write("/proList.pr?currentPage=1\">신상품순  |  </a>\r\n");
      out.write("                <a href=\"");
      out.print(contextPath);
      out.write("/proList2.pr?currentPage=1\">높은가격순  |  </a>\r\n");
      out.write("                <a href=\"");
      out.print(contextPath);
      out.write("/proList3.pr?currentPage=1\">낮은가격순 </a>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("\r\n");
      out.write("            <br>\r\n");
      out.write("            <!--상품리스트view1-->\r\n");
      out.write("            <div id=\"pro_list1\">\r\n");
      out.write("                <div id=\"pro_list1_1\"></div>\r\n");
      out.write("                <div id=\"pro_list1_2\"");
if(list.size()>0){ 
      out.write(" onclick=\"location.href='/na/proDetail.pr?pno=");
      out.print(list.get(0).getProNo());
}
      out.write("'\">\r\n");
      out.write("                    <div id=\"pro_list1_2_img\">\r\n");
      out.write("                        <img src=\"");
if(list.size()>0){ 
      out.print(list.get(0).getProImgPath());
}
      out.write("\" onerror=\"this.style.display='none';\" />\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div id=\"pro_list1_2_detail\" style=\"padding-right:15px;\">");
if(list.size()>0){ 
      out.print(list.get(0).getProName() );
}
      out.write("<br>\r\n");
      out.write("                    <span style=\"color:gray;\">");
if(list.size()>0){ 
      out.print(list.get(0).getProEff() );
}
      out.write("</span><br>\r\n");
      out.write("                    ");
if(list.size()>0){ 
      out.print(list.get(0).getPrice()+" 원" );
}else{
}
      out.write("\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div id=\"pro_list1_3\"></div>\r\n");
      out.write("                <div id=\"pro_list1_4\"");
if(list.size()>1){ 
      out.write(" onclick=\"location.href='/na/proDetail.pr?pno=");
      out.print(list.get(1).getProNo());
}
      out.write("'\">\r\n");
      out.write("                    <div id=\"pro_list1_4_img\">\r\n");
      out.write("                        <img src=\"");
if(list.size()>1){ 
      out.print(list.get(1).getProImgPath());
}
      out.write("\" onerror=\"this.style.display='none';\" />\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div id=\"pro_list1_4_detail\" style=\"padding-right:15px;\">");
if(list.size()>1){ 
      out.print(list.get(1).getProName() );
}
      out.write("<br>\r\n");
      out.write("                    <span style=\"color:gray;\">");
if(list.size()>1){ 
      out.print(list.get(1).getProEff() );
}
      out.write("</span><br>\r\n");
      out.write("                    ");
if(list.size()>1){ 
      out.print(list.get(1).getPrice()+" 원" );
}else{
}
      out.write("</div>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div id=\"pro_list1_5\"></div>\r\n");
      out.write("                <div id=\"pro_list1_6\"");
if(list.size()>2){ 
      out.write(" onclick=\"location.href='/na/proDetail.pr?pno=");
      out.print(list.get(2).getProNo());
}
      out.write("'\">\r\n");
      out.write("                    <div id=\"pro_list1_6_img\">\r\n");
      out.write("                        <img src=\"");
if(list.size()>2){ 
      out.print(list.get(2).getProImgPath());
}
      out.write("\" onerror=\"this.style.display='none';\" />\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div id=\"pro_list1_6_detail\" style=\"padding-right:15px;\">");
if(list.size()>2){ 
      out.print(list.get(2).getProName() );
}
      out.write("<br>\r\n");
      out.write("                    <span style=\"color:gray;\">");
if(list.size()>2){ 
      out.print(list.get(2).getProEff() );
}
      out.write("</span><br>\r\n");
      out.write("                    ");
if(list.size()>2){ 
      out.print(list.get(2).getPrice()+" 원" );
}else{
}
      out.write("</div>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div id=\"pro_list1_7\"></div>\r\n");
      out.write("            </div>\r\n");
      out.write("\r\n");
      out.write("            <br>\r\n");
      out.write("            <!--상품리스트view2-->\r\n");
      out.write("            <div id=\"pro_list2\">\r\n");
      out.write("                <div id=\"pro_list2_1\"></div>\r\n");
      out.write("                <div id=\"pro_list2_2\"");
if(list.size()>3){ 
      out.write(" onclick=\"location.href='/na/proDetail.pr?pno=");
      out.print(list.get(3).getProNo());
}
      out.write("'\">\r\n");
      out.write("                    <div id=\"pro_list2_2_img\">\r\n");
      out.write("                        <img src=\"");
if(list.size()>3){ 
      out.print(list.get(3).getProImgPath());
}
      out.write("\" onerror=\"this.style.display='none';\" />\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div id=\"pro_list2_2_detail\" style=\"padding-right:15px;\">");
if(list.size()>3){ 
      out.print(list.get(3).getProName() );
}
      out.write("<br>\r\n");
      out.write("                    <span style=\"color:gray;\">");
if(list.size()>3){ 
      out.print(list.get(3).getProEff() );
}
      out.write("</span><br>\r\n");
      out.write("                    ");
if(list.size()>3){ 
      out.print(list.get(3).getPrice()+" 원" );
}else{
}
      out.write("</div>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div id=\"pro_list2_3\"></div>\r\n");
      out.write("                <div id=\"pro_list2_4\"");
if(list.size()>4){ 
      out.write(" onclick=\"location.href='/na/proDetail.pr?pno=");
      out.print(list.get(4).getProNo());
}
      out.write("'\">\r\n");
      out.write("                    <div id=\"pro_list2_4_img\">\r\n");
      out.write("                        <img src=\"");
if(list.size()>4){ 
      out.print(list.get(4).getProImgPath());
}
      out.write("\" onerror=\"this.style.display='none';\" />\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div id=\"pro_list2_4_detail\" style=\"padding-right:15px;\">");
if(list.size()>4){ 
      out.print(list.get(4).getProName() );
}
      out.write("<br>\r\n");
      out.write("                    <span style=\"color:gray;\">");
if(list.size()>4){ 
      out.print(list.get(4).getProEff() );
}
      out.write("</span><br>\r\n");
      out.write("                    ");
if(list.size()>4){ 
      out.print(list.get(4).getPrice()+" 원" );
}else{
}
      out.write("</div>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div id=\"pro_list2_5\"></div>\r\n");
      out.write("                <div id=\"pro_list2_6\"");
if(list.size()>5){ 
      out.write(" onclick=\"location.href='/na/proDetail.pr?pno=");
      out.print(list.get(5).getProNo());
}
      out.write("'\">\r\n");
      out.write("                    <div id=\"pro_list2_6_img\">\r\n");
      out.write("                        <img src=\"");
if(list.size()>5){ 
      out.print(list.get(5).getProImgPath());
}
      out.write("\" onerror=\"this.style.display='none';\" />\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div id=\"pro_list2_6_detail\" style=\"padding-right:15px;\">");
if(list.size()>5){ 
      out.print(list.get(5).getProName() );
}
      out.write("<br>\r\n");
      out.write("                    <span style=\"color:gray;\">");
if(list.size()>5){ 
      out.print(list.get(5).getProEff() );
}
      out.write("</span><br>\r\n");
      out.write("                    ");
if(list.size()>5){ 
      out.print(list.get(5).getPrice()+" 원" );
}else{
}
      out.write("</div>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div id=\"pro_list2_7\"></div>\r\n");
      out.write("            </div>\r\n");
      out.write("            \r\n");
      out.write("            <br clear=\"both\">\r\n");
      out.write("            <!--페이징 영역-->\r\n");
      out.write("            \r\n");
      out.write("            <div id=\"pro_paging\" class=\"page_nation\">\r\n");
      out.write("            ");
if(list.size()!=0){ 
      out.write(" \r\n");
      out.write("                <ul class=\"pagination\">\r\n");
      out.write("            ");
if(currentPage==1){ 
      out.write("\r\n");
      out.write("            ");
}else{ 
      out.write("            \r\n");
      out.write("                    <li class=\"page-item\"><a class=\"page-link\" href=\"");
      out.print(contextPath);
      out.write("/proList.pr?currentPage=");
      out.print(currentPage - 1);
      out.write("\" style=\"color: black\"><</a></li>\r\n");
      out.write("            ");
} 
      out.write("\r\n");
      out.write("			");
for(int p = startPage; p<=endPage; p++){ 
      out.write("\r\n");
      out.write("				");
if(p!=currentPage){ 
      out.write("            \r\n");
      out.write("                    <li class=\"page-item\"><a class=\"page-link\" href=\"");
      out.print(contextPath);
      out.write("/proList.pr?currentPage=");
      out.print(p);
      out.write("\" style=\"color: black\">");
      out.print(p );
      out.write("</a></li>\r\n");
      out.write("			");
} else {
      out.write("     \r\n");
      out.write("                    <li class=\"page-item\"><a class=\"page-link\" href=\"\" style=\"color: black\">");
      out.print(p );
      out.write("</a></li>\r\n");
      out.write("				");
}} 
      out.write("      \r\n");
      out.write("            ");
if(currentPage==maxPage || maxPage==0){ 
      out.write("\r\n");
      out.write("            ");
}else{ 
      out.write("				              			               \r\n");
      out.write("                    <li class=\"page-item\"><a class=\"page-link\" href=\"");
      out.print(contextPath);
      out.write("/proList.pr?currentPage=");
      out.print(currentPage + 1);
      out.write("\" style=\"color: black\">></a></li>\r\n");
      out.write("            ");
} 
      out.write("                    \r\n");
      out.write("                    </ul>\r\n");
      out.write("            ");
} 
      out.write("\r\n");
      out.write("            </div>\r\n");
      out.write("     </div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"en\">\r\n");
      out.write("<head>\r\n");
      out.write("    <meta charset=\"UTF-8\">\r\n");
      out.write("    <meta http-equiv=\"X-UA-Compatible\" content=\"IE=edge\">\r\n");
      out.write("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\r\n");
      out.write("    <title>NUTRIENTS ALMIGHTY</title>\r\n");
      out.write("    <script src=\"https://ajax.googleapis.com/ajax/libs/jquery/3.6.0/jquery.min.js\"></script>\r\n");
      out.write("    <link rel=\"preconnect\" href=\"https://fonts.googleapis.com\">\r\n");
      out.write("    <link rel=\"preconnect\" href=\"https://fonts.gstatic.com\" crossorigin>\r\n");
      out.write("    <link href=\"https://fonts.googleapis.com/css2?family=Noto+Sans+KR:wght@400&display=swap\" rel=\"stylesheet\">\r\n");
      out.write("\r\n");
      out.write("    <style>\r\n");
      out.write("      div{\r\n");
      out.write("          box-sizing: border-box;\r\n");
      out.write("          /* border: 1px solid red; */\r\n");
      out.write("          /*가이드라인 */\r\n");
      out.write("      }\r\n");
      out.write("\r\n");
      out.write("      /* 크게 네가지 영역 */\r\n");
      out.write("       /* .wrap>div{ width: 100%; } */\r\n");
      out.write("\r\n");
      out.write("       #header,#footer{\r\n");
      out.write("            height: 205px;\r\n");
      out.write("            width:1000px;\r\n");
      out.write("            margin:auto;\r\n");
      out.write("        }\r\n");
      out.write("       #navigator { height: 41px;  font-family: 'Noto Sans KR', sans-serif; width: 1000px; margin:auto;}\r\n");
      out.write("\r\n");
      out.write("       /* 각각의 상세 영역 */\r\n");
      out.write("       #header>div{\r\n");
      out.write("           height: 100%;\r\n");
      out.write("           float: left;\r\n");
      out.write("       }\r\n");
      out.write("\r\n");
      out.write("       #header_1{ width: 15%;}\r\n");
      out.write("       #header_2{ width: 70%;}\r\n");
      out.write("       #header_3{ width: 15%;}\r\n");
      out.write("       \r\n");
      out.write("\r\n");
      out.write("       #footer{\r\n");
      out.write("          width: 1000px;\r\n");
      out.write("          height: 200px;  \r\n");
      out.write("      }\r\n");
      out.write("       \r\n");
      out.write("       #icon1{height: 20%;}\r\n");
      out.write("       #icon2{height: 20%;}\r\n");
      out.write("       #icon3{height: 0%;}\r\n");
      out.write("\r\n");
      out.write("      /*1.로고 스타일*/\r\n");
      out.write("      #header_2{\r\n");
      out.write("          position: relative;\r\n");
      out.write("      }\r\n");
      out.write("      #logo{\r\n");
      out.write("          margin: auto;\r\n");
      out.write("          position: absolute;\r\n");
      out.write("          top: 0px;\r\n");
      out.write("          bottom: 0px;\r\n");
      out.write("          left: 0px;    \r\n");
      out.write("          right: 0px;\r\n");
      out.write("      }\r\n");
      out.write("        /*3.메뉴바 */\r\n");
      out.write("         /* #navi에 대한 스타일 적용 */\r\n");
      out.write("         #navi{\r\n");
      out.write("          /* border: 1px solid blue; */\r\n");
      out.write("           list-style-type: none;\r\n");
      out.write("           text-align: center;\r\n");
      out.write("           margin: auto; \r\n");
      out.write("           padding: 0px;\r\n");
      out.write("           background-color: rgba(24,189,234, 0.5);\r\n");
      out.write("           height: 100%;\r\n");
      out.write("       }\r\n");
      out.write("       /* 메인메뉴에 대한 스타일 적용*/\r\n");
      out.write("       #navi>li {\r\n");
      out.write("          /* border: 1px solid green; */\r\n");
      out.write("           display:inline-block;\r\n");
      out.write("           width: 15%;\r\n");
      out.write("           height: 100%;\r\n");
      out.write("           text-align: center;\r\n");
      out.write("       }\r\n");
      out.write("\r\n");
      out.write("       /* 공통적인 메뉴 글씨에 대해서 스타일 적용 */\r\n");
      out.write("       #navi a { /*a태그는 인라인 요소 */\r\n");
      out.write("          /*  border: 1px solid blue; */\r\n");
      out.write("           text-decoration: none;\r\n");
      out.write("           color: white;\r\n");
      out.write("           font-size: 16px;\r\n");
      out.write("           font-weight: 900;\r\n");
      out.write("           width: 100%;\r\n");
      out.write("           height: 100%;\r\n");
      out.write("           display : block;\r\n");
      out.write("           line-height: 35px;   \r\n");
      out.write("       }\r\n");
      out.write("       #navi a:hover{\r\n");
      out.write("           color: steelblue;\r\n");
      out.write("           font-size: 18px;\r\n");
      out.write("           transform : scale(1); /* 1배 확대 */\r\n");
      out.write("       }\r\n");
      out.write("       /* 서브메뉴에 대한 스타일 적용*/\r\n");
      out.write("       #navi>li>ul{\r\n");
      out.write("           list-style-type: none;\r\n");
      out.write("           padding: 0px;\r\n");
      out.write("           display: none; \r\n");
      out.write("       }\r\n");
      out.write("       #navi>li>a:hover+ul {\r\n");
      out.write("           display: block; \r\n");
      out.write("       }\r\n");
      out.write("       #navi>li>ul:hover{\r\n");
      out.write("           display: block; \r\n");
      out.write("       }\r\n");
      out.write("\r\n");
      out.write("       /* 서브메뉴 글씨 조절 */\r\n");
      out.write("       #navi>li>ul a { font-size: 10px; }\r\n");
      out.write("       #navi>li>ul a:hover{ font-size: 13px;} \r\n");
      out.write("\r\n");
      out.write("       /*오른쪽에 장바구니, 로그인 아이콘*/\r\n");
      out.write("       #icon1, #icon2{\r\n");
      out.write("           width: 19%;\r\n");
      out.write("           height: 14%;\r\n");
      out.write("           display: inline-block;\r\n");
      out.write("           float: right;\r\n");
      out.write("           margin-top: 20px;\r\n");
      out.write("           margin-right: 15px;\r\n");
      out.write("       }\r\n");
      out.write("       #cart_icon>img, #login_icon>img{\r\n");
      out.write("           width: 100%;\r\n");
      out.write("           height: 100%;\r\n");
      out.write("           float: right;\r\n");
      out.write("       }\r\n");
      out.write("\r\n");
      out.write("        /* footer상세 영역 */\r\n");
      out.write("     #footer>table{\r\n");
      out.write("     width:100%;\r\n");
      out.write("        margin: auto;\r\n");
      out.write("        margin-top: 5px;\r\n");
      out.write("     }\r\n");
      out.write("      #ft1 {\r\n");
      out.write("          float: left;\r\n");
      out.write("          margin-right: 320px;\r\n");
      out.write("      }\r\n");
      out.write("      #ft1>a{\r\n");
      out.write("        padding: 0px;\r\n");
      out.write("        margin: 0px;\r\n");
      out.write("      }\r\n");
      out.write("      #ft2 {\r\n");
      out.write("        float: right; \r\n");
      out.write("      }\r\n");
      out.write("      #ft3 {\r\n");
      out.write("        font-family: 'Noto Sans KR', sans-serif;\r\n");
      out.write("          float: left;\r\n");
      out.write("          font-size: 10px;\r\n");
      out.write("      }\r\n");
      out.write("      #ft4 {\r\n");
      out.write("         font-family: 'Noto Sans KR', sans-serif;\r\n");
      out.write("          font-size: 10px;\r\n");
      out.write("          text-align: right;\r\n");
      out.write("          float: right; \r\n");
      out.write("          margin-left: auto;\r\n");
      out.write("      }\r\n");
      out.write("      #ft1>a, #ft2>a {\r\n");
      out.write("        font-family: 'Noto Sans KR', sans-serif;\r\n");
      out.write("          text-decoration: none;\r\n");
      out.write("          color: black;\r\n");
      out.write("          font-size: 110%;\r\n");
      out.write("          font-weight: 600;\r\n");
      out.write("          margin: 15px;     \r\n");
      out.write("          vertical-align: middle; \r\n");
      out.write("      }\r\n");
      out.write("\r\n");
      out.write("      #ft5{\r\n");
      out.write("        font-size: 10px;\r\n");
      out.write("        font-family: 'Noto Sans KR', sans-serif;\r\n");
      out.write("        color: rgba(73, 71, 71, 0.5);\r\n");
      out.write("      }\r\n");
      out.write("\r\n");
      out.write("      #ft5{\r\n");
      out.write("        text-align: right;\r\n");
      out.write("      }\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("    </style>\r\n");
      out.write("<script src=\"https://ajax.googleapis.com/ajax/libs/jquery/3.6.0/jquery.min.js\"></script>\r\n");
      out.write("\r\n");
      out.write("<!-- Latest compiled and minified CSS -->\r\n");
      out.write("<link rel=\"stylesheet\" href=\"https://cdn.jsdelivr.net/npm/bootstrap@4.6.1/dist/css/bootstrap.min.css\">\r\n");
      out.write("\r\n");
      out.write("<!-- Popper JS -->\r\n");
      out.write("<script src=\"https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js\"></script>\r\n");
      out.write("\r\n");
      out.write("<!-- Latest compiled JavaScript -->\r\n");
      out.write("<script src=\"https://cdn.jsdelivr.net/npm/bootstrap@4.6.1/dist/js/bootstrap.bundle.min.js\"></script>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("       <!-- <div id=\"header\">\r\n");
      out.write("           <div id=\"header_1\"></div>\r\n");
      out.write("           <div id=\"header_2\">\r\n");
      out.write("            <a href=\"\" target=\"_self\">\r\n");
      out.write("                <img src=\"resources/image/상호이미지.png\" id=\"logo\">\r\n");
      out.write("            </a>\r\n");
      out.write("           </div>\r\n");
      out.write("           <div id=\"header_3\">\r\n");
      out.write("               <div id=\"icon1\">\r\n");
      out.write("                    <a id=\"cart_icon\" href=\"\" target=\"\">\r\n");
      out.write("                      <img src=\"resources/image/장바구니.png\">\r\n");
      out.write("                     </a>\r\n");
      out.write("                   </div>        \r\n");
      out.write("                <div id=\"icon2\">\r\n");
      out.write("                    <a id=\"login_icon\" href=\"\" >\r\n");
      out.write("                        <img src=\"resources/image/로그인.png\">\r\n");
      out.write("                    </a>\r\n");
      out.write("               </div>\r\n");
      out.write("               <div id=\"icon3\"></div>\r\n");
      out.write("           </div>\r\n");
      out.write("       </div>\r\n");
      out.write("       <div id=\"navigator\">\r\n");
      out.write("        <ul id=\"navi\">\r\n");
      out.write("            <li><a href=\"\">제품보기</a></li>\r\n");
      out.write("            <li><a href=\"\">건강매거진</a></li>\r\n");
      out.write("            <li>\r\n");
      out.write("                <a href=\"\">고객후기</a>\r\n");
      out.write("            </li>\r\n");
      out.write("            <li>\r\n");
      out.write("                <a href=\"\">고객센터</a>\r\n");
      out.write("            </li>\r\n");
      out.write("        </ul>\r\n");
      out.write("       </div>  -->\r\n");
      out.write("\r\n");
      out.write("    \r\n");
      out.write("    \r\n");
      out.write("    <div id=\"footer\">\r\n");
      out.write("        <table>\r\n");
      out.write("            <tr>\r\n");
      out.write("                <td><hr style=\"border: solid 0.5px rgba(73, 71, 71, 0.1)\"></td>\r\n");
      out.write("            </tr>\r\n");
      out.write("            <tr>\r\n");
      out.write("                <td id=\"ft1\">\r\n");
      out.write("                   <a href=\"/na/contract.in\" >이용약관</a>  |\r\n");
      out.write("                   <a href=\"/na/contract.in\" >개인정보취급방침</a>  \r\n");
      out.write("                </td>\r\n");
      out.write("                <td id=\"ft2\">\r\n");
      out.write("                   <a href=\"/na/noticeList.no?currentPage=1\">고객센터</a>\r\n");
      out.write("                </td>\r\n");
      out.write("            </tr>\r\n");
      out.write("           <tr>\r\n");
      out.write("               <td>&nbsp;</td>\r\n");
      out.write("           </tr>\r\n");
      out.write("           <tr>\r\n");
      out.write("               <td id=\"ft3\">\r\n");
      out.write("                   (주)건강이내게5조 <br>\r\n");
      out.write("                   사업자번호: 768-34-333445 <br>\r\n");
      out.write("                   대표 : 한세인  <br>\r\n");
      out.write("                   주소 : 서울특별시 영등포구 당산동 <br>\r\n");
      out.write("                   유통판매신고 : 제 2333-330000 <br>\r\n");
      out.write("               </td>\r\n");
      out.write("               <td id=\"ft4\">\r\n");
      out.write("                  고객센터: sein151@naver.com <br>\r\n");
      out.write("                  전화 : 02-1588-3333 <br>\r\n");
      out.write("                  상담시간 : 평일 10:00 ~18:00 (점심시간 : 12:00~13:00) <br>\r\n");
      out.write("                  비지니스 문의 : sein151@naver.com\r\n");
      out.write("               </td>\r\n");
      out.write("           </tr>\r\n");
      out.write("           <tr>\r\n");
      out.write("               <td id=\"ft5\">\r\n");
      out.write("                    @content by all right\r\n");
      out.write("               </td>\r\n");
      out.write("           </tr>\r\n");
      out.write("        </table>\r\n");
      out.write("        <br><br>\r\n");
      out.write("       </div>\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
